// Generated by scripts/build-home-assets.ts --slides (docs/LANDING.md 2.0, 4.2, 6.1, 6.3); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The agents band's placeholders (`[data-fill]` in `[data-reserve="agents"]`), imported only by
// its chunk (bands.generated.ts).
import type { BandFills } from '../bands.generated';

export const FILLS: BandFills = {
  agents:
    '<div class="ts-sheet sheet ts-home-slide" data-home-slides data-slide="next-steps" data-instance="agents" data-counter="5 / 9"><div class="ts-stage stage"><div class="frame"><div class="rule top"></div><div class="rule bottom"></div><span class="cross tl"></span><span class="cross tr"></span><span class="cross bl"></span><span class="cross br"></span></div><section class="slide is-on" data-slide="next-steps" data-kind="content"><div class="in"><div class="cols"><div class="stack" data-slot="left"><div class="ts-home-h2" data-block="h" data-type="heading" data-run="h/text" data-object="next-steps#h" tabindex="-1" role="group" aria-roledescription="text box" aria-label="Heading">Next steps with Northwind</div><p class="max-p" data-block="p1" data-type="paragraph" data-run="p1/text" data-object="next-steps#p1" tabindex="-1" role="group" aria-roledescription="text box" aria-label="Text"></p></div><div data-slot="right" class="rows tight" style="--key:220px" data-block="rows" data-type="rows" data-object="next-steps#rows" tabindex="-1" role="group" aria-roledescription="text box" aria-label="Rows"><div><b data-run="rows/items/0/key">Monday</b><span data-run="rows/items/0/value">Northwind sellers get the deck</span></div><div><b data-run="rows/items/1/key">Wednesday</b><span data-run="rows/items/1/value">Agents draft slides over MCP</span></div><div><b data-run="rows/items/2/key">Friday</b><span data-run="rows/items/2/value">The first call uses this deck</span></div></div></div></div></section><div class="wordmark" aria-hidden="true"><svg width="28" height="18" fill="currentColor"><use href="#ts-mark"/></svg></div><div class="counter" data-counter-text>5 / 9</div></div></div>',
};
