// Generated by scripts/build-home-assets.ts --slides (docs/LANDING.md 2.0, 4.2, 6.1, 6.3); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The present band's placeholders (`[data-fill]` in `[data-reserve="present"]`), imported only by
// its chunk (bands.generated.ts).
import type { BandFills } from '../bands.generated';

export const FILLS: BandFills = {
  present:
    '<div class="ts-sheet sheet ts-home-slide" data-home-slides data-slide="gets" data-instance="present" data-counter="3 / 9"><div class="ts-stage stage"><div class="frame"><div class="rule top"></div><div class="rule bottom"></div><span class="cross tl"></span><span class="cross tr"></span><span class="cross bl"></span><span class="cross br"></span></div><section class="slide is-on" data-slide="gets" data-kind="content"><div class="in"><div class="cols"><div class="stack" data-slot="left"><div class="ts-home-h2" data-block="h" data-type="heading" data-run="h/text" data-object="gets#h" tabindex="0" role="group" aria-roledescription="text box" aria-label="Heading">What Northwind gets</div><p class="max-p" data-block="p1" data-type="paragraph" data-run="p1/text" data-object="gets#p1" tabindex="0" role="group" aria-roledescription="text box" aria-label="Text">Three things on the first day.</p></div><div data-slot="right" class="rows tight" style="--key:220px" data-block="rows" data-type="rows" data-object="gets#rows" tabindex="0" role="group" aria-roledescription="text box" aria-label="Rows"><div><b data-run="rows/items/0/key">Name</b><span data-run="rows/items/0/value">Their name on every slide</span></div><div><b data-run="rows/items/1/key">Theme</b><span data-run="rows/items/1/value">One theme for every deck</span></div><div><b data-run="rows/items/2/key">Drafts</b><span data-run="rows/items/2/value">Agents that draft the first slides</span></div></div></div></div></section><div class="wordmark" aria-hidden="true"><svg width="28" height="18" fill="currentColor"><use href="#ts-mark"/></svg></div><div class="counter" data-counter-text>3 / 9</div></div></div>',
};
