// The action table (SPEC 7.1): one typed constant from which the CLI subcommands, the MCP tool
// list, the window API's describe().actions, the OpenAPI document, the palette entries and the
// skills' reference tables are generated by `pnpm generate:contracts`. Every entry is declared
// now, including the ones whose implementation lands later; the dispatcher answers
// not_implemented (HTTP 501) for those (MILESTONES M1 item 3). Every mutating action takes
// baseRevision and rejects a stale one with 409 and the current document.
import { z } from 'zod';
import {
  assetMetricsSchema,
  assetSchema,
  assetSourceSchema,
  assetTreatmentSchema,
  assetTwinsSchema,
  ASSET_ROLES,
} from './assets.ts';
import { blockSchema } from './blocks.ts';
import { materialCatalogEntrySchema, materialUniformsSchema } from './blocks/material.ts';
import {
  APPEARANCES,
  COUNTER_MODES,
  LAYOUT_IDS,
  layoutSchema,
  PLATE_SIDES,
  sectionSchema,
  slideSchema,
  SLIDE_KINDS,
  SLOT_NAMES,
} from './deck.ts';
import { exportCheckSchema, exportReportSchema } from './export.ts';
import { findingSchema } from './findings.ts';
import { ALIGN_EDGES, ALIGN_TARGETS, DISTRIBUTE_AXES, ORDER_MOVES } from './freeform.ts';
import { blockIdSchema, slugSchema } from './ids.ts';
import { leaseSchema, mutationSchema, versionSchema } from './mutations.ts';
import { renderRecordSchema } from './render.ts';
import { RULE_IDS } from './rules.ts';

export type Transport = 'cli' | 'mcp' | 'http' | 'window';
export const TRANSPORTS = ['cli', 'mcp', 'http', 'window'] as const;
export const ALL_TRANSPORTS: ReadonlyArray<Transport> = TRANSPORTS;

/** M1 to M6 are the first six milestones; GS1 is the Google Slides parity round (docs/gslides-parity). */
export type Milestone = 'M1' | 'M2' | 'M3' | 'M4' | 'M5' | 'M6' | 'GS1';

/** The palette groups (SPEC 6.1) and the docs sections. */
export type ActionGroup =
  | 'deck'
  | 'slide'
  | 'block'
  | 'asset'
  | 'render'
  | 'lint'
  | 'version'
  | 'export'
  | 'view'
  | 'studio';

export type ActionCli = {
  /** The documented command; `<name>` tokens are positionals named after input keys. */
  usage: string;
  /** The input key read from stdin when the usage ends in `< file.json`. */
  stdin?: string;
};

export type ActionSpec = {
  id: ActionId;
  label: string;
  /** One sentence of documentation. */
  doc: string;
  group: ActionGroup;
  mutates: boolean;
  transports: ReadonlyArray<Transport>;
  milestone: Milestone;
  input: z.ZodType;
  output: z.ZodType;
  cli?: ActionCli;
  /** The MCP tool name, deck_<action>. */
  mcp?: string;
  /** An input that parses; the coverage test runs every example through `input`. */
  example: unknown;
};

export const ACTION_IDS = [
  'deck.info',
  'deck.create',
  'deck.rename',
  'deck.set',
  'deck.pack',
  'deck.unpack',
  'deck.push',
  'deck.pull',
  'deck.list',
  'deck.copy',
  'deck.trash',
  'deck.restore',
  'deck.remove',
  'slide.list',
  'slide.get',
  'slide.insert',
  'slide.remove',
  'slide.move',
  'slide.update',
  'slide.replace',
  'slide.setLayout',
  'slide.new',
  'slide.duplicate',
  'slide.skip',
  'slide.applyLayout',
  'slide.import',
  'text.replaceAll',
  'block.set',
  'block.insert',
  'block.remove',
  'block.move',
  'block.align',
  'block.distribute',
  'block.order',
  'block.duplicate',
  'section.set',
  'slide.lease',
  'asset.add',
  'asset.dither',
  'asset.capture',
  'material.capture',
  'material.list',
  'render.slide',
  'render.sheet',
  'lint.run',
  'fix.run',
  'diff.run',
  'version.save',
  'version.list',
  'version.restore',
  'judge.bundle',
  'view.goto',
  'view.mode',
  'view.theme',
  'view.present',
  'view.zoom',
  'export.run',
  'export.check',
  'export.text',
  'build.run',
  'fonts.build',
  'import.run',
  'validate.run',
  'source.read',
  'source.apply',
  'controls.list',
  'control.activate',
  'control.set',
  'artifact.download',
] as const;

export type ActionId = (typeof ACTION_IDS)[number];

// ---------------------------------------------------------------------------------------------
// Shared pieces

const baseRevision = z
  .number()
  .int()
  .nonnegative()
  .describe('The revision the caller read; a stale value is rejected with 409');
const revision = z.number().int().nonnegative();
const theme = z.enum(['light', 'dark']);
const themes = z.array(theme).min(1).describe('One or both themes');
const slideIdsOrAll = z
  .union([z.literal('all'), z.array(slugSchema).min(1)])
  .describe("Slide ids, or 'all'");
const slotSchema = z.enum([...SLOT_NAMES, 'plate']);

export const outlineSchema = z.array(
  z.strictObject({
    id: slugSchema,
    name: z.string(),
    slides: z.array(
      z.strictObject({
        id: slugSchema,
        n: z.number().int().positive(),
        title: z.string(),
        kind: z.enum(SLIDE_KINDS),
      }),
    ),
  }),
);

export const slideResultSchema = z.strictObject({
  slide: slideSchema,
  revision,
  findings: z.array(findingSchema),
});

const layoutId = z.enum(LAYOUT_IDS).describe('One of the layout list (gslides-parity SPEC 5.2)');
const slideIdList = z.array(slugSchema).min(1).describe('One or more slide ids');

const slideListRow = z.strictObject({
  id: slugSchema,
  n: z.number().int().positive(),
  section: slugSchema,
  title: z.string(),
  kind: z.enum(SLIDE_KINDS),
  lint: z.strictObject({ s3: z.number().int().nonnegative(), s2: z.number().int().nonnegative() }),
  /** true for a skipped slide (gslides-parity SPEC 7.2.1) */
  skip: z.boolean().optional(),
  /** the layout the slide was made from, when written (gslides-parity SPEC 7.2.2) */
  template: layoutId.optional(),
});

export const viewStateSchema = z.strictObject({
  slideId: slugSchema,
  n: z.number().int().positive(),
  mode: z.enum(['slide', 'grid', 'book']),
  theme,
  present: z.boolean(),
  edit: z.boolean().optional(),
  /** the stage scale, or 'fit' (gslides-parity SPEC 7.2.16) */
  zoom: z.union([z.number().positive(), z.literal('fit')]).optional(),
});

/** One deck of the deck list (gslides-parity SPEC 7.5 deck.list): the manifest facts, newest first. */
export const deckHeadSchema = z.strictObject({
  id: slugSchema,
  title: z.string(),
  slides: z.number().int().nonnegative(),
  sections: z.number().int().nonnegative(),
  revision: z.number().int().nonnegative(),
  updatedAt: z.string(),
  createdAt: z.string(),
  /** set when the deck is in the trash; such rows appear only with includeTrashed */
  trashedAt: z.string().optional(),
});

const deckTrashState = z.strictObject({
  id: slugSchema,
  /** the trash stamp, or null when the deck is not in the trash */
  trashedAt: z.string().nullable(),
  revision,
});

const empty = z.strictObject({});

const plateSide = z
  .enum(PLATE_SIDES)
  .describe('The plate rectangle the metrics are screened against');

/**
 * The two-tone parameters a capture or an intake takes before the pipeline fills the fixed
 * fields (kind, autocontrast 0.5, cell 2, bayer 8, lanczos3) and the crop default of the whole
 * source; every field is optional so `--black 24` alone is a complete request (SPEC 5.4).
 */
export const twoToneParamsSchema = z.strictObject({
  crop: z
    .tuple([z.number(), z.number(), z.number(), z.number()])
    .optional()
    .describe('Left, top, right, bottom in source pixels; may reach past the source'),
  channel: z.enum(['gray', 'r', 'g', 'b']).optional(),
  invert: z.boolean().optional(),
  blur: z.number().nonnegative().optional(),
  black: z.number().min(0).max(255).optional(),
  white: z.number().min(0).max(255).optional(),
  gamma: z.number().positive().optional(),
  minFilter: z.number().positive().optional(),
  polarity: z.enum(['dark-ground', 'light-ground']).optional(),
});

/** One asset's dither report: the twins, the metrics and the verification counts. */
export const ditherResultSchema = z.strictObject({
  assetId: slugSchema,
  twins: assetTwinsSchema,
  metrics: assetMetricsSchema.optional(),
  /** Cells of a screen regenerated from the source that differ from the committed dark twin. */
  mismatchedCells: z.number().int().nonnegative().optional(),
  /** Cells where the committed light twin is not the inverse of the dark one. */
  twinInverseMismatch: z.number().int().nonnegative().optional(),
  /** The recorded treatment lacks a parameter the pipeline needs, so it could not be re-run. */
  missingParameter: z.boolean().optional(),
  /** No continuous source is on disk (sourceFile absent), so the cells were not re-run. */
  missingSource: z.boolean().optional(),
  /** The committed twin files are not on disk, so nothing was read back. */
  missingTwins: z.boolean().optional(),
  /** Files written under assets/, relative to the deck directory. */
  written: z.array(z.string()),
});

/**
 * What deck.create starts from: the GT brand template record under decks/templates/gt-brand
 * (the deck's manifest and slides with a template.json naming it), or one title slide.
 */
export const DECK_TEMPLATES = ['gt-brand', 'blank'] as const;
export type DeckTemplateId = (typeof DECK_TEMPLATES)[number];

/**
 * The deck bundle shapes (docs/deck-transfer.md): what deck.pack reports, what deck.unpack and
 * deck.pull take and report; deck.push reports the same with the editor URL on the studio.
 */
const bundleCounts = z.strictObject({
  slides: z.number().int().nonnegative(),
  assets: z.number().int().nonnegative(),
  versions: z.number().int().nonnegative(),
  documents: z.number().int().nonnegative(),
});

export const bundlePackResultSchema = z.strictObject({
  deckId: slugSchema,
  title: z.string(),
  revision,
  out: z.string().describe('The zip written'),
  bytes: z.number().int().nonnegative(),
  sha256: z.string(),
  counts: z.strictObject({
    documents: z.number().int().nonnegative(),
    assets: z.number().int().nonnegative(),
    versions: z.number().int().nonnegative(),
  }),
});

export const bundleUnpackInputSchema = z.strictObject({
  file: z.string().describe('The bundle zip to read'),
  as: slugSchema.optional().describe('The deck id to write under; the bundle id when absent'),
  replace: z
    .boolean()
    .optional()
    .describe('Remove the deck that holds the id first; without it a taken id gets a free sibling'),
});

export const bundleUnpackResultSchema = z.strictObject({
  deckId: slugSchema.describe('The id the deck was written under'),
  sourceDeckId: slugSchema.describe('The id the bundle carried'),
  title: z.string(),
  revision,
  dir: z.string().describe('The deck directory'),
  replaced: z.boolean(),
  renamed: z.boolean(),
  counts: bundleCounts,
});

const A = ALL_TRANSPORTS;
const noWindow: ReadonlyArray<Transport> = ['cli', 'mcp', 'http'];

function action(spec: ActionSpec): ActionSpec {
  return spec;
}

// ---------------------------------------------------------------------------------------------
// The table

export const ACTIONS: Readonly<Record<ActionId, ActionSpec>> = {
  'deck.info': action({
    id: 'deck.info',
    label: 'Deck info',
    doc: 'Title, theme, sections with slide ids and titles, counts and the current revision.',
    group: 'deck',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: empty,
    output: z.strictObject({
      id: slugSchema,
      title: z.string(),
      theme: z.string(),
      revision,
      sections: outlineSchema,
      counts: z.strictObject({
        slides: z.number().int(),
        sections: z.number().int(),
        assets: z.number().int(),
        htmlBlocks: z.number().int(),
        /** skipped slides, left out of the slideshow and the downloads unless asked */
        skipped: z.number().int().optional(),
      }),
      /** the deck's appearance and counter defaults (gslides-parity SPEC 7.2.3, 7.2.4) */
      defaults: z
        .strictObject({
          notes: z.string().optional(),
          appearance: z.enum(APPEARANCES).optional(),
          counter: z.enum(COUNTER_MODES).optional(),
        })
        .optional(),
      trashedAt: z.string().optional(),
    }),
    cli: { usage: 'turboslide info' },
    mcp: 'deck_get_info',
    example: {},
  }),
  'deck.create': action({
    id: 'deck.create',
    label: 'New deck',
    doc: 'Creates a deck under decks/ from the GT brand template or as one title slide, and returns its id, revision and counts.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'M4',
    input: z.strictObject({
      name: z.string().min(1).describe('The deck title; the id is its slug unless `id` is given'),
      from: z
        .enum(DECK_TEMPLATES)
        .describe(
          "'gt-brand' copies decks/templates/gt-brand (85 slides, 8 sections, the assets); 'blank' writes one title slide",
        ),
      id: slugSchema
        .optional()
        .describe('The deck id under decks/; derived from the name when absent'),
    }),
    output: z.strictObject({
      deckId: slugSchema,
      title: z.string(),
      from: z.enum(DECK_TEMPLATES),
      revision,
      dir: z.string().describe('The deck directory'),
      counts: z.strictObject({
        slides: z.number().int().nonnegative(),
        sections: z.number().int().nonnegative(),
        assets: z.number().int().nonnegative(),
      }),
    }),
    cli: { usage: 'turboslide deck create <name> --from <from> --id <id>' },
    mcp: 'deck_create',
    example: { name: 'Q4 review', from: 'gt-brand' },
  }),
  'deck.rename': action({
    id: 'deck.rename',
    label: 'Rename deck',
    doc: 'Sets the deck title, the name the sidebar head, the toolbar and the deck list show; one deck.set of /title.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'M4',
    input: z.strictObject({ name: z.string().min(1).describe('The new title'), baseRevision }),
    output: z.strictObject({ title: z.string(), revision }),
    cli: { usage: 'turboslide deck rename <name>' },
    mcp: 'deck_rename',
    example: { name: 'GT brand deck, Q4', baseRevision: 412 },
  }),
  'deck.set': action({
    id: 'deck.set',
    label: 'Set a deck field',
    doc: 'Writes one field of the deck manifest by JSON pointer (/title, /theme, /defaults/appearance, /defaults/counter, /defaults/notes) as one deck.set mutation, the write the Themes panel and Slide numbers make; an absent value removes the field.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      path: z
        .string()
        .regex(/^\/(title|theme|defaults(\/[a-zA-Z]+)?)$/)
        .describe(
          'JSON pointer into the manifest: /title, /theme, /defaults/appearance, /defaults/counter or /defaults/notes',
        ),
      value: z.unknown().optional().describe('The new value; omit it to remove the field'),
      baseRevision,
    }),
    output: z.strictObject({
      path: z.string(),
      value: z.unknown().optional().describe('The value now at the path; absent when removed'),
      revision,
    }),
    cli: { usage: 'turboslide deck set <path> <value>' },
    mcp: 'deck_set',
    example: { path: '/defaults/appearance', value: 'light', baseRevision: 412 },
  }),
  'deck.pack': action({
    id: 'deck.pack',
    label: 'Pack deck bundle',
    doc: 'Writes decks/<id> (deck.json, slides, assets, versions and the sidecars) as one zip with a manifest.json carrying the bundle version, the deck id, its revision and a digest per file (docs/deck-transfer.md).',
    group: 'deck',
    mutates: false,
    transports: ['cli'],
    milestone: 'M6',
    input: z.strictObject({
      id: slugSchema.describe('The deck id under decks/'),
      out: z.string().optional().describe('The zip to write; defaults to <id>-r<revision>.zip'),
      versions: z
        .boolean()
        .optional()
        .describe('Carry versions/<n>.json; on by default (--no-versions turns it off)'),
    }),
    output: bundlePackResultSchema,
    cli: { usage: 'turboslide deck pack <id> --out <out>' },
    example: { id: 'gt-brand', out: 'gt-brand-r24.zip' },
  }),
  'deck.unpack': action({
    id: 'deck.unpack',
    label: 'Unpack deck bundle',
    doc: 'Creates a deck under decks/ from a bundle zip after validating it, under a free id when the bundle id is taken unless `replace` removes the deck that holds it (docs/deck-transfer.md).',
    group: 'deck',
    mutates: true,
    transports: ['cli'],
    milestone: 'M6',
    input: bundleUnpackInputSchema,
    output: bundleUnpackResultSchema,
    cli: { usage: 'turboslide deck unpack <file> --as <as> --replace' },
    example: { file: 'gt-brand-r24.zip', as: 'gt-brand-copy' },
  }),
  'deck.push': action({
    id: 'deck.push',
    label: 'Push deck to a studio',
    doc: 'Packs decks/<id> and uploads the bundle to a hosted studio through POST /api/decks/bundle with the bearer token, so the deck can be edited there (docs/deck-transfer.md).',
    group: 'deck',
    mutates: true,
    transports: ['cli'],
    milestone: 'M6',
    input: z.strictObject({
      id: slugSchema.describe('The deck id under decks/'),
      to: z.string().url().describe('The studio, such as https://turboslide.vercel.app'),
      token: z
        .string()
        .optional()
        .describe(
          'The bearer token (TURBOSLIDE_TOKEN of the deployment); kept in ~/.config/turboslide/hosts.json after the first use',
        ),
      as: slugSchema
        .optional()
        .describe('The id the deck takes on the studio; the local id when absent'),
      replace: z.boolean().optional().describe('Replace the deck of that id on the studio'),
      fromUrl: z
        .string()
        .url()
        .optional()
        .describe(
          'A bundle already stored at a URL the studio may read (the deck store Blob host); the studio fetches it instead of receiving the bytes, for bundles over a function 4.5 MB body cap',
        ),
    }),
    output: bundleUnpackResultSchema.extend({
      url: z.string().describe('The editor URL of the deck on the studio'),
    }),
    cli: {
      usage:
        'turboslide deck push <id> --to <to> --token <token> --as <as> --replace --from-url <fromUrl>',
    },
    example: { id: 'gt-brand', to: 'https://turboslide.vercel.app' },
  }),
  'deck.pull': action({
    id: 'deck.pull',
    label: 'Pull deck from a studio',
    doc: 'Downloads a deck bundle from a hosted studio through GET /api/decks/<id>/bundle with the bearer token and unpacks it into decks/, so the deck can be edited locally (docs/deck-transfer.md).',
    group: 'deck',
    mutates: true,
    transports: ['cli'],
    milestone: 'M6',
    input: z.strictObject({
      id: slugSchema.describe('The deck id on the studio'),
      from: z.string().url().describe('The studio, such as https://turboslide.vercel.app'),
      token: z
        .string()
        .optional()
        .describe(
          'The bearer token (TURBOSLIDE_TOKEN of the deployment); kept in ~/.config/turboslide/hosts.json after the first use',
        ),
      as: slugSchema
        .optional()
        .describe('The id the deck takes under decks/; the id on the studio when absent'),
      replace: z.boolean().optional().describe('Replace the local deck of that id'),
    }),
    output: bundleUnpackResultSchema,
    cli: { usage: 'turboslide deck pull <id> --from <from> --token <token> --as <as> --replace' },
    example: { id: 'gt-brand', from: 'https://turboslide.vercel.app', as: 'gt-brand-hosted' },
  }),
  'deck.list': action({
    id: 'deck.list',
    label: 'List decks',
    doc: 'The manifest facts of every deck under decks/ (id, title, slide and section counts, revision, the stamps), newest first; decks in the trash are left out unless asked.',
    group: 'deck',
    mutates: false,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      includeTrashed: z
        .boolean()
        .optional()
        .describe('Also list the decks in the trash, each with its trashedAt'),
    }),
    output: z.array(deckHeadSchema),
    cli: { usage: 'turboslide deck list --include-trashed' },
    mcp: 'deck_list',
    example: {},
  }),
  'deck.copy': action({
    id: 'deck.copy',
    label: 'Make a copy',
    doc: 'Copies a deck under a new id with a new title, every slide or the named ones, with or without the speaker notes, at revision 0 with an empty version log; the output names the new deck.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      id: slugSchema.describe('The deck to copy'),
      name: z
        .string()
        .min(1)
        .describe('The title of the copy; its id is the slug unless `newId` is given'),
      newId: slugSchema.optional().describe('The id of the copy under decks/'),
      slideIds: z
        .array(slugSchema)
        .min(1)
        .optional()
        .describe('Copy these slides only, in deck order; every slide when absent'),
      removeNotes: z.boolean().optional().describe('Leave the speaker notes out of the copy'),
      baseRevision: baseRevision.describe(
        'The revision of the source deck the caller read; a stale value is rejected with 409',
      ),
    }),
    output: z.strictObject({
      deckId: slugSchema.describe('The id of the copy'),
      sourceDeckId: slugSchema,
      title: z.string(),
      revision,
      dir: z.string().describe('The deck directory'),
      counts: z.strictObject({
        slides: z.number().int().nonnegative(),
        sections: z.number().int().nonnegative(),
        assets: z.number().int().nonnegative(),
      }),
    }),
    cli: {
      usage:
        'turboslide deck copy <id> --name <name> --id <newId> --slides <slideIds> --remove-notes',
    },
    mcp: 'deck_copy',
    example: { id: 'gt-brand', name: 'Copy of GT brand deck', baseRevision: 412 },
  }),
  'deck.trash': action({
    id: 'deck.trash',
    label: 'Move to trash',
    doc: 'Moves a deck to the trash by writing trashedAt on its manifest: the home page, the fresh presentation route and deck.list leave it out until deck.restore clears the stamp or deck.remove deletes it; nothing else changes.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      id: slugSchema.describe('The deck to move to the trash'),
      baseRevision: baseRevision.describe(
        'The revision the caller read; a stale value is rejected with 409',
      ),
    }),
    output: deckTrashState,
    cli: { usage: 'turboslide deck trash <id>' },
    mcp: 'deck_trash',
    example: { id: 'q4-review', baseRevision: 3 },
  }),
  'deck.restore': action({
    id: 'deck.restore',
    label: 'Restore from trash',
    doc: 'Clears trashedAt on a deck in the trash, so the home page and deck.list show it again.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      id: slugSchema.describe('The deck to restore'),
      baseRevision: baseRevision.describe(
        'The revision the caller read; a stale value is rejected with 409',
      ),
    }),
    output: deckTrashState,
    cli: { usage: 'turboslide deck restore <id>' },
    mcp: 'deck_restore',
    example: { id: 'q4-review', baseRevision: 3 },
  }),
  'deck.remove': action({
    id: 'deck.remove',
    label: 'Delete forever',
    doc: 'Deletes a deck: the folder under decks/ or the prefix in the Blob store, with its slides, assets and version log. Irreversible; the Trash page calls it, and `confirm` must be true.',
    group: 'deck',
    mutates: true,
    transports: ['cli', 'http', 'window'],
    milestone: 'GS1',
    input: z.strictObject({
      id: slugSchema.describe('The deck to delete'),
      confirm: z.literal(true).describe('The caller has confirmed the deletion'),
      baseRevision: baseRevision.describe(
        'The revision the caller read; a stale value is rejected with 409',
      ),
    }),
    output: z.strictObject({ id: slugSchema, removed: z.literal(true) }),
    cli: { usage: 'turboslide deck remove <id> --confirm' },
    example: { id: 'q4-review', confirm: true, baseRevision: 3 },
  }),
  'slide.list': action({
    id: 'slide.list',
    label: 'List slides',
    doc: 'Every slide in deck order with its number, section, title, kind and lint counts.',
    group: 'slide',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({ sectionId: slugSchema.optional() }),
    output: z.array(slideListRow),
    cli: { usage: 'turboslide slides' },
    mcp: 'deck_list_slides',
    example: {},
  }),
  'slide.get': action({
    id: 'slide.get',
    label: 'Get slide',
    doc: 'The normalized slide, the assets it references and its last render record.',
    group: 'slide',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({ slideId: slugSchema }),
    output: z.strictObject({
      slide: slideSchema,
      n: z.number().int().positive(),
      section: slugSchema,
      assets: z.record(slugSchema, assetSchema),
      render: renderRecordSchema.nullable(),
    }),
    cli: { usage: 'turboslide slide get <slideId>' },
    mcp: 'deck_get_slide',
    example: { slideId: 'content-rule' },
  }),
  'slide.insert': action({
    id: 'slide.insert',
    label: 'Insert slide',
    doc: 'Inserts a slide into a section after the named slide, or first.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      sectionId: slugSchema,
      after: slugSchema.optional(),
      slide: slideSchema,
      baseRevision,
    }),
    output: z.strictObject({ slide: slideSchema, revision, outline: outlineSchema }),
    cli: {
      usage: 'turboslide slide insert --section <sectionId> --after <after> < slide.json',
      stdin: 'slide',
    },
    mcp: 'deck_insert_slide',
    example: {
      sectionId: 'brand',
      after: 'thesis',
      baseRevision: 412,
      slide: { schemaVersion: 1, id: 'why', kind: 'statement', big: 'Why the redesign' },
    },
  }),
  'slide.remove': action({
    id: 'slide.remove',
    label: 'Remove slide',
    doc: 'Removes a slide from the deck and its section.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ slideId: slugSchema, baseRevision }),
    output: z.strictObject({ revision, outline: outlineSchema }),
    cli: { usage: 'turboslide slide remove <slideId>' },
    mcp: 'deck_remove_slide',
    example: { slideId: 'why', baseRevision: 413 },
  }),
  'slide.move': action({
    id: 'slide.move',
    label: 'Move slide',
    doc: 'Moves a slide to a section after the named slide, or first.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      sectionId: slugSchema,
      after: slugSchema.optional(),
      baseRevision,
    }),
    output: z.strictObject({ sections: z.array(sectionSchema), revision }),
    cli: { usage: 'turboslide slide move <slideId> --to <sectionId> --after <after>' },
    mcp: 'deck_move_slide',
    example: { slideId: 'content-rule', sectionId: 'website', baseRevision: 412 },
  }),
  'slide.update': action({
    id: 'slide.update',
    label: 'Patch slide',
    doc: 'Applies a mutation list to one slide and returns the normalized slide with its findings.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      baseRevision,
      mutations: z.array(mutationSchema).min(1),
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide slide patch <slideId> --set <pointer>=<value>' },
    mcp: 'deck_update_slide',
    example: {
      slideId: 'content-rule',
      baseRevision: 412,
      mutations: [
        { op: 'slide.set', slideId: 'content-rule', path: '/layout/ratio', value: '4/8' },
      ],
    },
  }),
  'slide.replace': action({
    id: 'slide.replace',
    label: 'Replace slide',
    doc: 'Replaces a slide with the given document; what the source drawer’s Apply emits.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ slideId: slugSchema, baseRevision, slide: slideSchema }),
    output: slideResultSchema,
    cli: { usage: 'turboslide slide put <slideId> < slide.json', stdin: 'slide' },
    mcp: 'deck_replace_slide',
    example: {
      slideId: 'thesis',
      baseRevision: 412,
      slide: {
        schemaVersion: 1,
        id: 'thesis',
        kind: 'statement',
        big: 'Every product in every language',
        measure: 22,
      },
    },
  }),
  'slide.setLayout': action({
    id: 'slide.setLayout',
    label: 'Set layout',
    doc: 'Moves a content slide to another layout and refiles its blocks: to freeform every block gets a position box from its slot, from freeform the boxes are dropped and the blocks fall into the target slots by geometry (docs/freeform.md).',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M6',
    input: z.strictObject({
      slideId: slugSchema,
      layout: layoutSchema.describe('The target layout with its options'),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: {
      usage:
        'turboslide slide set-layout <slideId> --type <type> --ratio <ratio> --gap <gap> --layout <layout>',
    },
    mcp: 'deck_set_layout',
    example: { slideId: 'content-rule', layout: { type: 'freeform' }, baseRevision: 412 },
  }),
  'slide.new': action({
    id: 'slide.new',
    label: 'New slide',
    doc: 'Inserts one slide made from a layout with empty placeholders after the named slide (or first in the section), as one slide.insert with template set; a Section header starts a new section that takes the slides after the anchor.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      layout: layoutId,
      after: slugSchema
        .optional()
        .describe('The slide the new one follows; first in the section when absent'),
      sectionId: slugSchema
        .optional()
        .describe("The section; the anchor's section, or the last section, when absent"),
      id: slugSchema
        .optional()
        .describe('The slide id; <layout>-<n> with the first free n when absent'),
      baseRevision,
    }),
    output: z.strictObject({ slide: slideSchema, revision, outline: outlineSchema }),
    cli: {
      usage:
        'turboslide slide new --layout <layout> --after <after> --section <sectionId> --id <id>',
    },
    mcp: 'deck_new_slide',
    example: { layout: 'big-number', after: 'content-rule', baseRevision: 412 },
  }),
  'slide.duplicate': action({
    id: 'slide.duplicate',
    label: 'Duplicate slide',
    doc: 'Copies the named slides with fresh ids after the last of them, in one write; a copied section header starts a new section.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({ slideIds: slideIdList, baseRevision }),
    output: z.strictObject({ slides: z.array(slideSchema), revision, outline: outlineSchema }),
    cli: { usage: 'turboslide slide duplicate <slideIds>' },
    mcp: 'deck_duplicate_slide',
    example: { slideIds: ['content-rule'], baseRevision: 412 },
  }),
  'slide.skip': action({
    id: 'slide.skip',
    label: 'Skip slide',
    doc: 'Sets or clears skip on the named slides in one write: a skipped slide is left out of the slideshow, the shared view, the downloads and the print unless asked.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      slideIds: slideIdList,
      skip: z.boolean().describe('true skips the slides, false shows them again'),
      baseRevision,
    }),
    output: z.strictObject({ slideIds: z.array(slugSchema), skip: z.boolean(), revision }),
    cli: { usage: 'turboslide slide skip <slideIds> --off' },
    mcp: 'deck_skip_slide',
    example: { slideIds: ['content-rule'], skip: true, baseRevision: 412 },
  }),
  'slide.applyLayout': action({
    id: 'slide.applyLayout',
    label: 'Apply layout',
    doc: 'Applies a layout to the named slides in one write, one slide.replace per slide: the title, the body, the lists, the tables and the pictures move into the matching placeholders and the rest is appended; only a Title slide or a Main point drops what does not fit, and the output names the dropped blocks.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({ slideIds: slideIdList, layout: layoutId, baseRevision }),
    output: z.strictObject({
      slides: z.array(slideSchema),
      dropped: z.array(z.strictObject({ slideId: slugSchema, blockIds: z.array(blockIdSchema) })),
      /** slides moved to the front of their section because they became a Section header */
      moved: z.array(slugSchema),
      revision,
      findings: z.array(findingSchema),
    }),
    cli: { usage: 'turboslide slide apply-layout <slideIds> <layout>' },
    mcp: 'deck_apply_layout',
    example: { slideIds: ['content-rule'], layout: 'title', baseRevision: 412 },
  }),
  'slide.import': action({
    id: 'slide.import',
    label: 'Import slides',
    doc: 'Copies slides from another deck after the named slide in one write: the assets they use are copied into this deck, colliding slide ids are renamed, and the output lists the slides and the assets that came over.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      sourceDeckId: slugSchema.describe('The deck the slides come from'),
      slideIds: slideIdList.describe('The slides to copy, in the order they land'),
      after: slugSchema
        .optional()
        .describe('The slide the copies follow; first in the section when absent'),
      sectionId: slugSchema
        .optional()
        .describe("The section; the anchor's section, or the last section, when absent"),
      baseRevision,
    }),
    output: z.strictObject({
      slides: z.array(slideSchema),
      assets: z.array(slugSchema).describe('The asset ids copied into this deck'),
      renamed: z.array(z.strictObject({ from: slugSchema, to: slugSchema })),
      revision,
      outline: outlineSchema,
    }),
    cli: {
      usage:
        'turboslide slide import <sourceDeckId> <slideIds> --after <after> --section <sectionId>',
    },
    mcp: 'deck_import_slides',
    example: { sourceDeckId: 'gt-brand', slideIds: ['thesis'], after: 'title', baseRevision: 412 },
  }),
  'text.replaceAll': action({
    id: 'text.replaceAll',
    label: 'Find and replace',
    doc: 'Replaces every occurrence of a string in the visible text of the deck (every Text of every block, the title slide fields, the table cells and the speaker notes) in one write, case insensitive unless asked; the output counts the replacements.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      find: z.string().min(1),
      replace: z.string(),
      matchCase: z.boolean().optional().describe('Match the case exactly; off by default'),
      slideIds: z.array(slugSchema).min(1).optional().describe('Restrict to these slides'),
      baseRevision,
    }),
    output: z.strictObject({
      replacements: z.number().int().nonnegative(),
      slideIds: z.array(slugSchema).describe('The slides that changed'),
      revision,
    }),
    cli: { usage: 'turboslide text replace <find> <replace> --match-case --slides <slideIds>' },
    mcp: 'deck_replace_text',
    example: { find: 'Acme', replace: 'Globex', baseRevision: 412 },
  }),
  'block.set': action({
    id: 'block.set',
    label: 'Set block property',
    doc: 'Writes one property of a block by JSON pointer; an absent value deletes it.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      blockId: blockIdSchema,
      path: z.string().describe('JSON pointer inside the block, such as /key'),
      value: z.unknown().optional().describe('The new value; omit it to delete the property'),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block set <slideId>#<blockId> <path> <value>' },
    mcp: 'deck_update_block',
    example: {
      slideId: 'content-rule',
      blockId: 'list',
      path: '/size',
      value: 22,
      baseRevision: 412,
    },
  }),
  'block.insert': action({
    id: 'block.insert',
    label: 'Insert block',
    doc: 'Inserts a block into a slot after the named block, or first.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      slot: slotSchema,
      after: blockIdSchema.optional(),
      block: blockSchema,
      baseRevision,
    }),
    output: slideResultSchema,
    cli: {
      usage: 'turboslide block insert <slideId> --slot <slot> --after <after> < block.json',
      stdin: 'block',
    },
    mcp: 'deck_insert_block',
    example: {
      slideId: 'content-rule',
      slot: 'left',
      after: 'p1',
      baseRevision: 412,
      block: { id: 'p2', type: 'paragraph', text: 'A second paragraph.' },
    },
  }),
  'block.remove': action({
    id: 'block.remove',
    label: 'Remove block',
    doc: 'Removes a block from its slide.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ slideId: slugSchema, blockId: blockIdSchema, baseRevision }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block remove <slideId>#<blockId>' },
    mcp: 'deck_remove_block',
    example: { slideId: 'content-rule', blockId: 'p1', baseRevision: 412 },
  }),
  'block.move': action({
    id: 'block.move',
    label: 'Move block',
    doc: 'Moves a block to a slot after the named block, or first.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      blockId: blockIdSchema,
      slot: slotSchema,
      after: blockIdSchema.optional(),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block move <slideId>#<blockId> --slot <slot> --after <after>' },
    mcp: 'deck_move_block',
    example: {
      slideId: 'content-rule',
      blockId: 'list',
      slot: 'left',
      after: 'p1',
      baseRevision: 412,
    },
  }),
  'block.align': action({
    id: 'block.align',
    label: 'Align blocks',
    doc: 'Aligns the position boxes of freeform blocks on one edge, against the selection, the content box or the sheet, and snaps the result unless snap is false.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M6',
    input: z.strictObject({
      slideId: slugSchema,
      blockIds: z
        .array(blockIdSchema)
        .min(1)
        .describe('The blocks to move, top level of a freeform slide'),
      edge: z
        .enum(ALIGN_EDGES)
        .describe('left, center or right move x; top, middle or bottom move y'),
      to: z
        .enum(ALIGN_TARGETS)
        .optional()
        .describe(
          "The reference box; 'selection' for several blocks and 'content' for one unless set",
        ),
      snap: z
        .boolean()
        .optional()
        .describe('Snap the moved edges to the guides and the grid; on unless false'),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block align <slideId> --blocks <blockIds> --edge <edge> --to <to>' },
    mcp: 'deck_align_blocks',
    example: { slideId: 'content-rule', blockIds: ['h', 'p1'], edge: 'left', baseRevision: 412 },
  }),
  'block.distribute': action({
    id: 'block.distribute',
    label: 'Distribute blocks',
    doc: 'Spreads freeform blocks along one axis with equal gaps between the first and the last, or with a fixed gap; with snap the moved edges round to the 8 px grid.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M6',
    input: z.strictObject({
      slideId: slugSchema,
      blockIds: z.array(blockIdSchema).min(2),
      axis: z.enum(DISTRIBUTE_AXES),
      gap: z
        .number()
        .nonnegative()
        .optional()
        .describe('A fixed gap in px instead of equal spacing'),
      snap: z.boolean().optional(),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: {
      usage: 'turboslide block distribute <slideId> --blocks <blockIds> --axis <axis> --gap <gap>',
    },
    mcp: 'deck_distribute_blocks',
    example: {
      slideId: 'content-rule',
      blockIds: ['h', 'p1', 'list'],
      axis: 'vertical',
      baseRevision: 412,
    },
  }),
  'block.order': action({
    id: 'block.order',
    label: 'Order block',
    doc: 'Moves a freeform block through the stacking order, to the front or back or by one step, or to a given z rank, and renumbers the stack densely.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M6',
    input: z
      .strictObject({
        slideId: slugSchema,
        blockId: blockIdSchema,
        move: z.enum(ORDER_MOVES).optional(),
        z: z.number().int().optional().describe('The target rank in the stack, 0 at the back'),
        baseRevision,
      })
      .refine((value) => (value.move === undefined) !== (value.z === undefined), {
        message: 'block.order takes move or z, not both and not neither',
        path: ['move'],
      }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block order <slideId>#<blockId> --move <move> --z <z>' },
    mcp: 'deck_order_block',
    example: { slideId: 'content-rule', blockId: 'h', move: 'front', baseRevision: 412 },
  }),
  'block.duplicate': action({
    id: 'block.duplicate',
    label: 'Duplicate block',
    doc: 'Copies the named blocks of a slide with fresh ids, each after its original; on a freeform slide the copy sits 16 px right and down and on top of the stack.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      slideId: slugSchema,
      blockIds: z.array(blockIdSchema).min(1),
      baseRevision,
    }),
    output: slideResultSchema.extend({
      blockIds: z.array(blockIdSchema).describe('The ids of the copies, in input order'),
    }),
    cli: { usage: 'turboslide block duplicate <slideId> --blocks <blockIds>' },
    mcp: 'deck_duplicate_block',
    example: { slideId: 'content-rule', blockIds: ['p1'], baseRevision: 412 },
  }),
  'section.set': action({
    id: 'section.set',
    label: 'Set sections',
    doc: 'Replaces the section list, the only place slide order lives.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ sections: z.array(sectionSchema), baseRevision }),
    output: z.strictObject({ sections: z.array(sectionSchema), revision }),
    cli: { usage: 'turboslide sections set < sections.json', stdin: 'sections' },
    mcp: 'deck_set_sections',
    example: {
      baseRevision: 412,
      sections: [{ id: 'brand', name: 'Brand', slideIds: ['opener-brand', 'title'] }],
    },
  }),
  'slide.lease': action({
    id: 'slide.lease',
    label: 'Lease slide',
    doc: 'Takes a lease on a slide for the author; another author’s write is rejected with 409 unless forced.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      minutes: z.number().int().positive().max(120).optional().describe('Defaults to 10'),
      force: z.boolean().optional(),
      release: z.boolean().optional().describe('Give the author’s lease on the slide back'),
    }),
    output: leaseSchema,
    cli: { usage: 'turboslide lease <slideId> --minutes <minutes> --force --release' },
    mcp: 'deck_lease_slide',
    example: { slideId: 'content-rule', minutes: 10 },
  }),
  'asset.add': action({
    id: 'asset.add',
    label: 'Add asset',
    doc: 'Adds a file, a data URL or a fetched URL as an asset with its role, alt, license fields and optional two-tone treatment; returns the asset with twins and metrics.',
    group: 'asset',
    mutates: true,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({
      id: slugSchema.optional().describe('The asset id; a slug of the file name when omitted'),
      file: z
        .string()
        .optional()
        .describe('A path on the machine, or a data: URL from the studio’s drop or paste'),
      url: z.string().url().optional().describe('An http(s) URL to fetch, 25 MB at most'),
      role: z.enum(ASSET_ROLES),
      alt: z.string().min(1),
      source: assetSourceSchema
        .optional()
        .describe(
          'The provenance record; built from title, artist, license and sourceUrl when omitted',
        ),
      title: z.string().optional().describe('The picture’s name as the source states it'),
      artist: z.string().optional(),
      license: z
        .string()
        .optional()
        .describe('CC0, CC BY, CC BY-SA 4.0, public domain, or the text'),
      shareAlike: z
        .boolean()
        .optional()
        .describe('The license is share-alike: the credit must appear on the plate'),
      sourceUrl: z.string().url().optional().describe('Where the picture came from'),
      credit: z
        .string()
        .optional()
        .describe('The plate credit; composed from artist and license when omitted'),
      twoTone: z
        .boolean()
        .optional()
        .describe('Run the two-tone pipeline; the source is kept as assets/<id>.source.<ext>'),
      treatment: twoToneParamsSchema.optional(),
      plate: plateSide.optional(),
      baseRevision,
    }),
    output: assetSchema,
    cli: {
      usage:
        'turboslide asset add <file> --role <role> --alt <alt> --two-tone --black <black> --plate <plate>',
    },
    mcp: 'deck_asset_add',
    example: {
      file: 'photo.jpg',
      role: 'mood',
      alt: 'A photograph',
      artist: 'Hans Hillewaert',
      license: 'CC BY-SA 4.0',
      shareAlike: true,
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rosetta_Stone.JPG',
      twoTone: true,
      treatment: { black: 140, white: 230, gamma: 0.9 },
      plate: 'lower-right',
      baseRevision: 412,
    },
  }),
  'asset.dither': action({
    id: 'asset.dither',
    label: 'Dither asset',
    doc: 'Re-runs the two-tone pipeline on an asset with new parameters and reports plate clearance; with fromRecorded it reads the committed twins back and verifies them cell for cell.',
    group: 'asset',
    mutates: true,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({
      assetId: slugSchema.optional().describe('Required unless allTwoTone'),
      treatment: assetTreatmentSchema
        .optional()
        .describe(
          'The full treatment to run; the recorded one with the params merged when omitted',
        ),
      params: twoToneParamsSchema
        .optional()
        .describe('Parameters merged over the recorded treatment (--gamma, --black on the CLI)'),
      plate: plateSide.optional(),
      source: z.string().optional().describe('The continuous source when the asset records none'),
      allTwoTone: z.boolean().optional().describe('Every asset with a two-tone treatment'),
      fromRecorded: z
        .boolean()
        .optional()
        .describe('Read the committed twins back instead of regenerating; metrics are recomputed'),
      verifyCells: z
        .boolean()
        .optional()
        .describe('Regenerate from the source where one exists and count the cells that differ'),
      baseRevision,
    }),
    output: z.union([ditherResultSchema, z.array(ditherResultSchema)]),
    cli: {
      usage:
        'turboslide asset dither <assetId> --gamma <gamma> --plate <plate> --all-two-tone --from-recorded --verify-cells',
    },
    mcp: 'deck_asset_dither',
    example: {
      assetId: 'mood-earth',
      params: { gamma: 1.1 },
      plate: 'lower-right',
      baseRevision: 412,
    },
  }),
  'asset.capture': action({
    id: 'asset.capture',
    label: 'Capture page',
    doc: 'Captures a page at 1440 by 900 in one or both themes through a per-site recipe, optionally cropped to a region, with identical-region 2x detail crops as further assets.',
    group: 'asset',
    mutates: true,
    transports: noWindow,
    milestone: 'M5',
    input: z.strictObject({
      url: z.string().url(),
      id: slugSchema.optional().describe('The asset id; a slug of the URL when omitted'),
      alt: z.string().optional(),
      role: z.enum(['capture', 'detail']).optional(),
      viewport: z.tuple([z.number().int().positive(), z.number().int().positive()]).optional(),
      scale: z.literal([1, 2]).optional(),
      theme: z.enum(['light', 'dark', 'both']),
      region: z
        .tuple([z.number(), z.number(), z.number(), z.number()])
        .optional()
        .describe(
          'A CSS-pixel box x, y, w, h inside the page; both twins take the identical region',
        ),
      details: z
        .array(z.tuple([z.number(), z.number(), z.number(), z.number()]))
        .optional()
        .describe('Identical-region detail crops, one asset each as <id>-detail-<n>'),
      recipe: z.string().optional().describe('The per-site recipe; gt-site by default'),
      settleMs: z.number().int().nonnegative().optional(),
      format: z
        .enum(['jpg', 'png'])
        .optional()
        .describe('The twin file format; jpg at quality 92 by default'),
      allowHosts: z
        .array(z.string())
        .optional()
        .describe('Hosts beyond the built-in allowlist (SPEC 11 captureHosts)'),
      baseRevision,
    }),
    output: assetSchema,
    cli: {
      usage:
        'turboslide asset capture <url> --theme <theme> --scale <scale> --recipe <recipe> --region <region>',
    },
    mcp: 'deck_asset_capture',
    example: {
      url: 'https://generaltranslation.com/',
      theme: 'both',
      scale: 2,
      recipe: 'gt-site',
      baseRevision: 412,
    },
  }),
  'material.capture': action({
    id: 'material.capture',
    label: 'Capture material',
    doc: 'Renders a shader material at 3200 by 1800 and captures frozen frames at the given anchors as assets with recipe keys, through the two-tone screen when asked; one anchor returns the asset, several the list.',
    group: 'asset',
    mutates: true,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({
      materialId: z.string().min(1),
      preset: z
        .string()
        .optional()
        .describe('A palette preset of the material, under the uniforms'),
      uniforms: materialUniformsSchema.optional(),
      size: z.tuple([z.number().int().positive(), z.number().int().positive()]).optional(),
      anchors: z.array(z.number().nonnegative()).min(1).describe('Frame times in ms'),
      id: slugSchema.optional().describe('The asset id; <id>-<anchor> per anchor when several'),
      role: z.enum(['opener', 'mood', 'frame']).optional(),
      alt: z.string().optional(),
      twoTone: z.boolean().optional(),
      treatment: twoToneParamsSchema.optional(),
      plate: plateSide.optional(),
      backend: z.enum(['angle-metal', 'swiftshader']).optional(),
      baseRevision,
    }),
    output: z.union([assetSchema, z.array(assetSchema)]),
    cli: {
      usage:
        'turboslide material capture <materialId> --preset <preset> --uniforms <uniforms> --anchor <anchors> --two-tone --plate <plate>',
    },
    mcp: 'deck_material_capture',
    example: {
      materialId: 'paper:liquid-metal',
      preset: 'diamond',
      anchors: [5500],
      twoTone: true,
      treatment: { crop: [-1325, 105, 2709, 2374], black: 20 },
      plate: 'lower-left',
      baseRevision: 412,
    },
  }),
  'material.list': action({
    id: 'material.list',
    label: 'List materials',
    doc: 'The material catalog: every paper:* entry with its uniform schema and palette presets, and the proto:* engines with their availability.',
    group: 'asset',
    mutates: false,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({ materialId: z.string().optional() }),
    output: z.array(materialCatalogEntrySchema),
    cli: { usage: 'turboslide material list' },
    mcp: 'deck_material_list',
    example: {},
  }),
  'render.slide': action({
    id: 'render.slide',
    label: 'Render',
    doc: 'Renders slides in one or both themes at 1x or 2x and returns render records with image paths.',
    group: 'render',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      themes: themes.optional(),
      scale: z.literal([1, 2]).optional(),
      format: z.enum(['png', 'jpg']).optional(),
      out: z.string().optional().describe('Output directory; defaults to .turboslide/render'),
    }),
    output: z.strictObject({ records: z.array(renderRecordSchema), images: z.array(z.string()) }),
    cli: { usage: 'turboslide render <slideIds> --theme <themes> --out <out> --json' },
    mcp: 'deck_render',
    example: { slideIds: ['content-rule'], themes: ['light', 'dark'], scale: 1 },
  }),
  'render.sheet': action({
    id: 'render.sheet',
    label: 'Contact sheet',
    doc: 'Renders a contact sheet per theme with a JSON cell map from cell boxes to slide ids.',
    group: 'render',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      themes: themes.optional(),
      cols: z.number().int().positive().optional(),
      thumb: z.number().int().positive().optional().describe('Thumbnail width in px'),
      numbered: z.boolean().optional(),
      overlay: z.enum(['lint', 'plate']).optional(),
      out: z.string().optional(),
    }),
    output: z.strictObject({
      sheets: z.array(
        z.strictObject({
          theme,
          image: z.string(),
          cells: z.array(
            z.strictObject({
              slideId: slugSchema,
              n: z.number().int().positive(),
              box: z.tuple([z.number(), z.number(), z.number(), z.number()]),
            }),
          ),
        }),
      ),
    }),
    cli: { usage: 'turboslide sheet <slideIds> --cols <cols> --thumb <thumb> --overlay <overlay>' },
    mcp: 'deck_sheet',
    example: { slideIds: 'all', cols: 4, thumb: 480, numbered: true },
  }),
  'lint.run': action({
    id: 'lint.run',
    label: 'Lint',
    doc: 'Runs the grammar linter on slides in the static, rendered or both layers and returns findings.',
    group: 'lint',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      layers: z.enum(['static', 'rendered', 'both']).optional(),
      rule: z.enum(RULE_IDS).optional(),
    }),
    output: z.array(findingSchema),
    cli: { usage: 'turboslide lint <slideIds> --json' },
    mcp: 'deck_lint',
    example: { slideIds: 'all', layers: 'static' },
  }),
  'fix.run': action({
    id: 'fix.run',
    label: 'Fix',
    doc: 'Applies the fix mutations of findings that carry one and reports what remains.',
    group: 'lint',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      rule: z.enum(RULE_IDS).optional(),
      dryRun: z.boolean().optional(),
      baseRevision,
    }),
    output: z.strictObject({
      applied: z.array(findingSchema),
      remaining: z.array(findingSchema),
      revision,
    }),
    cli: { usage: 'turboslide fix <slideIds> --rule <rule> --dry-run' },
    mcp: 'deck_fix',
    example: { slideIds: ['content-rule'], dryRun: true, baseRevision: 412 },
  }),
  'diff.run': action({
    id: 'diff.run',
    label: 'Diff',
    doc: 'The mutation list between two revisions in prose, optionally with before and after crops.',
    group: 'version',
    mutates: false,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      from: z
        .number()
        .int()
        .nonnegative()
        .optional()
        .describe('The older revision; omitted with staged, the last named version'),
      to: z.number().int().nonnegative().optional().describe('Defaults to the current revision'),
      staged: z
        .boolean()
        .optional()
        .describe('Diff from the newest named version below the current revision'),
      render: z
        .boolean()
        .optional()
        .describe('Write before and after crops of every touched block'),
      themes: themes.optional().describe('Themes to render the crops in; defaults to light'),
      out: z.string().optional().describe('Crop directory; defaults to .turboslide/diff'),
    }),
    output: z.strictObject({
      from: revision,
      to: revision,
      mutations: z.array(mutationSchema),
      prose: z.array(z.string()),
      crops: z
        .array(
          z.strictObject({
            slideId: slugSchema,
            blockId: blockIdSchema.optional(),
            theme,
            before: z.string().describe("The crop's path; '' when the slide is absent before"),
            after: z.string().describe("The crop's path; '' when the slide is absent after"),
          }),
        )
        .optional(),
    }),
    cli: { usage: 'turboslide diff <from> <to> --staged --render --theme <themes> --out <out>' },
    mcp: 'deck_diff',
    example: { from: 400, to: 412 },
  }),
  'version.save': action({
    id: 'version.save',
    label: 'Save version',
    doc: 'Saves a named version at the current revision.',
    group: 'version',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ note: z.string().min(1) }),
    output: versionSchema,
    cli: { usage: 'turboslide version save -m <note>' },
    mcp: 'deck_version_save',
    example: { note: 'Before the copy pass' },
  }),
  'version.list': action({
    id: 'version.list',
    label: 'List versions',
    doc: 'The saved versions with author, note and revision.',
    group: 'version',
    mutates: false,
    transports: A,
    milestone: 'M2',
    input: empty,
    output: z.array(versionSchema),
    cli: { usage: 'turboslide version list' },
    mcp: 'deck_version_list',
    example: {},
  }),
  'version.restore': action({
    id: 'version.restore',
    label: 'Restore version',
    doc: 'Restores a version as a mutation, so it is undoable and visible in History.',
    group: 'version',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ n: z.number().int().positive(), baseRevision }),
    output: z.strictObject({ revision }),
    cli: { usage: 'turboslide version restore <n>' },
    mcp: 'deck_version_restore',
    example: { n: 3, baseRevision: 412 },
  }),
  'judge.bundle': action({
    id: 'judge.bundle',
    label: 'Judge bundle',
    doc: 'Packages renders, sheets with cell maps, render records and findings into a directory for a judge run.',
    group: 'lint',
    mutates: false,
    transports: ['cli', 'mcp'],
    milestone: 'M4',
    input: z.strictObject({ slideIds: slideIdsOrAll, out: z.string() }),
    output: z.strictObject({ dir: z.string(), files: z.array(z.string()), revision }),
    cli: { usage: 'turboslide judge bundle --out <out>' },
    mcp: 'deck_judge_bundle',
    example: { slideIds: 'all', out: '.turboslide/judge/' },
  }),
  'view.goto': action({
    id: 'view.goto',
    label: 'Go to slide',
    doc: 'Shows a slide in the viewer, the editor or the presenter.',
    group: 'view',
    mutates: false,
    transports: ['window', 'mcp'],
    milestone: 'M3',
    input: z.strictObject({ slideId: slugSchema }),
    output: viewStateSchema,
    mcp: 'deck_goto_slide',
    example: { slideId: 'content-rule' },
  }),
  'view.mode': action({
    id: 'view.mode',
    label: 'View mode',
    doc: 'Switches between slide, grid and book mode.',
    group: 'view',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ mode: z.enum(['slide', 'grid', 'book']) }),
    output: viewStateSchema,
    mcp: 'deck_set_view',
    example: { mode: 'grid' },
  }),
  'view.theme': action({
    id: 'view.theme',
    label: 'View theme',
    doc: 'Sets the theme of chrome and sheet together through the gt-theme key.',
    group: 'view',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ theme }),
    output: viewStateSchema,
    mcp: 'deck_set_view',
    example: { theme: 'dark' },
  }),
  'view.present': action({
    id: 'view.present',
    label: 'Present',
    doc: 'Enters or leaves present mode.',
    group: 'view',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ on: z.boolean() }),
    output: viewStateSchema,
    mcp: 'deck_set_view',
    example: { on: true },
  }),
  'view.zoom': action({
    id: 'view.zoom',
    label: 'Zoom',
    doc: 'Sets the stage scale in the editor, a factor of the sheet size or fit; a view action with no document field.',
    group: 'view',
    mutates: false,
    transports: ['window', 'mcp'],
    milestone: 'GS1',
    input: z.strictObject({
      zoom: z
        .union([z.number().positive().max(4), z.literal('fit')])
        .describe("A factor between 0.25 and 4, or 'fit' for the stage's own fit"),
    }),
    output: viewStateSchema,
    mcp: 'deck_set_zoom',
    example: { zoom: 'fit' },
  }),
  'export.run': action({
    id: 'export.run',
    label: 'Export',
    doc: 'Exports the deck to PPTX in flatten (perfect, pixel identical) or native (editable text) mode and returns the verified report.',
    group: 'export',
    mutates: false,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      format: z.enum(['pptx', 'pdf']),
      mode: z
        .enum(['native', 'flatten'])
        .optional()
        .describe(
          'Defaults to flatten, the perfect mode: a 2x page raster over an invisible text layer, every page measured within 0.1 percent (SPEC 8.2)',
        ),
      theme: themes
        .optional()
        .describe('One file per theme; defaults to both, which also writes <deckId>-both.zip'),
      fonts: z
        .enum(['exact', 'standard'])
        .optional()
        .describe('The export font set (SPEC 8.4); defaults to exact'),
      embedFonts: z
        .boolean()
        .optional()
        .describe(
          'Native mode only: embed the export faces as fntdata parts; off by default, and flatten never embeds (docs/pptx.md)',
        ),
      headings: z
        .literal('raster')
        .optional()
        .describe('Write every heading as a PNG instead of a text box (SPEC 8.3)'),
      rasterScale: z
        .union([z.literal('auto'), z.literal(2), z.literal(3)])
        .optional()
        .describe(
          'Device pixels per sheet pixel of the raster PNGs: auto (3x icons and marks, 2x the rest), 2 or 3 (SPEC 8.6)',
        ),
      pictureScale: z
        .literal([2, 3])
        .optional()
        .describe(
          'The scale two-tone pictures are regenerated at from the one-bit image (SPEC 8.2)',
        ),
      excludeShareAlike: z
        .boolean()
        .optional()
        .describe(
          'Replace share-alike pictures with the paper plate and its credit (SPEC 11, open question 12)',
        ),
      baseline: z
        .enum(['libreoffice', 'none'])
        .optional()
        .describe(
          'The renderer whose measured first-baseline constant offsets native text boxes (calibration.json); defaults to libreoffice, the verify renderer',
        ),
      verify: z
        .boolean()
        .optional()
        .describe(
          'Render the files back through LibreOffice and diff every page against the web render (SPEC 8.5)',
        ),
      slideIds: slideIdsOrAll.optional().describe("A subset to export; defaults to 'all'"),
      includeSkipped: z
        .boolean()
        .optional()
        .describe('Export the skipped slides too; left out by default (gslides-parity SPEC 7.2.1)'),
      includeNotes: z
        .boolean()
        .optional()
        .describe('Carry the speaker notes; left out by default (gslides-parity decision 15.2)'),
      out: z.string().optional().describe('Output directory; defaults to .turboslide/export'),
    }),
    output: exportReportSchema,
    cli: {
      usage:
        'turboslide export <format> --mode <mode> --theme <theme> --fonts <fonts> --embed-fonts --exclude-share-alike --baseline-target <baseline> --include-skipped --include-notes --verify --out <out>',
    },
    mcp: 'deck_export',
    example: { format: 'pptx', mode: 'flatten', theme: ['light'], fonts: 'exact', verify: true },
  }),
  'export.check': action({
    id: 'export.check',
    label: 'Check export file',
    doc: 'Reopens an exported PPTX with python-pptx, walks the package against its content types and relationships, and reports the pages, size, raster formats, fonts and any invalid part.',
    group: 'export',
    mutates: false,
    transports: ['cli'],
    milestone: 'M6',
    input: z.strictObject({
      file: z.string().describe('The .pptx to check'),
      python: z
        .string()
        .optional()
        .describe(
          'An interpreter with python-pptx; defaults to TURBOSLIDE_PYTHON, then .turboslide/venv/bin/python when it exists',
        ),
      quickLook: z
        .boolean()
        .optional()
        .describe(
          'Render the first page through macOS QuickLook when qlmanage exists; defaults to on',
        ),
      out: z
        .string()
        .optional()
        .describe('Where the QuickLook thumbnail lands; defaults to a folder beside the file'),
    }),
    output: exportCheckSchema,
    cli: { usage: 'turboslide export check <file> --python <python> --out <out>' },
    example: { file: '.turboslide/export/gt-brand-light.pptx' },
  }),
  'export.text': action({
    id: 'export.text',
    label: 'Download as plain text',
    doc: 'The deck as plain text: one block of paragraphs per slide in order, table cells joined by tabs, a blank line between slides, the notes after each slide when asked; skipped slides left out unless asked.',
    group: 'export',
    mutates: false,
    transports: A,
    milestone: 'GS1',
    input: z.strictObject({
      slideIds: slideIdsOrAll.optional().describe("A subset; defaults to 'all'"),
      includeNotes: z.boolean().optional().describe('Append each slide’s speaker notes'),
      includeSkipped: z.boolean().optional().describe('Include the skipped slides'),
    }),
    output: z.strictObject({
      text: z.string(),
      slides: z.number().int().nonnegative().describe('How many slides the text covers'),
      bytes: z.number().int().nonnegative(),
    }),
    cli: { usage: 'turboslide export txt <slideIds> --include-notes --include-skipped' },
    mcp: 'deck_export_text',
    example: { slideIds: 'all', includeNotes: true },
  }),
  'build.run': action({
    id: 'build.run',
    label: 'Build standalone',
    doc: 'Writes the single-file HTML deck with fonts and assets inlined and asserts the size budget.',
    group: 'export',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      out: z.string(),
      budgetMB: z.number().positive().optional().describe('Defaults to 16'),
      quality: z.number().int().min(1).max(100).optional(),
      includeSkipped: z
        .boolean()
        .optional()
        .describe('Build the skipped slides too; left out by default (gslides-parity SPEC 7.2.1)'),
      includeNotes: z.boolean().optional().describe('Carry the speaker notes into the file'),
    }),
    output: z.strictObject({
      path: z.string(),
      bytes: z.number().int().nonnegative(),
      assertions: z.array(
        z.strictObject({ name: z.string(), passed: z.boolean(), detail: z.string() }),
      ),
    }),
    cli: { usage: 'turboslide build --out <out> --budget <budgetMB>' },
    mcp: 'deck_build',
    example: { out: 'public/brand-deck.html', budgetMB: 16 },
  }),
  'fonts.build': action({
    id: 'fonts.build',
    label: 'Build export fonts',
    doc: 'Cuts the static export font set from InterVariable into packages/fonts/export with fonts.json (scripts/build-fonts.py); --check reports a stale committed set.',
    group: 'export',
    mutates: false,
    transports: ['cli'],
    milestone: 'M2',
    input: z.strictObject({
      check: z
        .boolean()
        .optional()
        .describe('Compare the committed set with a fresh build; exit 1 when it differs'),
      python: z
        .string()
        .optional()
        .describe(
          'The Python binary; defaults to .turboslide/venv/bin/python, created from scripts/requirements.txt when missing',
        ),
    }),
    output: z.strictObject({
      out: z.string(),
      version: z.string(),
      faces: z.array(
        z.strictObject({
          file: z.string(),
          family: z.string(),
          opsz: z.number(),
          weight: z.number(),
          bytes: z.number().int().nonnegative(),
        }),
      ),
      written: z.array(z.string()),
      stale: z.array(z.string()),
    }),
    cli: { usage: 'turboslide fonts build --check' },
    example: {},
  }),
  'import.run': action({
    id: 'import.run',
    label: 'Import deck',
    doc: 'Imports the Prototemplate deck HTML into a Turboslide deck and writes the import report.',
    group: 'deck',
    mutates: true,
    transports: ['cli'],
    milestone: 'M1',
    input: z.strictObject({ from: z.string(), into: slugSchema }),
    output: z.strictObject({
      slides: z.number().int().nonnegative(),
      sections: z.number().int().nonnegative(),
      htmlBlocks: z.number().int().nonnegative(),
      report: z.string().describe('Path of import-report.json'),
    }),
    cli: { usage: 'turboslide import <from> --into <into>' },
    example: { from: '/Users/kevinliu/repos/Prototemplate/deck', into: 'gt-brand' },
  }),
  'validate.run': action({
    id: 'validate.run',
    label: 'Validate',
    doc: 'Validates a deck directory and returns the issues and the normalized document.',
    group: 'deck',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      path: z.string().optional().describe('Deck directory; defaults to the current deck'),
    }),
    output: z.strictObject({
      ok: z.boolean(),
      issues: z.array(
        z.strictObject({
          code: z.string(),
          severity: z.literal([1, 2, 3]),
          file: z.string(),
          pointer: z.string(),
          message: z.string(),
        }),
      ),
      revision: revision.nullable(),
    }),
    cli: { usage: 'turboslide validate <path>' },
    mcp: 'deck_validate',
    example: { path: 'decks/gt-brand' },
  }),
  'source.read': action({
    id: 'source.read',
    label: 'Read source',
    doc: 'Glyphfield standard action: the exact current source document of the active owner.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: empty,
    output: z.string(),
    example: {},
  }),
  'source.apply': action({
    id: 'source.apply',
    label: 'Apply source',
    doc: 'Glyphfield standard action: applies a JSON string or object through the active owner’s validator.',
    group: 'studio',
    mutates: true,
    transports: ['window'],
    milestone: 'M3',
    input: z.union([z.string(), z.record(z.string(), z.unknown())]),
    output: z.null(),
    example: {
      schemaVersion: 1,
      id: 'thesis',
      kind: 'statement',
      big: 'Every product in every language',
    },
  }),
  'controls.list': action({
    id: 'controls.list',
    label: 'List controls',
    doc: 'Glyphfield standard action: the visible interactive controls with labels, data-control ids and values.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: empty,
    output: z.array(
      z.strictObject({
        kind: z.enum(['button', 'checkbox', 'input', 'select', 'textarea', 'textbox']),
        label: z.string(),
        control: z.string().optional().describe('The data-control id'),
        value: z.union([z.boolean(), z.string()]).optional(),
      }),
    ),
    example: {},
  }),
  'control.activate': action({
    id: 'control.activate',
    label: 'Activate control',
    doc: 'Glyphfield standard action: activates a control by accessible label or data-control id.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.string().describe('The accessible label or data-control id'),
    output: z.null(),
    example: 'list: Size',
  }),
  'control.set': action({
    id: 'control.set',
    label: 'Set control',
    doc: 'Glyphfield standard action: sets a form control by accessible label or data-control id.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({
      label: z.string(),
      value: z.union([z.boolean(), z.string(), z.number()]),
    }),
    output: z.null(),
    example: { label: 'list: Size', value: '22' },
  }),
  'artifact.download': action({
    id: 'artifact.download',
    label: 'Download artifact',
    doc: 'Glyphfield standard action: saves a returned artifact with its deterministic file name.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ fileName: z.string().min(1) }),
    output: z.null(),
    example: { fileName: 'gt-brand-light.pptx' },
  }),
};

/** Actions in table order. */
export function actionsInOrder(): ActionSpec[] {
  return ACTION_IDS.map((id) => ACTIONS[id]);
}

export function actionsOn(transport: Transport): ActionSpec[] {
  return actionsInOrder().filter((spec) => spec.transports.includes(transport));
}

export function isActionId(value: string): value is ActionId {
  return (ACTION_IDS as ReadonlyArray<string>).includes(value);
}
