// The action table (SPEC 7.1): one typed constant from which the CLI subcommands, the MCP tool
// list, the window API's describe().actions, the OpenAPI document, the palette entries and the
// skills' reference tables are generated by `pnpm generate:contracts`. Every entry is declared
// now, including the ones whose implementation lands later; the dispatcher answers
// not_implemented (HTTP 501) for those (MILESTONES M1 item 3). Every mutating action takes
// baseRevision and rejects a stale one with 409 and the current document.
import { z } from 'zod';
import {
  assetMetricsSchema,
  assetSchema,
  assetSourceSchema,
  assetTreatmentSchema,
  assetTwinsSchema,
  ASSET_ROLES,
} from './assets.ts';
import { blockSchema } from './blocks.ts';
import { materialCatalogEntrySchema, materialUniformsSchema } from './blocks/material.ts';
import { PLATE_SIDES, sectionSchema, slideSchema, SLIDE_KINDS, SLOT_NAMES } from './deck.ts';
import { exportReportSchema } from './export.ts';
import { findingSchema } from './findings.ts';
import { blockIdSchema, slugSchema } from './ids.ts';
import { leaseSchema, mutationSchema, versionSchema } from './mutations.ts';
import { renderRecordSchema } from './render.ts';
import { RULE_IDS } from './rules.ts';

export type Transport = 'cli' | 'mcp' | 'http' | 'window';
export const TRANSPORTS = ['cli', 'mcp', 'http', 'window'] as const;
export const ALL_TRANSPORTS: ReadonlyArray<Transport> = TRANSPORTS;

export type Milestone = 'M1' | 'M2' | 'M3' | 'M4' | 'M5' | 'M6';

/** The palette groups (SPEC 6.1) and the docs sections. */
export type ActionGroup =
  | 'deck'
  | 'slide'
  | 'block'
  | 'asset'
  | 'render'
  | 'lint'
  | 'version'
  | 'export'
  | 'view'
  | 'studio';

export type ActionCli = {
  /** The documented command; `<name>` tokens are positionals named after input keys. */
  usage: string;
  /** The input key read from stdin when the usage ends in `< file.json`. */
  stdin?: string;
};

export type ActionSpec = {
  id: ActionId;
  label: string;
  /** One sentence of documentation. */
  doc: string;
  group: ActionGroup;
  mutates: boolean;
  transports: ReadonlyArray<Transport>;
  milestone: Milestone;
  input: z.ZodType;
  output: z.ZodType;
  cli?: ActionCli;
  /** The MCP tool name, deck_<action>. */
  mcp?: string;
  /** An input that parses; the coverage test runs every example through `input`. */
  example: unknown;
};

export const ACTION_IDS = [
  'deck.info',
  'deck.create',
  'deck.rename',
  'slide.list',
  'slide.get',
  'slide.insert',
  'slide.remove',
  'slide.move',
  'slide.update',
  'slide.replace',
  'block.set',
  'block.insert',
  'block.remove',
  'block.move',
  'section.set',
  'slide.lease',
  'asset.add',
  'asset.dither',
  'asset.capture',
  'material.capture',
  'material.list',
  'render.slide',
  'render.sheet',
  'lint.run',
  'fix.run',
  'diff.run',
  'version.save',
  'version.list',
  'version.restore',
  'judge.bundle',
  'view.goto',
  'view.mode',
  'view.theme',
  'view.present',
  'export.run',
  'build.run',
  'fonts.build',
  'import.run',
  'validate.run',
  'source.read',
  'source.apply',
  'controls.list',
  'control.activate',
  'control.set',
  'artifact.download',
] as const;

export type ActionId = (typeof ACTION_IDS)[number];

// ---------------------------------------------------------------------------------------------
// Shared pieces

const baseRevision = z
  .number()
  .int()
  .nonnegative()
  .describe('The revision the caller read; a stale value is rejected with 409');
const revision = z.number().int().nonnegative();
const theme = z.enum(['light', 'dark']);
const themes = z.array(theme).min(1).describe('One or both themes');
const slideIdsOrAll = z
  .union([z.literal('all'), z.array(slugSchema).min(1)])
  .describe("Slide ids, or 'all'");
const slotSchema = z.enum([...SLOT_NAMES, 'plate']);

export const outlineSchema = z.array(
  z.strictObject({
    id: slugSchema,
    name: z.string(),
    slides: z.array(
      z.strictObject({
        id: slugSchema,
        n: z.number().int().positive(),
        title: z.string(),
        kind: z.enum(SLIDE_KINDS),
      }),
    ),
  }),
);

export const slideResultSchema = z.strictObject({
  slide: slideSchema,
  revision,
  findings: z.array(findingSchema),
});

const slideListRow = z.strictObject({
  id: slugSchema,
  n: z.number().int().positive(),
  section: slugSchema,
  title: z.string(),
  kind: z.enum(SLIDE_KINDS),
  lint: z.strictObject({ s3: z.number().int().nonnegative(), s2: z.number().int().nonnegative() }),
});

export const viewStateSchema = z.strictObject({
  slideId: slugSchema,
  n: z.number().int().positive(),
  mode: z.enum(['slide', 'grid', 'book']),
  theme,
  present: z.boolean(),
  edit: z.boolean().optional(),
});

const empty = z.strictObject({});

const plateSide = z
  .enum(PLATE_SIDES)
  .describe('The plate rectangle the metrics are screened against');

/**
 * The two-tone parameters a capture or an intake takes before the pipeline fills the fixed
 * fields (kind, autocontrast 0.5, cell 2, bayer 8, lanczos3) and the crop default of the whole
 * source; every field is optional so `--black 24` alone is a complete request (SPEC 5.4).
 */
export const twoToneParamsSchema = z.strictObject({
  crop: z
    .tuple([z.number(), z.number(), z.number(), z.number()])
    .optional()
    .describe('Left, top, right, bottom in source pixels; may reach past the source'),
  channel: z.enum(['gray', 'r', 'g', 'b']).optional(),
  invert: z.boolean().optional(),
  blur: z.number().nonnegative().optional(),
  black: z.number().min(0).max(255).optional(),
  white: z.number().min(0).max(255).optional(),
  gamma: z.number().positive().optional(),
  minFilter: z.number().positive().optional(),
  polarity: z.enum(['dark-ground', 'light-ground']).optional(),
});

/** One asset's dither report: the twins, the metrics and the verification counts. */
export const ditherResultSchema = z.strictObject({
  assetId: slugSchema,
  twins: assetTwinsSchema,
  metrics: assetMetricsSchema.optional(),
  /** Cells of a screen regenerated from the source that differ from the committed dark twin. */
  mismatchedCells: z.number().int().nonnegative().optional(),
  /** Cells where the committed light twin is not the inverse of the dark one. */
  twinInverseMismatch: z.number().int().nonnegative().optional(),
  /** The recorded treatment lacks a parameter the pipeline needs, so it could not be re-run. */
  missingParameter: z.boolean().optional(),
  /** No continuous source is on disk (sourceFile absent), so the cells were not re-run. */
  missingSource: z.boolean().optional(),
  /** The committed twin files are not on disk, so nothing was read back. */
  missingTwins: z.boolean().optional(),
  /** Files written under assets/, relative to the deck directory. */
  written: z.array(z.string()),
});

/**
 * What deck.create starts from: the GT brand template record under decks/templates/gt-brand
 * (the deck's manifest and slides with a template.json naming it), or one title slide.
 */
export const DECK_TEMPLATES = ['gt-brand', 'blank'] as const;
export type DeckTemplateId = (typeof DECK_TEMPLATES)[number];

const A = ALL_TRANSPORTS;
const noWindow: ReadonlyArray<Transport> = ['cli', 'mcp', 'http'];

function action(spec: ActionSpec): ActionSpec {
  return spec;
}

// ---------------------------------------------------------------------------------------------
// The table

export const ACTIONS: Readonly<Record<ActionId, ActionSpec>> = {
  'deck.info': action({
    id: 'deck.info',
    label: 'Deck info',
    doc: 'Title, theme, sections with slide ids and titles, counts and the current revision.',
    group: 'deck',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: empty,
    output: z.strictObject({
      id: slugSchema,
      title: z.string(),
      theme: z.string(),
      revision,
      sections: outlineSchema,
      counts: z.strictObject({
        slides: z.number().int(),
        sections: z.number().int(),
        assets: z.number().int(),
        htmlBlocks: z.number().int(),
      }),
    }),
    cli: { usage: 'turboslide info' },
    mcp: 'deck_get_info',
    example: {},
  }),
  'deck.create': action({
    id: 'deck.create',
    label: 'New deck',
    doc: 'Creates a deck under decks/ from the GT brand template or as one title slide, and returns its id, revision and counts.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'M4',
    input: z.strictObject({
      name: z.string().min(1).describe('The deck title; the id is its slug unless `id` is given'),
      from: z
        .enum(DECK_TEMPLATES)
        .describe(
          "'gt-brand' copies decks/templates/gt-brand (85 slides, 8 sections, the assets); 'blank' writes one title slide",
        ),
      id: slugSchema
        .optional()
        .describe('The deck id under decks/; derived from the name when absent'),
    }),
    output: z.strictObject({
      deckId: slugSchema,
      title: z.string(),
      from: z.enum(DECK_TEMPLATES),
      revision,
      dir: z.string().describe('The deck directory'),
      counts: z.strictObject({
        slides: z.number().int().nonnegative(),
        sections: z.number().int().nonnegative(),
        assets: z.number().int().nonnegative(),
      }),
    }),
    cli: { usage: 'turboslide deck create <name> --from <from> --id <id>' },
    mcp: 'deck_create',
    example: { name: 'Q4 review', from: 'gt-brand' },
  }),
  'deck.rename': action({
    id: 'deck.rename',
    label: 'Rename deck',
    doc: 'Sets the deck title, the name the sidebar head, the toolbar and the deck list show; one deck.set of /title.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'M4',
    input: z.strictObject({ name: z.string().min(1).describe('The new title'), baseRevision }),
    output: z.strictObject({ title: z.string(), revision }),
    cli: { usage: 'turboslide deck rename <name>' },
    mcp: 'deck_rename',
    example: { name: 'GT brand deck, Q4', baseRevision: 412 },
  }),
  'slide.list': action({
    id: 'slide.list',
    label: 'List slides',
    doc: 'Every slide in deck order with its number, section, title, kind and lint counts.',
    group: 'slide',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({ sectionId: slugSchema.optional() }),
    output: z.array(slideListRow),
    cli: { usage: 'turboslide slides' },
    mcp: 'deck_list_slides',
    example: {},
  }),
  'slide.get': action({
    id: 'slide.get',
    label: 'Get slide',
    doc: 'The normalized slide, the assets it references and its last render record.',
    group: 'slide',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({ slideId: slugSchema }),
    output: z.strictObject({
      slide: slideSchema,
      n: z.number().int().positive(),
      section: slugSchema,
      assets: z.record(slugSchema, assetSchema),
      render: renderRecordSchema.nullable(),
    }),
    cli: { usage: 'turboslide slide get <slideId>' },
    mcp: 'deck_get_slide',
    example: { slideId: 'content-rule' },
  }),
  'slide.insert': action({
    id: 'slide.insert',
    label: 'Insert slide',
    doc: 'Inserts a slide into a section after the named slide, or first.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      sectionId: slugSchema,
      after: slugSchema.optional(),
      slide: slideSchema,
      baseRevision,
    }),
    output: z.strictObject({ slide: slideSchema, revision, outline: outlineSchema }),
    cli: {
      usage: 'turboslide slide insert --section <sectionId> --after <after> < slide.json',
      stdin: 'slide',
    },
    mcp: 'deck_insert_slide',
    example: {
      sectionId: 'brand',
      after: 'thesis',
      baseRevision: 412,
      slide: { schemaVersion: 1, id: 'why', kind: 'statement', big: 'Why the redesign' },
    },
  }),
  'slide.remove': action({
    id: 'slide.remove',
    label: 'Remove slide',
    doc: 'Removes a slide from the deck and its section.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ slideId: slugSchema, baseRevision }),
    output: z.strictObject({ revision, outline: outlineSchema }),
    cli: { usage: 'turboslide slide remove <slideId>' },
    mcp: 'deck_remove_slide',
    example: { slideId: 'why', baseRevision: 413 },
  }),
  'slide.move': action({
    id: 'slide.move',
    label: 'Move slide',
    doc: 'Moves a slide to a section after the named slide, or first.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      sectionId: slugSchema,
      after: slugSchema.optional(),
      baseRevision,
    }),
    output: z.strictObject({ sections: z.array(sectionSchema), revision }),
    cli: { usage: 'turboslide slide move <slideId> --to <sectionId> --after <after>' },
    mcp: 'deck_move_slide',
    example: { slideId: 'content-rule', sectionId: 'website', baseRevision: 412 },
  }),
  'slide.update': action({
    id: 'slide.update',
    label: 'Patch slide',
    doc: 'Applies a mutation list to one slide and returns the normalized slide with its findings.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      baseRevision,
      mutations: z.array(mutationSchema).min(1),
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide slide patch <slideId> --set <pointer>=<value>' },
    mcp: 'deck_update_slide',
    example: {
      slideId: 'content-rule',
      baseRevision: 412,
      mutations: [
        { op: 'slide.set', slideId: 'content-rule', path: '/layout/ratio', value: '4/8' },
      ],
    },
  }),
  'slide.replace': action({
    id: 'slide.replace',
    label: 'Replace slide',
    doc: 'Replaces a slide with the given document; what the source drawer’s Apply emits.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ slideId: slugSchema, baseRevision, slide: slideSchema }),
    output: slideResultSchema,
    cli: { usage: 'turboslide slide put <slideId> < slide.json', stdin: 'slide' },
    mcp: 'deck_replace_slide',
    example: {
      slideId: 'thesis',
      baseRevision: 412,
      slide: {
        schemaVersion: 1,
        id: 'thesis',
        kind: 'statement',
        big: 'Every product in every language',
        measure: 22,
      },
    },
  }),
  'block.set': action({
    id: 'block.set',
    label: 'Set block property',
    doc: 'Writes one property of a block by JSON pointer; an absent value deletes it.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      blockId: blockIdSchema,
      path: z.string().describe('JSON pointer inside the block, such as /key'),
      value: z.unknown().optional().describe('The new value; omit it to delete the property'),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block set <slideId>#<blockId> <path> <value>' },
    mcp: 'deck_update_block',
    example: {
      slideId: 'content-rule',
      blockId: 'list',
      path: '/size',
      value: 22,
      baseRevision: 412,
    },
  }),
  'block.insert': action({
    id: 'block.insert',
    label: 'Insert block',
    doc: 'Inserts a block into a slot after the named block, or first.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      slot: slotSchema,
      after: blockIdSchema.optional(),
      block: blockSchema,
      baseRevision,
    }),
    output: slideResultSchema,
    cli: {
      usage: 'turboslide block insert <slideId> --slot <slot> --after <after> < block.json',
      stdin: 'block',
    },
    mcp: 'deck_insert_block',
    example: {
      slideId: 'content-rule',
      slot: 'left',
      after: 'p1',
      baseRevision: 412,
      block: { id: 'p2', type: 'paragraph', text: 'A second paragraph.' },
    },
  }),
  'block.remove': action({
    id: 'block.remove',
    label: 'Remove block',
    doc: 'Removes a block from its slide.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ slideId: slugSchema, blockId: blockIdSchema, baseRevision }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block remove <slideId>#<blockId>' },
    mcp: 'deck_remove_block',
    example: { slideId: 'content-rule', blockId: 'p1', baseRevision: 412 },
  }),
  'block.move': action({
    id: 'block.move',
    label: 'Move block',
    doc: 'Moves a block to a slot after the named block, or first.',
    group: 'block',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      blockId: blockIdSchema,
      slot: slotSchema,
      after: blockIdSchema.optional(),
      baseRevision,
    }),
    output: slideResultSchema,
    cli: { usage: 'turboslide block move <slideId>#<blockId> --slot <slot> --after <after>' },
    mcp: 'deck_move_block',
    example: {
      slideId: 'content-rule',
      blockId: 'list',
      slot: 'left',
      after: 'p1',
      baseRevision: 412,
    },
  }),
  'section.set': action({
    id: 'section.set',
    label: 'Set sections',
    doc: 'Replaces the section list, the only place slide order lives.',
    group: 'deck',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ sections: z.array(sectionSchema), baseRevision }),
    output: z.strictObject({ sections: z.array(sectionSchema), revision }),
    cli: { usage: 'turboslide sections set < sections.json', stdin: 'sections' },
    mcp: 'deck_set_sections',
    example: {
      baseRevision: 412,
      sections: [{ id: 'brand', name: 'Brand', slideIds: ['opener-brand', 'title'] }],
    },
  }),
  'slide.lease': action({
    id: 'slide.lease',
    label: 'Lease slide',
    doc: 'Takes a lease on a slide for the author; another author’s write is rejected with 409 unless forced.',
    group: 'slide',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideId: slugSchema,
      minutes: z.number().int().positive().max(120).optional().describe('Defaults to 10'),
      force: z.boolean().optional(),
      release: z.boolean().optional().describe('Give the author’s lease on the slide back'),
    }),
    output: leaseSchema,
    cli: { usage: 'turboslide lease <slideId> --minutes <minutes> --force --release' },
    mcp: 'deck_lease_slide',
    example: { slideId: 'content-rule', minutes: 10 },
  }),
  'asset.add': action({
    id: 'asset.add',
    label: 'Add asset',
    doc: 'Adds a file, a data URL or a fetched URL as an asset with its role, alt, license fields and optional two-tone treatment; returns the asset with twins and metrics.',
    group: 'asset',
    mutates: true,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({
      id: slugSchema.optional().describe('The asset id; a slug of the file name when omitted'),
      file: z
        .string()
        .optional()
        .describe('A path on the machine, or a data: URL from the studio’s drop or paste'),
      url: z.string().url().optional().describe('An http(s) URL to fetch, 25 MB at most'),
      role: z.enum(ASSET_ROLES),
      alt: z.string().min(1),
      source: assetSourceSchema
        .optional()
        .describe(
          'The provenance record; built from title, artist, license and sourceUrl when omitted',
        ),
      title: z.string().optional().describe('The picture’s name as the source states it'),
      artist: z.string().optional(),
      license: z
        .string()
        .optional()
        .describe('CC0, CC BY, CC BY-SA 4.0, public domain, or the text'),
      shareAlike: z
        .boolean()
        .optional()
        .describe('The license is share-alike: the credit must appear on the plate'),
      sourceUrl: z.string().url().optional().describe('Where the picture came from'),
      credit: z
        .string()
        .optional()
        .describe('The plate credit; composed from artist and license when omitted'),
      twoTone: z
        .boolean()
        .optional()
        .describe('Run the two-tone pipeline; the source is kept as assets/<id>.source.<ext>'),
      treatment: twoToneParamsSchema.optional(),
      plate: plateSide.optional(),
      baseRevision,
    }),
    output: assetSchema,
    cli: {
      usage:
        'turboslide asset add <file> --role <role> --alt <alt> --two-tone --black <black> --plate <plate>',
    },
    mcp: 'deck_asset_add',
    example: {
      file: 'photo.jpg',
      role: 'mood',
      alt: 'A photograph',
      artist: 'Hans Hillewaert',
      license: 'CC BY-SA 4.0',
      shareAlike: true,
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rosetta_Stone.JPG',
      twoTone: true,
      treatment: { black: 140, white: 230, gamma: 0.9 },
      plate: 'lower-right',
      baseRevision: 412,
    },
  }),
  'asset.dither': action({
    id: 'asset.dither',
    label: 'Dither asset',
    doc: 'Re-runs the two-tone pipeline on an asset with new parameters and reports plate clearance; with fromRecorded it reads the committed twins back and verifies them cell for cell.',
    group: 'asset',
    mutates: true,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({
      assetId: slugSchema.optional().describe('Required unless allTwoTone'),
      treatment: assetTreatmentSchema
        .optional()
        .describe(
          'The full treatment to run; the recorded one with the params merged when omitted',
        ),
      params: twoToneParamsSchema
        .optional()
        .describe('Parameters merged over the recorded treatment (--gamma, --black on the CLI)'),
      plate: plateSide.optional(),
      source: z.string().optional().describe('The continuous source when the asset records none'),
      allTwoTone: z.boolean().optional().describe('Every asset with a two-tone treatment'),
      fromRecorded: z
        .boolean()
        .optional()
        .describe('Read the committed twins back instead of regenerating; metrics are recomputed'),
      verifyCells: z
        .boolean()
        .optional()
        .describe('Regenerate from the source where one exists and count the cells that differ'),
      baseRevision,
    }),
    output: z.union([ditherResultSchema, z.array(ditherResultSchema)]),
    cli: {
      usage:
        'turboslide asset dither <assetId> --gamma <gamma> --plate <plate> --all-two-tone --from-recorded --verify-cells',
    },
    mcp: 'deck_asset_dither',
    example: {
      assetId: 'mood-earth',
      params: { gamma: 1.1 },
      plate: 'lower-right',
      baseRevision: 412,
    },
  }),
  'asset.capture': action({
    id: 'asset.capture',
    label: 'Capture page',
    doc: 'Captures a page at 1440 by 900 in one or both themes through a per-site recipe, optionally cropped to a region, with identical-region 2x detail crops as further assets.',
    group: 'asset',
    mutates: true,
    transports: noWindow,
    milestone: 'M5',
    input: z.strictObject({
      url: z.string().url(),
      id: slugSchema.optional().describe('The asset id; a slug of the URL when omitted'),
      alt: z.string().optional(),
      role: z.enum(['capture', 'detail']).optional(),
      viewport: z.tuple([z.number().int().positive(), z.number().int().positive()]).optional(),
      scale: z.literal([1, 2]).optional(),
      theme: z.enum(['light', 'dark', 'both']),
      region: z
        .tuple([z.number(), z.number(), z.number(), z.number()])
        .optional()
        .describe(
          'A CSS-pixel box x, y, w, h inside the page; both twins take the identical region',
        ),
      details: z
        .array(z.tuple([z.number(), z.number(), z.number(), z.number()]))
        .optional()
        .describe('Identical-region detail crops, one asset each as <id>-detail-<n>'),
      recipe: z.string().optional().describe('The per-site recipe; gt-site by default'),
      settleMs: z.number().int().nonnegative().optional(),
      format: z
        .enum(['jpg', 'png'])
        .optional()
        .describe('The twin file format; jpg at quality 92 by default'),
      allowHosts: z
        .array(z.string())
        .optional()
        .describe('Hosts beyond the built-in allowlist (SPEC 11 captureHosts)'),
      baseRevision,
    }),
    output: assetSchema,
    cli: {
      usage:
        'turboslide asset capture <url> --theme <theme> --scale <scale> --recipe <recipe> --region <region>',
    },
    mcp: 'deck_asset_capture',
    example: {
      url: 'https://generaltranslation.com/',
      theme: 'both',
      scale: 2,
      recipe: 'gt-site',
      baseRevision: 412,
    },
  }),
  'material.capture': action({
    id: 'material.capture',
    label: 'Capture material',
    doc: 'Renders a shader material at 3200 by 1800 and captures frozen frames at the given anchors as assets with recipe keys, through the two-tone screen when asked; one anchor returns the asset, several the list.',
    group: 'asset',
    mutates: true,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({
      materialId: z.string().min(1),
      preset: z
        .string()
        .optional()
        .describe('A palette preset of the material, under the uniforms'),
      uniforms: materialUniformsSchema.optional(),
      size: z.tuple([z.number().int().positive(), z.number().int().positive()]).optional(),
      anchors: z.array(z.number().nonnegative()).min(1).describe('Frame times in ms'),
      id: slugSchema.optional().describe('The asset id; <id>-<anchor> per anchor when several'),
      role: z.enum(['opener', 'mood', 'frame']).optional(),
      alt: z.string().optional(),
      twoTone: z.boolean().optional(),
      treatment: twoToneParamsSchema.optional(),
      plate: plateSide.optional(),
      backend: z.enum(['angle-metal', 'swiftshader']).optional(),
      baseRevision,
    }),
    output: z.union([assetSchema, z.array(assetSchema)]),
    cli: {
      usage:
        'turboslide material capture <materialId> --preset <preset> --uniforms <uniforms> --anchor <anchors> --two-tone --plate <plate>',
    },
    mcp: 'deck_material_capture',
    example: {
      materialId: 'paper:liquid-metal',
      preset: 'diamond',
      anchors: [5500],
      twoTone: true,
      treatment: { crop: [-1325, 105, 2709, 2374], black: 20 },
      plate: 'lower-left',
      baseRevision: 412,
    },
  }),
  'material.list': action({
    id: 'material.list',
    label: 'List materials',
    doc: 'The material catalog: every paper:* entry with its uniform schema and palette presets, and the proto:* engines with their availability.',
    group: 'asset',
    mutates: false,
    transports: A,
    milestone: 'M5',
    input: z.strictObject({ materialId: z.string().optional() }),
    output: z.array(materialCatalogEntrySchema),
    cli: { usage: 'turboslide material list' },
    mcp: 'deck_material_list',
    example: {},
  }),
  'render.slide': action({
    id: 'render.slide',
    label: 'Render',
    doc: 'Renders slides in one or both themes at 1x or 2x and returns render records with image paths.',
    group: 'render',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      themes: themes.optional(),
      scale: z.literal([1, 2]).optional(),
      format: z.enum(['png', 'jpg']).optional(),
      out: z.string().optional().describe('Output directory; defaults to .turboslide/render'),
    }),
    output: z.strictObject({ records: z.array(renderRecordSchema), images: z.array(z.string()) }),
    cli: { usage: 'turboslide render <slideIds> --theme <themes> --out <out> --json' },
    mcp: 'deck_render',
    example: { slideIds: ['content-rule'], themes: ['light', 'dark'], scale: 1 },
  }),
  'render.sheet': action({
    id: 'render.sheet',
    label: 'Contact sheet',
    doc: 'Renders a contact sheet per theme with a JSON cell map from cell boxes to slide ids.',
    group: 'render',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      themes: themes.optional(),
      cols: z.number().int().positive().optional(),
      thumb: z.number().int().positive().optional().describe('Thumbnail width in px'),
      numbered: z.boolean().optional(),
      overlay: z.enum(['lint', 'plate']).optional(),
      out: z.string().optional(),
    }),
    output: z.strictObject({
      sheets: z.array(
        z.strictObject({
          theme,
          image: z.string(),
          cells: z.array(
            z.strictObject({
              slideId: slugSchema,
              n: z.number().int().positive(),
              box: z.tuple([z.number(), z.number(), z.number(), z.number()]),
            }),
          ),
        }),
      ),
    }),
    cli: { usage: 'turboslide sheet <slideIds> --cols <cols> --thumb <thumb> --overlay <overlay>' },
    mcp: 'deck_sheet',
    example: { slideIds: 'all', cols: 4, thumb: 480, numbered: true },
  }),
  'lint.run': action({
    id: 'lint.run',
    label: 'Lint',
    doc: 'Runs the grammar linter on slides in the static, rendered or both layers and returns findings.',
    group: 'lint',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      layers: z.enum(['static', 'rendered', 'both']).optional(),
      rule: z.enum(RULE_IDS).optional(),
    }),
    output: z.array(findingSchema),
    cli: { usage: 'turboslide lint <slideIds> --json' },
    mcp: 'deck_lint',
    example: { slideIds: 'all', layers: 'static' },
  }),
  'fix.run': action({
    id: 'fix.run',
    label: 'Fix',
    doc: 'Applies the fix mutations of findings that carry one and reports what remains.',
    group: 'lint',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      slideIds: slideIdsOrAll,
      rule: z.enum(RULE_IDS).optional(),
      dryRun: z.boolean().optional(),
      baseRevision,
    }),
    output: z.strictObject({
      applied: z.array(findingSchema),
      remaining: z.array(findingSchema),
      revision,
    }),
    cli: { usage: 'turboslide fix <slideIds> --rule <rule> --dry-run' },
    mcp: 'deck_fix',
    example: { slideIds: ['content-rule'], dryRun: true, baseRevision: 412 },
  }),
  'diff.run': action({
    id: 'diff.run',
    label: 'Diff',
    doc: 'The mutation list between two revisions in prose, optionally with before and after crops.',
    group: 'version',
    mutates: false,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      from: z
        .number()
        .int()
        .nonnegative()
        .optional()
        .describe('The older revision; omitted with staged, the last named version'),
      to: z.number().int().nonnegative().optional().describe('Defaults to the current revision'),
      staged: z
        .boolean()
        .optional()
        .describe('Diff from the newest named version below the current revision'),
      render: z
        .boolean()
        .optional()
        .describe('Write before and after crops of every touched block'),
      themes: themes.optional().describe('Themes to render the crops in; defaults to light'),
      out: z.string().optional().describe('Crop directory; defaults to .turboslide/diff'),
    }),
    output: z.strictObject({
      from: revision,
      to: revision,
      mutations: z.array(mutationSchema),
      prose: z.array(z.string()),
      crops: z
        .array(
          z.strictObject({
            slideId: slugSchema,
            blockId: blockIdSchema.optional(),
            theme,
            before: z.string().describe("The crop's path; '' when the slide is absent before"),
            after: z.string().describe("The crop's path; '' when the slide is absent after"),
          }),
        )
        .optional(),
    }),
    cli: { usage: 'turboslide diff <from> <to> --staged --render --theme <themes> --out <out>' },
    mcp: 'deck_diff',
    example: { from: 400, to: 412 },
  }),
  'version.save': action({
    id: 'version.save',
    label: 'Save version',
    doc: 'Saves a named version at the current revision.',
    group: 'version',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ note: z.string().min(1) }),
    output: versionSchema,
    cli: { usage: 'turboslide version save -m <note>' },
    mcp: 'deck_version_save',
    example: { note: 'Before the copy pass' },
  }),
  'version.list': action({
    id: 'version.list',
    label: 'List versions',
    doc: 'The saved versions with author, note and revision.',
    group: 'version',
    mutates: false,
    transports: A,
    milestone: 'M2',
    input: empty,
    output: z.array(versionSchema),
    cli: { usage: 'turboslide version list' },
    mcp: 'deck_version_list',
    example: {},
  }),
  'version.restore': action({
    id: 'version.restore',
    label: 'Restore version',
    doc: 'Restores a version as a mutation, so it is undoable and visible in History.',
    group: 'version',
    mutates: true,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({ n: z.number().int().positive(), baseRevision }),
    output: z.strictObject({ revision }),
    cli: { usage: 'turboslide version restore <n>' },
    mcp: 'deck_version_restore',
    example: { n: 3, baseRevision: 412 },
  }),
  'judge.bundle': action({
    id: 'judge.bundle',
    label: 'Judge bundle',
    doc: 'Packages renders, sheets with cell maps, render records and findings into a directory for a judge run.',
    group: 'lint',
    mutates: false,
    transports: ['cli', 'mcp'],
    milestone: 'M4',
    input: z.strictObject({ slideIds: slideIdsOrAll, out: z.string() }),
    output: z.strictObject({ dir: z.string(), files: z.array(z.string()), revision }),
    cli: { usage: 'turboslide judge bundle --out <out>' },
    mcp: 'deck_judge_bundle',
    example: { slideIds: 'all', out: '.turboslide/judge/' },
  }),
  'view.goto': action({
    id: 'view.goto',
    label: 'Go to slide',
    doc: 'Shows a slide in the viewer, the editor or the presenter.',
    group: 'view',
    mutates: false,
    transports: ['window', 'mcp'],
    milestone: 'M3',
    input: z.strictObject({ slideId: slugSchema }),
    output: viewStateSchema,
    mcp: 'deck_goto_slide',
    example: { slideId: 'content-rule' },
  }),
  'view.mode': action({
    id: 'view.mode',
    label: 'View mode',
    doc: 'Switches between slide, grid and book mode.',
    group: 'view',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ mode: z.enum(['slide', 'grid', 'book']) }),
    output: viewStateSchema,
    mcp: 'deck_set_view',
    example: { mode: 'grid' },
  }),
  'view.theme': action({
    id: 'view.theme',
    label: 'View theme',
    doc: 'Sets the theme of chrome and sheet together through the gt-theme key.',
    group: 'view',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ theme }),
    output: viewStateSchema,
    mcp: 'deck_set_view',
    example: { theme: 'dark' },
  }),
  'view.present': action({
    id: 'view.present',
    label: 'Present',
    doc: 'Enters or leaves present mode.',
    group: 'view',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ on: z.boolean() }),
    output: viewStateSchema,
    mcp: 'deck_set_view',
    example: { on: true },
  }),
  'export.run': action({
    id: 'export.run',
    label: 'Export',
    doc: 'Exports the deck to PPTX, Google Slides or PDF in native or flatten mode and returns the verified report.',
    group: 'export',
    mutates: false,
    transports: A,
    milestone: 'M2',
    input: z.strictObject({
      format: z.enum(['pptx', 'gslides', 'pdf']),
      mode: z
        .enum(['native', 'flatten'])
        .optional()
        .describe('Defaults to flatten, the verified pixel-identical mode (SPEC 8.2)'),
      theme: themes.optional().describe('One file per theme; defaults to both'),
      fonts: z
        .enum(['exact', 'standard'])
        .optional()
        .describe('The export font set (SPEC 8.4); defaults to exact'),
      headings: z
        .literal('raster')
        .optional()
        .describe('Write every heading as a PNG instead of a text box (SPEC 8.3)'),
      rasterScale: z
        .union([z.literal('auto'), z.literal(2), z.literal(3)])
        .optional()
        .describe(
          'Device pixels per sheet pixel of the raster PNGs: auto (3x icons and marks, 2x the rest), 2 or 3 (SPEC 8.6)',
        ),
      pictureScale: z
        .literal([2, 3])
        .optional()
        .describe(
          'The scale two-tone pictures are regenerated at from the one-bit image (SPEC 8.2)',
        ),
      excludeShareAlike: z
        .boolean()
        .optional()
        .describe(
          'Replace share-alike pictures with the paper plate and its credit (SPEC 11, open question 12)',
        ),
      baseline: z
        .enum(['libreoffice', 'none'])
        .optional()
        .describe(
          'The renderer whose measured first-baseline constant offsets native text boxes (calibration.json); defaults to libreoffice, the verify renderer',
        ),
      verify: z.boolean().optional(),
      dryRun: z
        .boolean()
        .optional()
        .describe(
          'Google Slides: build and validate the batchUpdate requests without credentials and write requests.json; no presentation is created (SPEC 8.3)',
        ),
      slideIds: slideIdsOrAll.optional().describe("A subset to export; defaults to 'all'"),
      out: z.string().optional().describe('Output directory; defaults to .turboslide/export'),
    }),
    output: exportReportSchema,
    cli: {
      usage:
        'turboslide export <format> --mode <mode> --theme <theme> --fonts <fonts> --exclude-share-alike --baseline-target <baseline> --verify --dry-run --out <out>',
    },
    mcp: 'deck_export',
    example: { format: 'pptx', mode: 'flatten', theme: ['light'], fonts: 'exact', verify: true },
  }),
  'build.run': action({
    id: 'build.run',
    label: 'Build standalone',
    doc: 'Writes the single-file HTML deck with fonts and assets inlined and asserts the size budget.',
    group: 'export',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      out: z.string(),
      budgetMB: z.number().positive().optional().describe('Defaults to 16'),
      quality: z.number().int().min(1).max(100).optional(),
    }),
    output: z.strictObject({
      path: z.string(),
      bytes: z.number().int().nonnegative(),
      assertions: z.array(
        z.strictObject({ name: z.string(), passed: z.boolean(), detail: z.string() }),
      ),
    }),
    cli: { usage: 'turboslide build --out <out> --budget <budgetMB>' },
    mcp: 'deck_build',
    example: { out: 'public/brand-deck.html', budgetMB: 16 },
  }),
  'fonts.build': action({
    id: 'fonts.build',
    label: 'Build export fonts',
    doc: 'Cuts the static export font set from InterVariable into packages/fonts/export with fonts.json (scripts/build-fonts.py); --check reports a stale committed set.',
    group: 'export',
    mutates: false,
    transports: ['cli'],
    milestone: 'M2',
    input: z.strictObject({
      check: z
        .boolean()
        .optional()
        .describe('Compare the committed set with a fresh build; exit 1 when it differs'),
      python: z
        .string()
        .optional()
        .describe(
          'The Python binary; defaults to .turboslide/venv/bin/python, created from scripts/requirements.txt when missing',
        ),
    }),
    output: z.strictObject({
      out: z.string(),
      version: z.string(),
      faces: z.array(
        z.strictObject({
          file: z.string(),
          family: z.string(),
          opsz: z.number(),
          weight: z.number(),
          bytes: z.number().int().nonnegative(),
        }),
      ),
      written: z.array(z.string()),
      stale: z.array(z.string()),
    }),
    cli: { usage: 'turboslide fonts build --check' },
    example: {},
  }),
  'import.run': action({
    id: 'import.run',
    label: 'Import deck',
    doc: 'Imports the Prototemplate deck HTML into a Turboslide deck and writes the import report.',
    group: 'deck',
    mutates: true,
    transports: ['cli'],
    milestone: 'M1',
    input: z.strictObject({ from: z.string(), into: slugSchema }),
    output: z.strictObject({
      slides: z.number().int().nonnegative(),
      sections: z.number().int().nonnegative(),
      htmlBlocks: z.number().int().nonnegative(),
      report: z.string().describe('Path of import-report.json'),
    }),
    cli: { usage: 'turboslide import <from> --into <into>' },
    example: { from: '/Users/kevinliu/repos/Prototemplate/deck', into: 'gt-brand' },
  }),
  'validate.run': action({
    id: 'validate.run',
    label: 'Validate',
    doc: 'Validates a deck directory and returns the issues and the normalized document.',
    group: 'deck',
    mutates: false,
    transports: A,
    milestone: 'M1',
    input: z.strictObject({
      path: z.string().optional().describe('Deck directory; defaults to the current deck'),
    }),
    output: z.strictObject({
      ok: z.boolean(),
      issues: z.array(
        z.strictObject({
          code: z.string(),
          severity: z.literal([1, 2, 3]),
          file: z.string(),
          pointer: z.string(),
          message: z.string(),
        }),
      ),
      revision: revision.nullable(),
    }),
    cli: { usage: 'turboslide validate <path>' },
    mcp: 'deck_validate',
    example: { path: 'decks/gt-brand' },
  }),
  'source.read': action({
    id: 'source.read',
    label: 'Read source',
    doc: 'Glyphfield standard action: the exact current source document of the active owner.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: empty,
    output: z.string(),
    example: {},
  }),
  'source.apply': action({
    id: 'source.apply',
    label: 'Apply source',
    doc: 'Glyphfield standard action: applies a JSON string or object through the active owner’s validator.',
    group: 'studio',
    mutates: true,
    transports: ['window'],
    milestone: 'M3',
    input: z.union([z.string(), z.record(z.string(), z.unknown())]),
    output: z.null(),
    example: {
      schemaVersion: 1,
      id: 'thesis',
      kind: 'statement',
      big: 'Every product in every language',
    },
  }),
  'controls.list': action({
    id: 'controls.list',
    label: 'List controls',
    doc: 'Glyphfield standard action: the visible interactive controls with labels, data-control ids and values.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: empty,
    output: z.array(
      z.strictObject({
        kind: z.enum(['button', 'checkbox', 'input', 'select', 'textarea', 'textbox']),
        label: z.string(),
        control: z.string().optional().describe('The data-control id'),
        value: z.union([z.boolean(), z.string()]).optional(),
      }),
    ),
    example: {},
  }),
  'control.activate': action({
    id: 'control.activate',
    label: 'Activate control',
    doc: 'Glyphfield standard action: activates a control by accessible label or data-control id.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.string().describe('The accessible label or data-control id'),
    output: z.null(),
    example: 'list: Size',
  }),
  'control.set': action({
    id: 'control.set',
    label: 'Set control',
    doc: 'Glyphfield standard action: sets a form control by accessible label or data-control id.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({
      label: z.string(),
      value: z.union([z.boolean(), z.string(), z.number()]),
    }),
    output: z.null(),
    example: { label: 'list: Size', value: '22' },
  }),
  'artifact.download': action({
    id: 'artifact.download',
    label: 'Download artifact',
    doc: 'Glyphfield standard action: saves a returned artifact with its deterministic file name.',
    group: 'studio',
    mutates: false,
    transports: ['window'],
    milestone: 'M3',
    input: z.strictObject({ fileName: z.string().min(1) }),
    output: z.null(),
    example: { fileName: 'gt-brand-light.pptx' },
  }),
};

/** Actions in table order. */
export function actionsInOrder(): ActionSpec[] {
  return ACTION_IDS.map((id) => ACTIONS[id]);
}

export function actionsOn(transport: Transport): ActionSpec[] {
  return actionsInOrder().filter((spec) => spec.transports.includes(transport));
}

export function isActionId(value: string): value is ActionId {
  return (ACTION_IDS as ReadonlyArray<string>).includes(value);
}
