// Turboslide's own autocorrect lists (gslides-parity SPEC-5 7.1, 0.34; R10 1.3, 1.5, 1.6): the
// sentence exception list (abbreviations after which the next word stays lowercase), the
// correction list (common English misspellings), the quote table per language and the list
// prefixes the list rule recognises. Every row is written here under the repository's licence
// (R10 1.6: LibreOffice's `acor_en-US` lists are MPL-2.0 files whose file level obligations would
// follow any copy, and most of their rows are noise for a slide editor). The engine
// (`autocorrect.ts`) reads these tables and nothing else; the twelve default substitutions live
// with the preferences record (`preferences.ts` DEFAULT_SUBSTITUTIONS). The data is committed,
// no network, and the module imports nothing so a test can pin every row.

/**
 * The abbreviations after which the next word is not the start of a sentence (R10 1.3 "Sentence
 * capital", the categories of LibreOffice's SentenceExceptList: single letters with a period,
 * months, weekdays, "e.g.", "i.e.", "etc.", "vs.", "approx.", the titles and "No."). Compared
 * case insensitively against the token before the period; the period itself is part of the row.
 */
export const SENTENCE_EXCEPTIONS: ReadonlyArray<string> = [
  ...'abcdefghijklmnopqrstuvwxyz'.split('').map((letter) => `${letter}.`),
  'jan.',
  'feb.',
  'mar.',
  'apr.',
  'jun.',
  'jul.',
  'aug.',
  'sep.',
  'sept.',
  'oct.',
  'nov.',
  'dec.',
  'mon.',
  'tue.',
  'tues.',
  'wed.',
  'thu.',
  'thur.',
  'thurs.',
  'fri.',
  'sat.',
  'sun.',
  'e.g.',
  'i.e.',
  'etc.',
  'vs.',
  'approx.',
  'mr.',
  'mrs.',
  'ms.',
  'dr.',
  'prof.',
  'sr.',
  'jr.',
  'st.',
  'no.',
  'vol.',
  'fig.',
  'ch.',
  'p.',
  'pp.',
  'ed.',
  'est.',
  'dept.',
  'inc.',
  'ltd.',
  'co.',
  'corp.',
  'min.',
  'max.',
  'avg.',
  'misc.',
  'cf.',
  'ca.',
  'al.',
  'esp.',
  'incl.',
  'excl.',
  'tel.',
  'ext.',
];

/**
 * The correction list of "Automatically correct spelling" (R10 1.3, 12 item 7): about two
 * hundred common English misspellings, each keyed by the lowercase misspelt token with its
 * correction. The engine keeps the token's capitalisation pattern (a capital first letter, all
 * capitals). English only this round; a language the list does not cover skips the rule.
 */
export const CORRECTIONS: Readonly<Record<string, string>> = {
  teh: 'the',
  hte: 'the',
  adn: 'and',
  nad: 'and',
  taht: 'that',
  thta: 'that',
  whcih: 'which',
  wich: 'which',
  wiht: 'with',
  witht: 'with',
  thier: 'their',
  theri: 'their',
  recieve: 'receive',
  recieved: 'received',
  reciept: 'receipt',
  seperate: 'separate',
  seperated: 'separated',
  seperately: 'separately',
  definately: 'definitely',
  definitly: 'definitely',
  occured: 'occurred',
  occurence: 'occurrence',
  occurance: 'occurrence',
  untill: 'until',
  becuase: 'because',
  becasue: 'because',
  beacuse: 'because',
  begining: 'beginning',
  beleive: 'believe',
  belive: 'believe',
  acheive: 'achieve',
  acheived: 'achieved',
  accomodate: 'accommodate',
  accomodation: 'accommodation',
  accross: 'across',
  agressive: 'aggressive',
  apparant: 'apparent',
  apparantly: 'apparently',
  arguement: 'argument',
  basicly: 'basically',
  buisness: 'business',
  bussiness: 'business',
  calender: 'calendar',
  catagory: 'category',
  cemetary: 'cemetery',
  changable: 'changeable',
  cheif: 'chief',
  collegue: 'colleague',
  comming: 'coming',
  commited: 'committed',
  commitee: 'committee',
  comittee: 'committee',
  completly: 'completely',
  concious: 'conscious',
  consistant: 'consistent',
  controll: 'control',
  convienient: 'convenient',
  copywrite: 'copyright',
  critisism: 'criticism',
  curiousity: 'curiosity',
  decieve: 'deceive',
  desparate: 'desperate',
  developement: 'development',
  diffrent: 'different',
  dilemna: 'dilemma',
  dissapoint: 'disappoint',
  dissapear: 'disappear',
  dosent: "doesn't",
  doesnt: "doesn't",
  dont: "don't",
  didnt: "didn't",
  cant: "can't",
  wont: "won't",
  isnt: "isn't",
  wasnt: "wasn't",
  werent: "weren't",
  havent: "haven't",
  hasnt: "hasn't",
  couldnt: "couldn't",
  wouldnt: "wouldn't",
  shouldnt: "shouldn't",
  thats: "that's",
  whats: "what's",
  theres: "there's",
  youre: "you're",
  theyre: "they're",
  im: "I'm",
  ive: "I've",
  embarass: 'embarrass',
  embarassing: 'embarrassing',
  enviroment: 'environment',
  equiptment: 'equipment',
  excellant: 'excellent',
  exercize: 'exercise',
  existance: 'existence',
  experiance: 'experience',
  familar: 'familiar',
  finaly: 'finally',
  foriegn: 'foreign',
  fourty: 'forty',
  freind: 'friend',
  freinds: 'friends',
  fufill: 'fulfil',
  gaurd: 'guard',
  goverment: 'government',
  grammer: 'grammar',
  gratefull: 'grateful',
  garantee: 'guarantee',
  guarentee: 'guarantee',
  happend: 'happened',
  harrass: 'harass',
  hieght: 'height',
  heigth: 'height',
  humerous: 'humorous',
  immediatly: 'immediately',
  independant: 'independent',
  indispensible: 'indispensable',
  inteligent: 'intelligent',
  interupt: 'interrupt',
  irrelevent: 'irrelevant',
  jewelery: 'jewellery',
  judgement: 'judgment',
  knowlege: 'knowledge',
  labratory: 'laboratory',
  lenght: 'length',
  liason: 'liaison',
  libary: 'library',
  lisence: 'licence',
  liscense: 'license',
  maintainance: 'maintenance',
  maintenence: 'maintenance',
  managment: 'management',
  marketting: 'marketing',
  medeval: 'medieval',
  millenium: 'millennium',
  miniture: 'miniature',
  mischevious: 'mischievous',
  mispell: 'misspell',
  misspel: 'misspell',
  neccessary: 'necessary',
  necessery: 'necessary',
  neice: 'niece',
  nieghbor: 'neighbor',
  noticable: 'noticeable',
  occassion: 'occasion',
  occasionaly: 'occasionally',
  offical: 'official',
  ommision: 'omission',
  oppurtunity: 'opportunity',
  opertunity: 'opportunity',
  orignal: 'original',
  paralel: 'parallel',
  parliment: 'parliament',
  particulary: 'particularly',
  peice: 'piece',
  percieve: 'perceive',
  perfomance: 'performance',
  performace: 'performance',
  permanant: 'permanent',
  persistant: 'persistent',
  personel: 'personnel',
  persue: 'pursue',
  posession: 'possession',
  possesion: 'possession',
  potatos: 'potatoes',
  preceed: 'precede',
  prefered: 'preferred',
  presense: 'presence',
  privelege: 'privilege',
  priviledge: 'privilege',
  probaly: 'probably',
  probablly: 'probably',
  proffesional: 'professional',
  profesional: 'professional',
  pronounciation: 'pronunciation',
  publically: 'publicly',
  quater: 'quarter',
  questionaire: 'questionnaire',
  realy: 'really',
  reccomend: 'recommend',
  recomend: 'recommend',
  refered: 'referred',
  refering: 'referring',
  relevent: 'relevant',
  religous: 'religious',
  remeber: 'remember',
  repitition: 'repetition',
  resistence: 'resistance',
  responsability: 'responsibility',
  responsibilty: 'responsibility',
  restaraunt: 'restaurant',
  rythm: 'rhythm',
  rhythem: 'rhythm',
  sargent: 'sergeant',
  scedule: 'schedule',
  sceptical: 'skeptical',
  secratary: 'secretary',
  sieze: 'seize',
  similiar: 'similar',
  sincerly: 'sincerely',
  speach: 'speech',
  succesful: 'successful',
  sucessful: 'successful',
  succesfully: 'successfully',
  suprise: 'surprise',
  supercede: 'supersede',
  supress: 'suppress',
  tendancy: 'tendency',
  therefor: 'therefore',
  threshhold: 'threshold',
  tommorow: 'tomorrow',
  tommorrow: 'tomorrow',
  tounge: 'tongue',
  truely: 'truly',
  unforseen: 'unforeseen',
  unfortunatly: 'unfortunately',
  unneccessary: 'unnecessary',
  usefull: 'useful',
  vaccuum: 'vacuum',
  vegtable: 'vegetable',
  vehical: 'vehicle',
  visable: 'visible',
  wether: 'whether',
  wierd: 'weird',
  writting: 'writing',
  yeild: 'yield',
  alot: 'a lot',
  allways: 'always',
  amature: 'amateur',
  anual: 'annual',
  arround: 'around',
  attendence: 'attendance',
  audiance: 'audience',
  availble: 'available',
  availible: 'available',
  awsome: 'awesome',
  benifit: 'benefit',
  benifits: 'benefits',
  breif: 'brief',
  brodcast: 'broadcast',
  cheifly: 'chiefly',
  cliant: 'client',
  clents: 'clients',
  comunication: 'communication',
  compair: 'compare',
  competance: 'competence',
  competetive: 'competitive',
  conferance: 'conference',
  custommer: 'customer',
  custmer: 'customer',
  decison: 'decision',
  delievery: 'delivery',
  deliverd: 'delivered',
  disucss: 'discuss',
  effeciency: 'efficiency',
  efficent: 'efficient',
  eventhough: 'even though',
  feasable: 'feasible',
  finacial: 'financial',
  forcast: 'forecast',
  implimentation: 'implementation',
  implimented: 'implemented',
  infomation: 'information',
  informaton: 'information',
  intergration: 'integration',
  intrest: 'interest',
  invester: 'investor',
  lauch: 'launch',
  liablity: 'liability',
  merchandice: 'merchandise',
  negociate: 'negotiate',
  ocassion: 'occasion',
  ocurred: 'occurred',
  peformance: 'performance',
  prefrence: 'preference',
  presentaton: 'presentation',
  presentaion: 'presentation',
  prioritise: 'prioritize',
  proceedure: 'procedure',
  proccess: 'process',
  procces: 'process',
  proffit: 'profit',
  reveune: 'revenue',
  revenu: 'revenue',
  sattelite: 'satellite',
  shedule: 'schedule',
  strenght: 'strength',
  sucess: 'success',
  sumary: 'summary',
  suport: 'support',
  templete: 'template',
  transfered: 'transferred',
  wellcome: 'welcome',
};

/** The quote characters of a language (R10 1.5; the table is Turboslide's and listed as unverified). */
export type QuoteStyle = {
  /** the double quotes: opening, closing */
  double: [string, string];
  /** the single quotes: opening, closing */
  single: [string, string];
  /** a space written inside a guillemet (French: the narrow no break space) */
  inner?: string;
};

const CURLY: QuoteStyle = { double: ['“', '”'], single: ['‘', '’'] };

/**
 * The quote table per primary language subtag (R10 1.5): English, Portuguese and Dutch take the
 * curly pair; German the low nine opening pair; French the guillemets with a narrow no break
 * space inside; Spanish and Italian the guillemets with the curly pair for single quotes. A
 * language outside the table reads as English.
 */
export const QUOTE_STYLES: Readonly<Record<string, QuoteStyle>> = {
  en: CURLY,
  pt: CURLY,
  nl: CURLY,
  de: { double: ['„', '“'], single: ['‚', '‘'] },
  fr: { double: ['«', '»'], single: ['‹', '›'], inner: ' ' },
  es: { double: ['«', '»'], single: ['“', '”'] },
  it: { double: ['«', '»'], single: ['“', '”'] },
};

/** The quote style of a BCP 47 tag: the primary subtag's row, English when the table has none. */
export function quoteStyleFor(language: string): QuoteStyle {
  const primary = language.split('-')[0]?.toLowerCase() ?? 'en';
  return QUOTE_STYLES[primary] ?? CURLY;
}

/** The typed prefixes that start a bulleted list when followed by a space (R10 1.3 "List detection"; G11). */
export const BULLET_PREFIXES: ReadonlyArray<string> = ['-', '*', '•'];

/**
 * The typed prefixes that start a numbered list when followed by a space (R10 1.3; G11 "1)",
 * "a.", "as would other permutations like I., (A), etc."): a digit, a letter or a roman numeral
 * with a period, a closing parenthesis or in parentheses. Each row maps the form to the number
 * preset family the list takes (the digit, alpha or roman form at level 1 of the presets of
 * `text.ts`).
 */
export const NUMBER_PREFIX_PATTERN =
  /^(?:\(?(?<num>\d{1,2})[.)]|\(?(?<roman>[ivxIVX]{1,4})[.)]|\(?(?<alpha>[a-zA-Z])[.)])$/;

/** The number preset a typed numeral form implies (the presets of `text.ts` NUMBER_PRESETS). */
export const NUMBER_PREFIX_PRESETS: Readonly<Record<'num' | 'alpha' | 'roman', string>> = {
  num: 'digit-alpha-roman',
  alpha: 'alpha-roman-digit',
  roman: 'roman-alpha-digit',
};

/** The closing punctuation marks that fire the sentence and substitution rules beside a space and Enter (R10 1.3). */
export const TRIGGER_PUNCTUATION: ReadonlyArray<string> = ['.', ',', ';', ':', '!', '?', ')'];
