// The grammar linter's rule table (SPEC 7.7). Rule ids are constants here so the docs table and
// the CLI's --rule filter are generated from one source; the checks themselves live in
// @turboslide/lint. Severity 3 must fix (the gate), 2 should fix, 1 polish.

export type RuleLayer = 'static' | 'rendered' | 'both';
export type RuleSeverity = 1 | 2 | 3;
export type FindingKind = 'defect' | 'diagram' | 'polish' | 'copy' | 'accuracy';

export type Rule = {
  id: RuleId;
  layer: RuleLayer;
  severity: RuleSeverity;
  kind: FindingKind;
  check: string;
  /** true when the finding carries mechanical `fix` mutations */
  fix: boolean;
  source: string;
};

export const RULE_IDS = [
  'sheet/overflow',
  'sheet/rail-touch',
  'sheet/thumb-legible',
  'type/floor-15',
  'type/svg-label-min',
  'type/weight-cap',
  'type/face',
  'type/sizes-ladder',
  'type/ladder',
  'text/overflow',
  'color/tokens-only',
  'color/semantic-icons-only',
  'color/off-palette',
  'icon/placement',
  'icon/known',
  'rows/two-lines',
  'rows/key-snap',
  'dia/label-clearance',
  'dia/stroke-grammar',
  'dia/fit-slot',
  'dia/half-pixel',
  'asset/twin-or-border',
  'asset/credit-on-plate',
  'asset/license-missing',
  'asset/stretched',
  'picture/plate-clear',
  'picture/blank-twin',
  'picture/mood-placement',
  'opener/sentence-lists-section',
  'lines/law',
  'copy/heading-period',
  'copy/sentence-case',
  'copy/token-first',
  'copy/heading-is-name',
  'copy/no-em-dash',
  'copy/no-exclamation',
  'copy/no-eyebrow',
  'copy/full-sentence-caption',
  'copy/contrast-pair',
  'copy/metaphor-candidate',
  'copy/empty-placeholder',
  'table/size',
  'chart/size',
  'contrast/both-themes',
  'layout/empty-half',
  'layout/pair-gaps',
  'layout/columns-aligned',
  'layout/freeform',
  'freeform/overlap',
  'freeform/off-sheet',
  'scales/marker-equals-value',
  'escape/html-block',
  'html/sanitize',
  'export/non-native',
  'numbers/contradiction',
  'count/hard-coded',
] as const;

export type RuleId = (typeof RULE_IDS)[number];

function rule(
  id: RuleId,
  layer: RuleLayer,
  severity: RuleSeverity,
  kind: FindingKind,
  check: string,
  fix: boolean,
  source: string,
): Rule {
  return { id, layer, severity, kind, check, fix, source };
}

export const RULES: Readonly<Record<RuleId, Rule>> = {
  'sheet/overflow': rule(
    'sheet/overflow',
    'rendered',
    3,
    'defect',
    'any data-block box outside 0..1600 by 0..900',
    false,
    'DECK-GRAMMAR.md:15, shoot-slide.mjs:47-56',
  ),
  'sheet/rail-touch': rule(
    'sheet/rail-touch',
    'rendered',
    2,
    'defect',
    'a text box within 8 px of a rail or rule',
    false,
    'DECK-GRAMMAR.md:15',
  ),
  'sheet/thumb-legible': rule(
    'sheet/thumb-legible',
    'rendered',
    1,
    'polish',
    'text whose rendered size (font size times the diagram scale) is under 2 px at the grid’s 0.14x',
    false,
    'report 03 section 1',
  ),
  'type/floor-15': rule(
    'type/floor-15',
    'rendered',
    3,
    'defect',
    'computed font size under 15 px on any text node',
    false,
    'DECK-GRAMMAR.md:21',
  ),
  'type/svg-label-min': rule(
    'type/svg-label-min',
    'both',
    3,
    'diagram',
    'diagram text under 18 px, or 18 px without sm',
    false,
    'head:157-160',
  ),
  'type/weight-cap': rule(
    'type/weight-cap',
    'both',
    3,
    'defect',
    'display weight above 500 outside spec',
    true,
    'DECK-GRAMMAR.md:20',
  ),
  'type/face': rule(
    'type/face',
    'rendered',
    3,
    'defect',
    'a font status of fallback for Inter',
    false,
    'pptx report section 4.4',
  ),
  'type/sizes-ladder': rule(
    'type/sizes-ladder',
    'static',
    2,
    'defect',
    'a heading or paragraph size outside the ladder',
    true,
    'head:59-65',
  ),
  'type/ladder': rule(
    'type/ladder',
    'static',
    2,
    'defect',
    'a typography size on a heading, paragraph, text or box block outside the type ladder',
    true,
    'head:59-65; docs/freeform.md',
  ),
  'text/overflow': rule(
    'text/overflow',
    'rendered',
    2,
    'defect',
    'text that leaves its box on a positioned block under autofit none or absent, or when shrink reached the ladder floor; the fix writes the step down or the box height (gslides-parity SPEC-2 2.1.5)',
    true,
    'gslides-parity SPEC-2 0.23, 0.64',
  ),
  'color/tokens-only': rule(
    'color/tokens-only',
    'static',
    3,
    'defect',
    'a color literal in html CSS or raw svg outside the sanctioned exceptions (swatch, panel, logoPlates)',
    false,
    'DECK-GRAMMAR.md:28',
  ),
  'color/semantic-icons-only': rule(
    'color/semantic-icons-only',
    'static',
    3,
    'defect',
    'a semantic hue on anything but an Icon; on a text run the finding is severity 1 (gslides-parity SPEC-2 0.6)',
    false,
    'DECK-GRAMMAR.md:30; gslides-parity SPEC-2 2.2.5',
  ),
  'color/off-palette': rule(
    'color/off-palette',
    'static',
    2,
    'defect',
    'a custom hex color on a primitive block instead of a palette token, named with the block',
    false,
    'DECK-GRAMMAR.md:28; docs/freeform.md',
  ),
  'icon/placement': rule(
    'icon/placement',
    'static',
    3,
    'defect',
    'an icon outside a rows key, a plain row start, a board state or a dia; size not 20 or 24',
    false,
    'DECK-GRAMMAR.md:40',
  ),
  'icon/known': rule(
    'icon/known',
    'static',
    3,
    'defect',
    'an IconName not in the sprite',
    false,
    'report 03 section 11 item 12',
  ),
  'rows/two-lines': rule(
    'rows/two-lines',
    'rendered',
    2,
    'defect',
    'a row value or a table cell taller than two line heights',
    false,
    'DECK-GRAMMAR.md:36',
  ),
  'rows/key-snap': rule(
    'rows/key-snap',
    'static',
    1,
    'polish',
    'a key width outside the snap set',
    true,
    'report 03 section 11 item 6',
  ),
  'dia/label-clearance': rule(
    'dia/label-clearance',
    'both',
    2,
    'diagram',
    'a label box within 12 px of a stroke',
    false,
    'DECK-GRAMMAR.md:45',
  ),
  'dia/stroke-grammar': rule(
    'dia/stroke-grammar',
    'static',
    2,
    'diagram',
    'stroke not 1 or 1.5, round caps or joins, filled arrowheads over 8 px, fill outside ink, paper, plate',
    false,
    'DECK-GRAMMAR.md:44',
  ),
  'dia/fit-slot': rule(
    'dia/fit-slot',
    'static',
    1,
    'diagram',
    'a viewBox width that does not equal its slot width',
    true,
    'report 03 section 1',
  ),
  'dia/half-pixel': rule(
    'dia/half-pixel',
    'static',
    1,
    'diagram',
    'an odd-width stroke on an integer coordinate',
    true,
    'report 03 section 5.11',
  ),
  'asset/twin-or-border': rule(
    'asset/twin-or-border',
    'static',
    3,
    'defect',
    'a shot or pair image with a neutral twin and no border',
    true,
    'DECK-GRAMMAR.md:56',
  ),
  'asset/credit-on-plate': rule(
    'asset/credit-on-plate',
    'static',
    3,
    'defect',
    'a share-alike source whose credit is missing from the plate',
    false,
    'OPENERS.md:255',
  ),
  'asset/license-missing': rule(
    'asset/license-missing',
    'static',
    2,
    'accuracy',
    'a photograph with no license record',
    false,
    'report 06 section 4 item 9',
  ),
  'asset/stretched': rule(
    'asset/stretched',
    'rendered',
    2,
    'defect',
    'an image drawn at an aspect other than its file’s, outside crop',
    false,
    'DECK-GRAMMAR.md:61',
  ),
  'picture/plate-clear': rule(
    'picture/plate-clear',
    'static',
    2,
    'defect',
    'lit cells inside the plate rectangle or within 30 px of it',
    false,
    'OPENERS.md:105, 176',
  ),
  'picture/blank-twin': rule(
    'picture/blank-twin',
    'static',
    3,
    'defect',
    'a two-tone twin with lit fraction under 0.02 or over 0.98',
    false,
    'OPENERS.md:251',
  ),
  'picture/mood-placement': rule(
    'picture/mood-placement',
    'static',
    2,
    'polish',
    'a mood slide directly before an opener, or two mood slides adjacent',
    false,
    'OPENERS.md:137',
  ),
  'opener/sentence-lists-section': rule(
    'opener/sentence-lists-section',
    'static',
    1,
    'copy',
    'the opener sentence does not mention each family in the section',
    false,
    'OPENERS.md:44',
  ),
  'lines/law': rule(
    'lines/law',
    'rendered',
    2,
    'defect',
    'doubled hairlines within 4 px, junctions drawn twice, a border color outside the three roles',
    false,
    'lint-lines.mjs:1-28',
  ),
  'copy/heading-period': rule(
    'copy/heading-period',
    'static',
    3,
    'copy',
    'a heading, plate title or key ending in a period',
    true,
    'DECK-GRAMMAR.md:22',
  ),
  'copy/sentence-case': rule(
    'copy/sentence-case',
    'static',
    2,
    'copy',
    'a heading with Title Case outside the proper-noun and token lists',
    true,
    'DECK-GRAMMAR.md:22',
  ),
  'copy/token-first': rule(
    'copy/token-first',
    'static',
    2,
    'copy',
    'a heading starting with a product token',
    false,
    'DECK-GRAMMAR.md:22',
  ),
  'copy/heading-is-name': rule(
    'copy/heading-is-name',
    'static',
    2,
    'copy',
    'a heading containing a domain',
    false,
    'DECK-GRAMMAR.md:22',
  ),
  'copy/no-em-dash': rule(
    'copy/no-em-dash',
    'static',
    3,
    'copy',
    'an em dash present',
    true,
    'DECK-GRAMMAR.md:23',
  ),
  'copy/no-exclamation': rule(
    'copy/no-exclamation',
    'static',
    3,
    'copy',
    'an exclamation mark present',
    true,
    'DECK-GRAMMAR.md:23',
  ),
  'copy/no-eyebrow': rule(
    'copy/no-eyebrow',
    'static',
    2,
    'copy',
    'a short cap or all-caps line as the first block above a heading',
    false,
    'DECK-GRAMMAR.md:23',
  ),
  'copy/full-sentence-caption': rule(
    'copy/full-sentence-caption',
    'static',
    1,
    'copy',
    'a caption without a terminal period',
    true,
    'DECK-GRAMMAR.md:23',
  ),
  'copy/contrast-pair': rule(
    'copy/contrast-pair',
    'static',
    1,
    'copy',
    '"not" followed by a comma clause, for the copy judge',
    false,
    'DECK-GRAMMAR.md:23',
  ),
  'copy/metaphor-candidate': rule(
    'copy/metaphor-candidate',
    'static',
    1,
    'copy',
    'a word list hit (journey, unlock, supercharge)',
    false,
    'DECK-GRAMMAR.md:23',
  ),
  'copy/empty-placeholder': rule(
    'copy/empty-placeholder',
    'static',
    1,
    'copy',
    'an empty Text where a layout placeholder waits for copy: a title, a subtitle, a paragraph, a text box, a list item, a table cell or a caption',
    false,
    'gslides-parity SPEC 5.4',
  ),
  'table/size': rule(
    'table/size',
    'static',
    3,
    'defect',
    'a table over 20 by 20 cells, or a row without one cell per column',
    false,
    'gslides-parity SPEC 7.3; R11 A8',
  ),
  'chart/size': rule(
    'chart/size',
    'static',
    2,
    'defect',
    'more than 8 categories in a chart narrower than 960 px, or a pie with more than 8 slices (gslides-parity SPEC-2 0.60)',
    false,
    'gslides-parity SPEC-2 2.8.1',
  ),
  'contrast/both-themes': rule(
    'contrast/both-themes',
    'rendered',
    2,
    'defect',
    'sampled text against ground under 4.5:1 (3:1 at 26 px and up) in either theme',
    false,
    'DECK-GRAMMAR.md:61',
  ),
  'layout/empty-half': rule(
    'layout/empty-half',
    'rendered',
    2,
    'defect',
    'ink coverage under 2 percent in one column of a cols slide while the other exceeds 10',
    false,
    'DECK-GRAMMAR.md:61',
  ),
  'layout/pair-gaps': rule(
    'layout/pair-gaps',
    'rendered',
    2,
    'defect',
    'unequal gaps in a pair or details grid beyond 2 px',
    false,
    'DECK-GRAMMAR.md:61',
  ),
  'layout/columns-aligned': rule(
    'layout/columns-aligned',
    'rendered',
    2,
    'defect',
    'tops of side-by-side rows blocks differing by more than 1 px',
    false,
    'report 03 section 11 item 4',
  ),
  'layout/freeform': rule(
    'layout/freeform',
    'static',
    1,
    'polish',
    'a slide arranged by hand on the canvas; Apply layout re-flows it (gslides-parity SPEC-2 1.4)',
    false,
    'docs/freeform.md; gslides-parity SPEC-2 0.76',
  ),
  'freeform/overlap': rule(
    'freeform/overlap',
    'static',
    1,
    'defect',
    'two objects that carry text placed over each other; a picture or a textless box under a text is the design (gslides-parity SPEC-2 1.4)',
    false,
    'docs/freeform.md; gslides-parity SPEC-2 0.76',
  ),
  'freeform/off-sheet': rule(
    'freeform/off-sheet',
    'static',
    3,
    'defect',
    'an object whose rotated bounding box lies wholly outside the 1600 by 900 sheet; one that crosses an edge is severity 2 (gslides-parity SPEC-2 0.96)',
    false,
    'DECK-GRAMMAR.md:15; docs/freeform.md; gslides-parity SPEC-2 0.96',
  ),
  'scales/marker-equals-value': rule(
    'scales/marker-equals-value',
    'static',
    3,
    'accuracy',
    'a marker authored rather than derived; only possible in imported html',
    false,
    'DECK-GRAMMAR.md:61',
  ),
  'escape/html-block': rule(
    'escape/html-block',
    'static',
    2,
    'polish',
    'an html block exists; export is raster for it',
    false,
    'report 05 section 6.1',
  ),
  'html/sanitize': rule(
    'html/sanitize',
    'static',
    2,
    'defect',
    'an html block without the htmlSanitized stamp: markup and CSS the parser and the tokenizer have not passed; the fix writes the cleaned strings and the stamp, by hand, never inside migrate',
    true,
    'gslides-parity SPEC-3 8.4',
  ),
  'export/non-native': rule(
    'export/non-native',
    'static',
    1,
    'polish',
    'a block that exports as raster in the requested mode, listed per export',
    false,
    'design C section 6.7',
  ),
  'numbers/contradiction': rule(
    'numbers/contradiction',
    'static',
    1,
    'accuracy',
    'the same noun with different numerals across slides, for the accuracy judge',
    false,
    'DECK-GRAMMAR.md:61',
  ),
  'count/hard-coded': rule(
    'count/hard-coded',
    'static',
    3,
    'accuracy',
    'a numeral equal to the slide count inside copy that should derive from the deck',
    false,
    'report 06 section 4 item 2',
  ),
};

export function isRuleId(value: string): value is RuleId {
  return (RULE_IDS as ReadonlyArray<string>).includes(value);
}

/** Rules in table order, for the generated docs. */
export function rulesInOrder(): Rule[] {
  return RULE_IDS.map((id) => RULES[id]);
}

/** The rules a layer runs: `rendered` includes the rules of both layers. */
export function ruleIdsOfLayer(layer: 'static' | 'rendered'): RuleId[] {
  return RULE_IDS.filter((id) => RULES[id].layer === layer || RULES[id].layer === 'both');
}

/**
 * The measured limits of the rendered rules (SPEC 7.7; MILESTONES M3 item 5), one source for the
 * checks in @turboslide/lint and for the numbers the rule table quotes. Distances are sheet pixels
 * at scale 1; fractions are of an area or of an aspect ratio.
 */
export const RENDERED_LIMITS = {
  /** sheet/rail-touch: a text box closer than this to a rail or rule (DECK-GRAMMAR.md:15). */
  railTouchPx: 8,
  /** type/floor-15 (DECK-GRAMMAR.md:21). */
  floorPx: 15,
  /** type/svg-label-min (head:157-160). */
  svgLabelMinPx: 18,
  /** type/weight-cap (DECK-GRAMMAR.md:20). */
  weightCap: 500,
  /** dia/label-clearance: a label box this close to a stroke (DECK-GRAMMAR.md:45). */
  labelClearancePx: 12,
  /** lines/law: two parallel 1 px lines this close, edge to edge, are one seam drawn twice. */
  doubledLinePx: 4,
  /** lines/law: the shortest uniform 1 px run that counts as a drawn line. */
  lineMinRunPx: 48,
  /** lines/law: the per-channel distance within which a line color matches a role. */
  lineColorTolerance: 10,
  /** contrast/both-themes: WCAG ratios; the lower floor applies from contrastLargePx up. */
  contrastMin: 4.5,
  contrastLargeMin: 3,
  contrastLargePx: 26,
  /** layout/empty-half: ink coverage of one column under the first while the other exceeds the second. */
  emptyHalfMaxFraction: 0.02,
  fullHalfMinFraction: 0.1,
  /** layout/pair-gaps: the spread of the gaps in a figure grid. */
  pairGapPx: 2,
  /** layout/columns-aligned: the difference of the tops of side-by-side rows blocks. */
  columnsAlignedPx: 1,
  /** asset/stretched: the relative deviation of the drawn aspect from the file's, and its pixel floor. */
  stretchedFraction: 0.02,
  stretchedMinPx: 2,
  /** sheet/thumb-legible: the grid's smallest scale (report 03 section 1) and the size legible at it. */
  thumbScale: 0.14,
  thumbMinPx: 2,
} as const;

export type RenderedLimits = typeof RENDERED_LIMITS;
