/**
 * The characters the Insert special characters dialog offers (gslides-parity SPEC-2 0.36, 6.2,
 * section 10): Google's six categories, each character with the name a person searches by (the
 * Unicode name in plain words). Committed data, no network; the dialog's search matches the name
 * and the category. About 340 characters: the arrows, punctuation, currency and math people put
 * in slides, the common symbols and the emoji the reports saw in decks. Google's drawing box is
 * not built (round three).
 */
export type SpecialCharacterCategory =
  'Arrows' | 'Punctuation' | 'Currency' | 'Math' | 'Symbols' | 'Emoji';

export type SpecialCharacter = {
  char: string;
  name: string;
  category: SpecialCharacterCategory;
};

export const SPECIAL_CHARACTER_CATEGORIES: ReadonlyArray<SpecialCharacterCategory> = [
  'Arrows',
  'Punctuation',
  'Currency',
  'Math',
  'Symbols',
  'Emoji',
];

const rows = (category: SpecialCharacterCategory, list: ReadonlyArray<[string, string]>) =>
  list.map(([char, name]): SpecialCharacter => ({ char, name, category }));

export const SPECIAL_CHARACTERS: ReadonlyArray<SpecialCharacter> = [
  ...rows('Arrows', [
    ['←', 'Leftwards arrow'],
    ['↑', 'Upwards arrow'],
    ['→', 'Rightwards arrow'],
    ['↓', 'Downwards arrow'],
    ['↔', 'Left right arrow'],
    ['↕', 'Up down arrow'],
    ['↖', 'North west arrow'],
    ['↗', 'North east arrow'],
    ['↘', 'South east arrow'],
    ['↙', 'South west arrow'],
    ['↚', 'Leftwards arrow with stroke'],
    ['↛', 'Rightwards arrow with stroke'],
    ['↞', 'Leftwards two headed arrow'],
    ['↠', 'Rightwards two headed arrow'],
    ['↢', 'Leftwards arrow with tail'],
    ['↣', 'Rightwards arrow with tail'],
    ['↤', 'Leftwards arrow from bar'],
    ['↦', 'Rightwards arrow from bar'],
    ['↩', 'Leftwards arrow with hook'],
    ['↪', 'Rightwards arrow with hook'],
    ['↫', 'Leftwards arrow with loop'],
    ['↬', 'Rightwards arrow with loop'],
    ['↭', 'Left right wave arrow'],
    ['↰', 'Upwards arrow with tip leftwards'],
    ['↱', 'Upwards arrow with tip rightwards'],
    ['↲', 'Downwards arrow with tip leftwards'],
    ['↳', 'Downwards arrow with tip rightwards'],
    ['↴', 'Rightwards arrow with corner downwards'],
    ['↵', 'Downwards arrow with corner leftwards'],
    ['↶', 'Anticlockwise top semicircle arrow'],
    ['↷', 'Clockwise top semicircle arrow'],
    ['↺', 'Anticlockwise open circle arrow'],
    ['↻', 'Clockwise open circle arrow'],
    ['⇄', 'Rightwards arrow over leftwards arrow'],
    ['⇅', 'Upwards arrow leftwards of downwards arrow'],
    ['⇆', 'Leftwards arrow over rightwards arrow'],
    ['⇇', 'Leftwards paired arrows'],
    ['⇈', 'Upwards paired arrows'],
    ['⇉', 'Rightwards paired arrows'],
    ['⇊', 'Downwards paired arrows'],
    ['⇐', 'Leftwards double arrow'],
    ['⇑', 'Upwards double arrow'],
    ['⇒', 'Rightwards double arrow'],
    ['⇓', 'Downwards double arrow'],
    ['⇔', 'Left right double arrow'],
    ['⇕', 'Up down double arrow'],
    ['⇚', 'Leftwards triple arrow'],
    ['⇛', 'Rightwards triple arrow'],
    ['⇠', 'Leftwards dashed arrow'],
    ['⇡', 'Upwards dashed arrow'],
    ['⇢', 'Rightwards dashed arrow'],
    ['⇣', 'Downwards dashed arrow'],
    ['⇤', 'Leftwards arrow to bar'],
    ['⇥', 'Rightwards arrow to bar'],
    ['⇦', 'Leftwards white arrow'],
    ['⇧', 'Upwards white arrow'],
    ['⇨', 'Rightwards white arrow'],
    ['⇩', 'Downwards white arrow'],
    ['⇵', 'Downwards arrow leftwards of upwards arrow'],
    ['⟵', 'Long leftwards arrow'],
    ['⟶', 'Long rightwards arrow'],
    ['⟷', 'Long left right arrow'],
    ['⟸', 'Long leftwards double arrow'],
    ['⟹', 'Long rightwards double arrow'],
    ['⟺', 'Long left right double arrow'],
    ['➔', 'Heavy wide headed rightwards arrow'],
    ['➜', 'Heavy round tipped rightwards arrow'],
    ['➝', 'Triangle headed rightwards arrow'],
    ['➞', 'Heavy triangle headed rightwards arrow'],
    ['➡', 'Black rightwards arrow'],
    ['➢', 'Three D top lighted rightwards arrowhead'],
    ['➤', 'Black rightwards arrowhead'],
    ['➥', 'Heavy black curved downwards and rightwards arrow'],
    ['➦', 'Heavy black curved upwards and rightwards arrow'],
    ['➨', 'Heavy concave pointed black rightwards arrow'],
    ['➲', 'Circled heavy white rightwards arrow'],
    ['➽', 'Heavy wedge tailed rightwards arrow'],
    ['⬅', 'Leftwards black arrow'],
    ['⬆', 'Upwards black arrow'],
    ['⬇', 'Downwards black arrow'],
    ['⬈', 'North east black arrow'],
    ['⬉', 'North west black arrow'],
    ['⬊', 'South east black arrow'],
    ['⬋', 'South west black arrow'],
    ['⤴', 'Arrow pointing rightwards then curving upwards'],
    ['⤵', 'Arrow pointing rightwards then curving downwards'],
    ['⥁', 'Clockwise closed circle arrow'],
    ['⥀', 'Anticlockwise closed circle arrow'],
  ]),
  ...rows('Punctuation', [
    ['‘', 'Left single quotation mark'],
    ['’', 'Right single quotation mark'],
    ['“', 'Left double quotation mark'],
    ['”', 'Right double quotation mark'],
    ['‚', 'Single low 9 quotation mark'],
    ['„', 'Double low 9 quotation mark'],
    ['‹', 'Single left pointing angle quotation mark'],
    ['›', 'Single right pointing angle quotation mark'],
    ['«', 'Left pointing double angle quotation mark'],
    ['»', 'Right pointing double angle quotation mark'],
    ['–', 'En dash'],
    ['—', 'Em dash'],
    ['―', 'Horizontal bar'],
    ['‐', 'Hyphen'],
    ['‑', 'Non breaking hyphen'],
    ['…', 'Horizontal ellipsis'],
    ['·', 'Middle dot'],
    ['•', 'Bullet'],
    ['‣', 'Triangular bullet'],
    ['⁃', 'Hyphen bullet'],
    ['◦', 'White bullet'],
    ['▪', 'Black small square'],
    ['†', 'Dagger'],
    ['‡', 'Double dagger'],
    ['§', 'Section sign'],
    ['¶', 'Pilcrow sign'],
    ['‖', 'Double vertical line'],
    ['‗', 'Double low line'],
    ['′', 'Prime'],
    ['″', 'Double prime'],
    ['‴', 'Triple prime'],
    ['‰', 'Per mille sign'],
    ['‱', 'Per ten thousand sign'],
    ['¡', 'Inverted exclamation mark'],
    ['¿', 'Inverted question mark'],
    ['‽', 'Interrobang'],
    ['⁂', 'Asterism'],
    ['※', 'Reference mark'],
    ['⁎', 'Low asterisk'],
    ['⁕', 'Flower punctuation mark'],
    ['⁓', 'Swung dash'],
    ['〃', 'Ditto mark'],
    ['〜', 'Wave dash'],
    ['¦', 'Broken bar'],
    ['ˉ', 'Modifier letter macron'],
    ['ˆ', 'Modifier letter circumflex accent'],
    ['˜', 'Small tilde'],
    ['¨', 'Diaeresis'],
    ['¯', 'Macron'],
    ['´', 'Acute accent'],
    ['`', 'Grave accent'],
    ['¸', 'Cedilla'],
    ['ª', 'Feminine ordinal indicator'],
    ['º', 'Masculine ordinal indicator'],
    [' ', 'No break space'],
    [' ', 'Thin space'],
    [' ', 'Hair space'],
    [' ', 'En space'],
    [' ', 'Em space'],
    ['‑', 'Non breaking hyphen'],
    ['­', 'Soft hyphen'],
    ['​', 'Zero width space'],
  ]),
  ...rows('Currency', [
    ['$', 'Dollar sign'],
    ['¢', 'Cent sign'],
    ['£', 'Pound sign'],
    ['¤', 'Currency sign'],
    ['¥', 'Yen sign'],
    ['€', 'Euro sign'],
    ['₹', 'Indian rupee sign'],
    ['₽', 'Ruble sign'],
    ['₩', 'Won sign'],
    ['₪', 'New sheqel sign'],
    ['₫', 'Dong sign'],
    ['₱', 'Peso sign'],
    ['₦', 'Naira sign'],
    ['₡', 'Colon sign'],
    ['₢', 'Cruzeiro sign'],
    ['₣', 'French franc sign'],
    ['₤', 'Lira sign'],
    ['₥', 'Mill sign'],
    ['₧', 'Peseta sign'],
    ['₨', 'Rupee sign'],
    ['₭', 'Kip sign'],
    ['₮', 'Tugrik sign'],
    ['₯', 'Drachma sign'],
    ['₰', 'German penny sign'],
    ['₲', 'Guarani sign'],
    ['₳', 'Austral sign'],
    ['₴', 'Hryvnia sign'],
    ['₵', 'Cedi sign'],
    ['₸', 'Tenge sign'],
    ['₺', 'Turkish lira sign'],
    ['₼', 'Manat sign'],
    ['₾', 'Lari sign'],
    ['₿', 'Bitcoin sign'],
    ['฿', 'Thai baht sign'],
    ['៛', 'Khmer riel sign'],
    ['﷼', 'Rial sign'],
    ['֏', 'Armenian dram sign'],
    ['₠', 'Euro currency sign'],
    ['₶', 'Livre tournois sign'],
    ['₷', 'Spesmilo sign'],
    ['₻', 'Nordic mark sign'],
  ]),
  ...rows('Math', [
    ['+', 'Plus sign'],
    ['−', 'Minus sign'],
    ['±', 'Plus minus sign'],
    ['∓', 'Minus or plus sign'],
    ['×', 'Multiplication sign'],
    ['÷', 'Division sign'],
    ['∕', 'Division slash'],
    ['⁄', 'Fraction slash'],
    ['=', 'Equals sign'],
    ['≠', 'Not equal to'],
    ['≈', 'Almost equal to'],
    ['≉', 'Not almost equal to'],
    ['≡', 'Identical to'],
    ['≢', 'Not identical to'],
    ['≅', 'Approximately equal to'],
    ['≃', 'Asymptotically equal to'],
    ['≜', 'Delta equal to'],
    ['≝', 'Equal to by definition'],
    ['≔', 'Colon equals'],
    ['<', 'Less than sign'],
    ['>', 'Greater than sign'],
    ['≤', 'Less than or equal to'],
    ['≥', 'Greater than or equal to'],
    ['≪', 'Much less than'],
    ['≫', 'Much greater than'],
    ['≮', 'Not less than'],
    ['≯', 'Not greater than'],
    ['∞', 'Infinity'],
    ['∝', 'Proportional to'],
    ['∼', 'Tilde operator'],
    ['∴', 'Therefore'],
    ['∵', 'Because'],
    ['∀', 'For all'],
    ['∃', 'There exists'],
    ['∄', 'There does not exist'],
    ['∅', 'Empty set'],
    ['∈', 'Element of'],
    ['∉', 'Not an element of'],
    ['∋', 'Contains as member'],
    ['∩', 'Intersection'],
    ['∪', 'Union'],
    ['⊂', 'Subset of'],
    ['⊃', 'Superset of'],
    ['⊆', 'Subset of or equal to'],
    ['⊇', 'Superset of or equal to'],
    ['⊄', 'Not a subset of'],
    ['∧', 'Logical and'],
    ['∨', 'Logical or'],
    ['¬', 'Not sign'],
    ['⊕', 'Circled plus'],
    ['⊗', 'Circled times'],
    ['⊙', 'Circled dot operator'],
    ['∘', 'Ring operator'],
    ['∙', 'Bullet operator'],
    ['⋅', 'Dot operator'],
    ['∑', 'N ary summation'],
    ['∏', 'N ary product'],
    ['∐', 'N ary coproduct'],
    ['∫', 'Integral'],
    ['∬', 'Double integral'],
    ['∭', 'Triple integral'],
    ['∮', 'Contour integral'],
    ['∂', 'Partial differential'],
    ['∇', 'Nabla'],
    ['∆', 'Increment'],
    ['√', 'Square root'],
    ['∛', 'Cube root'],
    ['∜', 'Fourth root'],
    ['∠', 'Angle'],
    ['∟', 'Right angle'],
    ['∡', 'Measured angle'],
    ['⊥', 'Up tack'],
    ['∥', 'Parallel to'],
    ['∦', 'Not parallel to'],
    ['°', 'Degree sign'],
    ['µ', 'Micro sign'],
    ['π', 'Greek small letter pi'],
    ['Σ', 'Greek capital letter sigma'],
    ['Ω', 'Greek capital letter omega'],
    ['Δ', 'Greek capital letter delta'],
    ['α', 'Greek small letter alpha'],
    ['β', 'Greek small letter beta'],
    ['γ', 'Greek small letter gamma'],
    ['δ', 'Greek small letter delta'],
    ['ε', 'Greek small letter epsilon'],
    ['θ', 'Greek small letter theta'],
    ['λ', 'Greek small letter lamda'],
    ['σ', 'Greek small letter sigma'],
    ['φ', 'Greek small letter phi'],
    ['ω', 'Greek small letter omega'],
    ['ℵ', 'Alef symbol'],
    ['ℏ', 'Planck constant over two pi'],
    ['ℓ', 'Script small l'],
    ['ℕ', 'Double struck capital n'],
    ['ℤ', 'Double struck capital z'],
    ['ℚ', 'Double struck capital q'],
    ['ℝ', 'Double struck capital r'],
    ['ℂ', 'Double struck capital c'],
    ['¼', 'Vulgar fraction one quarter'],
    ['½', 'Vulgar fraction one half'],
    ['¾', 'Vulgar fraction three quarters'],
    ['⅓', 'Vulgar fraction one third'],
    ['⅔', 'Vulgar fraction two thirds'],
    ['⅛', 'Vulgar fraction one eighth'],
    ['⅜', 'Vulgar fraction three eighths'],
    ['⅝', 'Vulgar fraction five eighths'],
    ['⅞', 'Vulgar fraction seven eighths'],
    ['¹', 'Superscript one'],
    ['²', 'Superscript two'],
    ['³', 'Superscript three'],
    ['⁴', 'Superscript four'],
    ['ⁿ', 'Superscript latin small letter n'],
    ['₀', 'Subscript zero'],
    ['₁', 'Subscript one'],
    ['₂', 'Subscript two'],
    ['₃', 'Subscript three'],
    ['‰', 'Per mille sign'],
    ['%', 'Percent sign'],
    ['⌈', 'Left ceiling'],
    ['⌉', 'Right ceiling'],
    ['⌊', 'Left floor'],
    ['⌋', 'Right floor'],
    ['⟨', 'Mathematical left angle bracket'],
    ['⟩', 'Mathematical right angle bracket'],
    ['⊤', 'Down tack'],
    ['⊢', 'Right tack'],
    ['⊨', 'True'],
    ['≀', 'Wreath product'],
    ['⋯', 'Midline horizontal ellipsis'],
    ['⋮', 'Vertical ellipsis'],
  ]),
  ...rows('Symbols', [
    ['©', 'Copyright sign'],
    ['®', 'Registered sign'],
    ['™', 'Trade mark sign'],
    ['℠', 'Service mark'],
    ['℗', 'Sound recording copyright'],
    ['№', 'Numero sign'],
    ['℃', 'Degree celsius'],
    ['℉', 'Degree fahrenheit'],
    ['Ω', 'Ohm sign'],
    ['℮', 'Estimated symbol'],
    ['✓', 'Check mark'],
    ['✔', 'Heavy check mark'],
    ['✗', 'Ballot x'],
    ['✘', 'Heavy ballot x'],
    ['☐', 'Ballot box'],
    ['☑', 'Ballot box with check'],
    ['☒', 'Ballot box with x'],
    ['★', 'Black star'],
    ['☆', 'White star'],
    ['✦', 'Black four pointed star'],
    ['✧', 'White four pointed star'],
    ['✪', 'Circled white star'],
    ['✯', 'Pinwheel star'],
    ['●', 'Black circle'],
    ['○', 'White circle'],
    ['◐', 'Circle with left half black'],
    ['◑', 'Circle with right half black'],
    ['◉', 'Fisheye'],
    ['◎', 'Bullseye'],
    ['■', 'Black square'],
    ['□', 'White square'],
    ['▢', 'White square with rounded corners'],
    ['▲', 'Black up pointing triangle'],
    ['△', 'White up pointing triangle'],
    ['▼', 'Black down pointing triangle'],
    ['▽', 'White down pointing triangle'],
    ['◀', 'Black left pointing triangle'],
    ['▶', 'Black right pointing triangle'],
    ['◄', 'Black left pointing pointer'],
    ['►', 'Black right pointing pointer'],
    ['◆', 'Black diamond'],
    ['◇', 'White diamond'],
    ['◈', 'White diamond containing black small diamond'],
    ['❖', 'Black diamond minus white x'],
    ['❏', 'Lower right drop shadowed white square'],
    ['❐', 'Upper right drop shadowed white square'],
    ['♠', 'Black spade suit'],
    ['♣', 'Black club suit'],
    ['♥', 'Black heart suit'],
    ['♦', 'Black diamond suit'],
    ['♤', 'White spade suit'],
    ['♧', 'White club suit'],
    ['♡', 'White heart suit'],
    ['♢', 'White diamond suit'],
    ['♩', 'Quarter note'],
    ['♪', 'Eighth note'],
    ['♫', 'Beamed eighth notes'],
    ['♬', 'Beamed sixteenth notes'],
    ['♭', 'Music flat sign'],
    ['♮', 'Music natural sign'],
    ['♯', 'Music sharp sign'],
    ['☀', 'Black sun with rays'],
    ['☁', 'Cloud'],
    ['☂', 'Umbrella'],
    ['☃', 'Snowman'],
    ['☄', 'Comet'],
    ['☉', 'Sun'],
    ['☽', 'First quarter moon'],
    ['☾', 'Last quarter moon'],
    ['♀', 'Female sign'],
    ['♂', 'Male sign'],
    ['⚥', 'Male and female sign'],
    ['⚠', 'Warning sign'],
    ['⚡', 'High voltage sign'],
    ['⚙', 'Gear'],
    ['⚖', 'Scales'],
    ['⚗', 'Alembic'],
    ['⚛', 'Atom symbol'],
    ['⚕', 'Staff of aesculapius'],
    ['☎', 'Black telephone'],
    ['☏', 'White telephone'],
    ['✉', 'Envelope'],
    ['✂', 'Black scissors'],
    ['✈', 'Airplane'],
    ['✎', 'Lower right pencil'],
    ['✏', 'Pencil'],
    ['✒', 'Black nib'],
    ['⌘', 'Place of interest sign'],
    ['⌥', 'Option key'],
    ['⇧', 'Upwards white arrow'],
    ['⌃', 'Up arrowhead'],
    ['⌫', 'Erase to the left'],
    ['⌦', 'Erase to the right'],
    ['⏎', 'Return symbol'],
    ['⎋', 'Broken circle with northwest arrow'],
    ['⌨', 'Keyboard'],
    ['⏏', 'Eject symbol'],
    ['⏻', 'Power symbol'],
    ['⏰', 'Alarm clock'],
    ['⌚', 'Watch'],
    ['⌛', 'Hourglass'],
    ['⏳', 'Hourglass with flowing sand'],
    ['⏱', 'Stopwatch'],
    ['⌂', 'House'],
    ['♻', 'Black universal recycling symbol'],
    ['☮', 'Peace symbol'],
    ['☯', 'Yin yang'],
    ['☢', 'Radioactive sign'],
    ['☣', 'Biohazard sign'],
    ['✝', 'Latin cross'],
    ['✡', 'Star of david'],
    ['☪', 'Star and crescent'],
    ['☸', 'Wheel of dharma'],
    ['⚑', 'Black flag'],
    ['⚐', 'White flag'],
    ['⚓', 'Anchor'],
    ['⚔', 'Crossed swords'],
    ['⚽', 'Soccer ball'],
    ['⚾', 'Baseball'],
    ['⛄', 'Snowman without snow'],
    ['⛅', 'Sun behind cloud'],
    ['⛔', 'No entry'],
    ['⛽', 'Fuel pump'],
    ['⛳', 'Flag in hole'],
    ['❄', 'Snowflake'],
    ['❅', 'Tight trifoliate snowflake'],
    ['❆', 'Heavy chevron snowflake'],
    ['❝', 'Heavy double turned comma quotation mark ornament'],
    ['❞', 'Heavy double comma quotation mark ornament'],
    ['❢', 'Heavy exclamation mark ornament'],
    ['❣', 'Heavy heart exclamation mark ornament'],
    ['❤', 'Heavy black heart'],
    ['❥', 'Rotated heavy black heart bullet'],
    ['➕', 'Heavy plus sign'],
    ['➖', 'Heavy minus sign'],
    ['➗', 'Heavy division sign'],
    ['✖', 'Heavy multiplication x'],
    ['①', 'Circled digit one'],
    ['②', 'Circled digit two'],
    ['③', 'Circled digit three'],
    ['④', 'Circled digit four'],
    ['⑤', 'Circled digit five'],
    ['⑥', 'Circled digit six'],
    ['⑦', 'Circled digit seven'],
    ['⑧', 'Circled digit eight'],
    ['⑨', 'Circled digit nine'],
    ['⑩', 'Circled number ten'],
    ['Ⓐ', 'Circled latin capital letter a'],
    ['Ⓑ', 'Circled latin capital letter b'],
    ['Ⓒ', 'Circled latin capital letter c'],
  ]),
  ...rows('Emoji', [
    ['😀', 'Grinning face'],
    ['😃', 'Grinning face with big eyes'],
    ['😄', 'Grinning face with smiling eyes'],
    ['😁', 'Beaming face with smiling eyes'],
    ['😆', 'Grinning squinting face'],
    ['😅', 'Grinning face with sweat'],
    ['🤣', 'Rolling on the floor laughing'],
    ['😂', 'Face with tears of joy'],
    ['🙂', 'Slightly smiling face'],
    ['😉', 'Winking face'],
    ['😊', 'Smiling face with smiling eyes'],
    ['😇', 'Smiling face with halo'],
    ['🥰', 'Smiling face with hearts'],
    ['😍', 'Smiling face with heart eyes'],
    ['😘', 'Face blowing a kiss'],
    ['😋', 'Face savoring food'],
    ['😎', 'Smiling face with sunglasses'],
    ['🤩', 'Star struck'],
    ['🥳', 'Partying face'],
    ['😏', 'Smirking face'],
    ['😐', 'Neutral face'],
    ['🤔', 'Thinking face'],
    ['🤫', 'Shushing face'],
    ['🤭', 'Face with hand over mouth'],
    ['😶', 'Face without mouth'],
    ['🙄', 'Face with rolling eyes'],
    ['😬', 'Grimacing face'],
    ['😴', 'Sleeping face'],
    ['😷', 'Face with medical mask'],
    ['🤒', 'Face with thermometer'],
    ['🤯', 'Exploding head'],
    ['🥶', 'Cold face'],
    ['🥵', 'Hot face'],
    ['😱', 'Face screaming in fear'],
    ['😢', 'Crying face'],
    ['😭', 'Loudly crying face'],
    ['😤', 'Face with steam from nose'],
    ['😡', 'Pouting face'],
    ['🤬', 'Face with symbols on mouth'],
    ['🤗', 'Hugging face'],
    ['🤝', 'Handshake'],
    ['👍', 'Thumbs up'],
    ['👎', 'Thumbs down'],
    ['👏', 'Clapping hands'],
    ['🙌', 'Raising hands'],
    ['🙏', 'Folded hands'],
    ['👋', 'Waving hand'],
    ['✌', 'Victory hand'],
    ['🤞', 'Crossed fingers'],
    ['👉', 'Backhand index pointing right'],
    ['👈', 'Backhand index pointing left'],
    ['👆', 'Backhand index pointing up'],
    ['👇', 'Backhand index pointing down'],
    ['💪', 'Flexed biceps'],
    ['🧠', 'Brain'],
    ['👀', 'Eyes'],
    ['❤️', 'Red heart'],
    ['🧡', 'Orange heart'],
    ['💛', 'Yellow heart'],
    ['💚', 'Green heart'],
    ['💙', 'Blue heart'],
    ['💜', 'Purple heart'],
    ['🖤', 'Black heart'],
    ['🤍', 'White heart'],
    ['💔', 'Broken heart'],
    ['💯', 'Hundred points'],
    ['💥', 'Collision'],
    ['💫', 'Dizzy'],
    ['⭐', 'Star'],
    ['🌟', 'Glowing star'],
    ['✨', 'Sparkles'],
    ['🔥', 'Fire'],
    ['🎉', 'Party popper'],
    ['🎊', 'Confetti ball'],
    ['🎯', 'Bullseye'],
    ['🏆', 'Trophy'],
    ['🥇', 'First place medal'],
    ['🥈', 'Second place medal'],
    ['🥉', 'Third place medal'],
    ['🚀', 'Rocket'],
    ['✅', 'Check mark button'],
    ['❌', 'Cross mark'],
    ['❓', 'Question mark'],
    ['❗', 'Exclamation mark'],
    ['⚠️', 'Warning'],
    ['🚫', 'Prohibited'],
    ['🔔', 'Bell'],
    ['🔒', 'Locked'],
    ['🔓', 'Unlocked'],
    ['🔑', 'Key'],
    ['💡', 'Light bulb'],
    ['🔍', 'Magnifying glass tilted left'],
    ['📈', 'Chart increasing'],
    ['📉', 'Chart decreasing'],
    ['📊', 'Bar chart'],
    ['📅', 'Calendar'],
    ['📌', 'Pushpin'],
    ['📎', 'Paperclip'],
    ['📝', 'Memo'],
    ['📣', 'Megaphone'],
    ['💬', 'Speech balloon'],
    ['💭', 'Thought balloon'],
    ['📧', 'E mail'],
    ['📱', 'Mobile phone'],
    ['💻', 'Laptop'],
    ['🖥', 'Desktop computer'],
    ['⌨️', 'Keyboard'],
    ['🖱', 'Computer mouse'],
    ['💾', 'Floppy disk'],
    ['🔗', 'Link'],
    ['🌐', 'Globe with meridians'],
    ['🌍', 'Globe showing europe africa'],
    ['🌎', 'Globe showing americas'],
    ['🌏', 'Globe showing asia australia'],
    ['🏠', 'House'],
    ['🏢', 'Office building'],
    ['🏭', 'Factory'],
    ['🚗', 'Automobile'],
    ['✈️', 'Airplane'],
    ['🚢', 'Ship'],
    ['⏰', 'Alarm clock'],
    ['⏳', 'Hourglass not done'],
    ['💰', 'Money bag'],
    ['💵', 'Dollar banknote'],
    ['💳', 'Credit card'],
    ['🛒', 'Shopping cart'],
    ['🎁', 'Wrapped gift'],
    ['🎓', 'Graduation cap'],
    ['📚', 'Books'],
    ['🔧', 'Wrench'],
    ['🔨', 'Hammer'],
    ['⚙️', 'Gear'],
    ['🧩', 'Puzzle piece'],
    ['🧭', 'Compass'],
    ['🗺', 'World map'],
    ['☀️', 'Sun'],
    ['🌙', 'Crescent moon'],
    ['☁️', 'Cloud'],
    ['🌧', 'Cloud with rain'],
    ['❄️', 'Snowflake'],
    ['🌈', 'Rainbow'],
    ['🌱', 'Seedling'],
    ['🌳', 'Deciduous tree'],
    ['🌸', 'Cherry blossom'],
    ['🍎', 'Red apple'],
    ['☕', 'Hot beverage'],
    ['🍕', 'Pizza'],
    ['🐶', 'Dog face'],
    ['🐱', 'Cat face'],
    ['🦊', 'Fox'],
    ['🐻', 'Bear'],
    ['🐼', 'Panda'],
    ['🦁', 'Lion'],
    ['🐝', 'Honeybee'],
    ['🦄', 'Unicorn'],
    ['🎵', 'Musical note'],
    ['🎶', 'Musical notes'],
    ['🎨', 'Artist palette'],
    ['🎬', 'Clapper board'],
    ['📷', 'Camera'],
    ['🎤', 'Microphone'],
    ['🏁', 'Chequered flag'],
    ['🚩', 'Triangular flag'],
  ]),
];

/** The characters whose name or category contains the query, case insensitive; every one for an empty query. */
export function searchSpecialCharacters(
  query: string,
  category: SpecialCharacterCategory | null,
): SpecialCharacter[] {
  const needle = query.trim().toLowerCase();
  return SPECIAL_CHARACTERS.filter(
    (entry) =>
      (category === null || entry.category === category) &&
      (needle === '' ||
        entry.name.toLowerCase().includes(needle) ||
        entry.char === needle ||
        entry.category.toLowerCase().includes(needle)),
  );
}

/** The name of a character, for the announcement after a pick. */
export function specialCharacterName(char: string): string {
  return SPECIAL_CHARACTERS.find((entry) => entry.char === char)?.name ?? char;
}
