/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 8ad247941a0caf401425af2f006864d2)
interface __BaseEnv_Env {
	ACCOUNTS: D1Database;
	TURBOSLIDE_PROTOCOL: string;
	TURBOSLIDE_ROOM_HINT: string;
	TURBOSLIDE_CHECKPOINT_IDLE_MS: string;
	TURBOSLIDE_CHECKPOINT_MAX_MS: string;
	TURBOSLIDE_BUILD_COMMIT: string;
	TURBOSLIDE_ROOM_SECRET: string;
	TURBOSLIDE_ROOM_BEARER: string;
	TURBOSLIDE_DB_BEARER: string;
	TURBOSLIDE_ROOM_SECRET_PREVIOUS: string;
	TURBOSLIDE_ROOM_BEARER_PREVIOUS: string;
	TURBOSLIDE_DB_BEARER_PREVIOUS: string;
	TURBOSLIDE_DB_STATEMENTS: string;
	VERCEL_AUTOMATION_BYPASS_SECRET: string;
	TURBOSLIDE_APP_ORIGIN: string;
	DECK_ROOM: DurableObjectNamespace<import("./src/index").DeckRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DeckRoom";
	}
	interface PreviewEnv {
		ACCOUNTS: D1Database;
		TURBOSLIDE_PROTOCOL: string;
		TURBOSLIDE_ROOM_HINT: string;
		TURBOSLIDE_CHECKPOINT_IDLE_MS: string;
		TURBOSLIDE_CHECKPOINT_MAX_MS: string;
		TURBOSLIDE_BUILD_COMMIT: string;
		TURBOSLIDE_ROOM_SECRET: string;
		TURBOSLIDE_ROOM_BEARER: string;
		TURBOSLIDE_DB_BEARER: string;
		TURBOSLIDE_ROOM_SECRET_PREVIOUS: string;
		TURBOSLIDE_ROOM_BEARER_PREVIOUS: string;
		TURBOSLIDE_DB_BEARER_PREVIOUS: string;
		TURBOSLIDE_DB_STATEMENTS: string;
		VERCEL_AUTOMATION_BYPASS_SECRET: string;
		TURBOSLIDE_APP_ORIGIN: string;
		DECK_ROOM: DurableObjectNamespace<import("./src/index").DeckRoom>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURBOSLIDE_PROTOCOL" | "TURBOSLIDE_ROOM_HINT" | "TURBOSLIDE_CHECKPOINT_IDLE_MS" | "TURBOSLIDE_CHECKPOINT_MAX_MS" | "TURBOSLIDE_BUILD_COMMIT" | "TURBOSLIDE_ROOM_SECRET" | "TURBOSLIDE_ROOM_BEARER" | "TURBOSLIDE_DB_BEARER" | "TURBOSLIDE_ROOM_SECRET_PREVIOUS" | "TURBOSLIDE_ROOM_BEARER_PREVIOUS" | "TURBOSLIDE_DB_BEARER_PREVIOUS" | "TURBOSLIDE_DB_STATEMENTS" | "VERCEL_AUTOMATION_BYPASS_SECRET" | "TURBOSLIDE_APP_ORIGIN">> {}
}
