// The boot script's build module (docs/LANDING.md 3.2, 4.1, 6.1, 6.4; the second pass). V4 owns
// this file, `apps/studio/src/components/home/boot.ts` and the `boot.generated.ts` it writes.
// `scripts/build-home-assets.ts --boot` calls `deriveBoot(sentences)` with copy.ts `HERO.visit` and
// writes the text it returns, and `--check` compares that text with the file. The script is
// `bootSource` minified by the minifier Vite carries (no new dependency), at most 1 KB, and it
// reads no layout.
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { BOOT_LIMIT_BYTES, bootSource } from '../../apps/studio/src/components/home/boot.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

/** What a minified script may not call: anything that reads layout before the first paint. */
const LAYOUT_READS =
  /getBoundingClientRect|offset(Width|Height|Top|Left)|getComputedStyle|scroll(Top|Height)|client(Width|Height)/;

/** The minified boot script, or a thrown error naming the rule it breaks. */
export function bootScript(sentences: readonly string[]): string {
  return minifyBoot(bootSource(sentences).source);
}

/** A boot script's source minified and checked against 4.1's two rules. */
export function minifyBoot(source: string): string {
  const vite = createRequire(resolve(ROOT, 'apps/studio/package.json'))('vite') as {
    minifySync(name: string, code: string, options: Record<string, unknown>): { code: string };
  };
  const script = vite.minifySync('boot.js', source, { compress: true, mangle: true }).code.trim();
  const bytes = Buffer.byteLength(script);
  if (bytes > BOOT_LIMIT_BYTES)
    throw new Error(`the boot script is ${bytes} B minified, over ${BOOT_LIMIT_BYTES}`);
  if (LAYOUT_READS.test(script)) throw new Error('the boot script reads layout');
  return script;
}

/** The text of `boot.generated.ts`, unformatted (the entry formats it with the repository's Prettier). */
export function deriveBoot(sentences: readonly string[]): string {
  return generatedBoot(bootScript(sentences));
}

/** `boot.generated.ts`'s text around a minified script. */
export function generatedBoot(script: string): string {
  return `// Generated by scripts/build-home-assets.ts --boot (docs/LANDING.md 3.2, 4.1, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// \`BOOT_SCRIPT\` is \`bootSource(HERO.visit)\` of src/components/home/boot.ts (V4's) minified by the
// minifier Vite carries (scripts/home/boot.ts); src/routes/home.tsx inlines it as the first child of
// main#top. At most 1,000 bytes minified, and it reads no layout.

/** The minified boot script. */
export const BOOT_SCRIPT: string = ${JSON.stringify(script)};

/** sha256 of BOOT_SCRIPT, checked by \`build-home-assets.ts --check\` */
export const BOOT_SHA256: string = ${JSON.stringify(createHash('sha256').update(script).digest('hex'))};
`;
}
