// The font catalog (gslides-parity SPEC-5-amendments A5 item 2; MILESTONES-5 B7 "Owns"): the
// faces Google Slides' Font menu also offers, each under the SIL Open Font License 1.1 or the
// Apache License 2.0, with the name PowerPoint and Google Slides use, Google's category, the
// weights, whether an italic ships, the licence, the woff2 files under packages/fonts/assets/<id>/
// and the pinned source in the Google Fonts repository. The ids are the schema's FONT_IDS
// (@turboslide/schema/fonts): the schema holds the ids alone so it stays at the bottom of the
// dependency direction, and catalog.test.ts asserts the two lists agree.
//
// Two tables meet here. FONT_SOURCES is the hand written membership: the repository directory
// of each family and what to take from it (the variable file where the family ships one, else a
// list of static weights). CATALOG_FILES (catalog-files.ts) is generated by
// scripts/fetch-fonts.mjs, which downloads the TrueType files and the licence at
// GOOGLE_FONTS_COMMIT, converts each file to woff2 with fontTools in the fonts venv (a format
// conversion alone: no subsetting, no renaming, no instancing, so a family's Reserved Font Name
// is kept under the OFL), and records the name table facts, the bytes and the sha256 of every
// file. The check chain never fetches; the assets are committed. Browser safe: no `node:` import
// (the picker and the renderer read this module); the file bytes are catalog-node.ts.
//
// Membership is Kevin's list (SPEC-5 17, the row A7 adds): a face joins or leaves as one id in
// FONT_IDS, one row in FONT_SOURCES, one run of the fetch script and one asset folder.
import type { FontCategory, FontId, FontLicence } from '@turboslide/schema/fonts';
import { FONT_IDS } from '@turboslide/schema/fonts';

import type { CatalogFamilyFacts, CatalogFile } from './catalog-files.ts';
import { CATALOG_FILES } from './catalog-files.ts';
import { CATEGORY_GENERIC, FONT_NAMES } from './names.ts';

export { CATEGORY_GENERIC, FONT_NAMES, fontFamilyName } from './names.ts';

/** The repository every fetched family comes from. */
export const GOOGLE_FONTS_REPOSITORY = 'https://github.com/google/fonts';

/** The commit of google/fonts the assets were fetched at (`main` on 2026-09-15, "drop compare meta"). */
export const GOOGLE_FONTS_COMMIT = '1ac2012c34919f5fa2675aacf723fa98edb30b5f';

/** The weights the picker can name (CSS's nine); a family carries the ones its files cover. */
export const STANDARD_WEIGHTS = [100, 200, 300, 400, 500, 600, 700, 800, 900] as const;

/**
 * What the fetch script takes from a family's directory: the variable file (and its italic twin
 * where one ships), a list of static weights (both styles where the italic ships), or nothing
 * because the files are already in the repository (Inter, from the rsms release; inter.ts).
 */
export type FontTake =
  { kind: 'variable' } | { kind: 'static'; weights: readonly number[] } | { kind: 'present' };

export type FontSource = {
  id: FontId;
  /** the family's directory in the repository (`ofl/<name>`), or the release for a present face */
  directory: string;
  take: FontTake;
};

/**
 * The membership (A5 item 2), in FONT_IDS order. A static family takes the five weights the
 * inspector offers (TYPE_WEIGHTS of the schema, 300 to 700) where the family ships them, so a
 * block set to any inspector weight renders in a real cut.
 */
export const FONT_SOURCES: readonly FontSource[] = [
  { id: 'inter', directory: 'rsms/inter v4.001 web/', take: { kind: 'present' } },
  { id: 'roboto', directory: 'ofl/roboto', take: { kind: 'variable' } },
  { id: 'open-sans', directory: 'ofl/opensans', take: { kind: 'variable' } },
  {
    id: 'lato',
    directory: 'ofl/lato',
    take: { kind: 'static', weights: [300, 400, 500, 600, 700] },
  },
  { id: 'montserrat', directory: 'ofl/montserrat', take: { kind: 'variable' } },
  {
    id: 'poppins',
    directory: 'ofl/poppins',
    take: { kind: 'static', weights: [300, 400, 500, 600, 700] },
  },
  { id: 'source-sans-3', directory: 'ofl/sourcesans3', take: { kind: 'variable' } },
  { id: 'source-serif-4', directory: 'ofl/sourceserif4', take: { kind: 'variable' } },
  { id: 'merriweather', directory: 'ofl/merriweather', take: { kind: 'variable' } },
  { id: 'playfair-display', directory: 'ofl/playfairdisplay', take: { kind: 'variable' } },
  { id: 'lora', directory: 'ofl/lora', take: { kind: 'variable' } },
  { id: 'pt-serif', directory: 'ofl/ptserif', take: { kind: 'static', weights: [400, 700] } },
  { id: 'libre-baskerville', directory: 'ofl/librebaskerville', take: { kind: 'variable' } },
  { id: 'eb-garamond', directory: 'ofl/ebgaramond', take: { kind: 'variable' } },
  { id: 'nunito', directory: 'ofl/nunito', take: { kind: 'variable' } },
  { id: 'raleway', directory: 'ofl/raleway', take: { kind: 'variable' } },
  { id: 'work-sans', directory: 'ofl/worksans', take: { kind: 'variable' } },
  { id: 'dm-sans', directory: 'ofl/dmsans', take: { kind: 'variable' } },
  { id: 'space-grotesk', directory: 'ofl/spacegrotesk', take: { kind: 'variable' } },
  { id: 'oswald', directory: 'ofl/oswald', take: { kind: 'variable' } },
  { id: 'bebas-neue', directory: 'ofl/bebasneue', take: { kind: 'static', weights: [400] } },
  { id: 'roboto-mono', directory: 'ofl/robotomono', take: { kind: 'variable' } },
  { id: 'jetbrains-mono', directory: 'ofl/jetbrainsmono', take: { kind: 'variable' } },
  { id: 'ibm-plex-sans', directory: 'ofl/ibmplexsans', take: { kind: 'variable' } },
  {
    id: 'ibm-plex-mono',
    directory: 'ofl/ibmplexmono',
    take: { kind: 'static', weights: [300, 400, 500, 600, 700] },
  },
  { id: 'fira-code', directory: 'ofl/firacode', take: { kind: 'variable' } },
];

/** One row of the catalog: the facts every surface reads (A5 item 2). */
export type CatalogFont = {
  id: FontId;
  /** the family name PowerPoint and Google Slides use; the `font-family` value and the `a:latin typeface` */
  name: string;
  category: FontCategory;
  /** the weights the files cover, ascending, from STANDARD_WEIGHTS */
  weights: number[];
  /** true when an italic file ships (a browser synthesizes the slant otherwise) */
  italic: boolean;
  licence: FontLicence;
  /** the Reserved Font Name the OFL text declares, or null; the files keep it because nothing but the container format changed */
  reservedFontName: string | null;
  files: CatalogFile[];
  source: FontSource;
};

const factsById = new Map<string, CatalogFamilyFacts>(CATALOG_FILES.map((row) => [row.id, row]));
const sourceById = new Map<string, FontSource>(FONT_SOURCES.map((row) => [row.id, row]));

/** The weights of STANDARD_WEIGHTS a file list covers: a range covers every step inside it. */
export function weightsOf(files: readonly CatalogFile[]): number[] {
  const out = new Set<number>();
  for (const file of files) {
    if (typeof file.weight === 'number') {
      out.add(file.weight);
      continue;
    }
    const [min, max] = file.weight;
    for (const weight of STANDARD_WEIGHTS) if (weight >= min && weight <= max) out.add(weight);
  }
  return [...out].sort((a, b) => a - b);
}

function composeRow(id: FontId): CatalogFont {
  const source = sourceById.get(id);
  if (source === undefined) throw new Error(`@turboslide/fonts: no FONT_SOURCES row for "${id}"`);
  const facts = factsById.get(id);
  const files = facts?.files ?? [];
  return {
    id,
    name: facts?.name ?? FONT_NAMES[id],
    category: facts?.category ?? 'sans',
    weights: weightsOf(files),
    italic: files.some((file) => file.style === 'italic'),
    licence: facts?.licence ?? 'OFL 1.1',
    reservedFontName: facts?.reservedFontName ?? null,
    files: [...files],
    source,
  };
}

/** Every face, in FONT_IDS order (the picker's "by category" groups sort within a category by this order). */
export const FONT_CATALOG: readonly CatalogFont[] = FONT_IDS.map(composeRow);

const rowById = new Map<string, CatalogFont>(FONT_CATALOG.map((row) => [row.id, row]));

/** The row of an id; throws on an id outside FONT_IDS. */
export function catalogFont(id: FontId): CatalogFont {
  const row = rowById.get(id);
  if (row === undefined) throw new RangeError(`@turboslide/fonts: no catalog row for "${id}"`);
  return row;
}

/** The `font-family` value of a face: its name quoted, then the category's generic family. */
export function fontFamilyStack(id: FontId): string {
  const row = catalogFont(id);
  return `'${row.name.replace(/'/g, "\\'")}', ${CATEGORY_GENERIC[row.category]}`;
}

/**
 * The custom property a block's `font-family` reads for a face (`--ts-font-<id>`): the schema's
 * typographyDeclarations writes `font-family:var(--ts-font-<id>, inherit)` from the id alone, and
 * @turboslide/render/fonts defines the property on the sheet root beside the family's @font-face
 * rules, so a document that never loaded the face inherits the theme's.
 */
export function fontFamilyVariable(id: FontId): string {
  return `--ts-font-${id}`;
}

/**
 * A file's path under packages/fonts/, the same for the checkout, a served asset route and the
 * TURBOSLIDE_PACKAGES_DIR folder: `assets/<id>/<file>` for a fetched family, `assets/<file>` for
 * the present Inter files (inter.ts named them before the catalog existed).
 */
export function fontAssetPath(id: FontId, file: string): string {
  return catalogFont(id).source.take.kind === 'present' ? `assets/${file}` : `assets/${id}/${file}`;
}

/** The rows of one category, in catalog order. */
export function fontsInCategory(category: FontCategory): CatalogFont[] {
  return FONT_CATALOG.filter((row) => row.category === category);
}

/** What `font.list` answers (SPEC-5-amendments A5 item 6; the action's output schema in actions.ts). */
export function catalogSummary(): {
  fonts: {
    id: FontId;
    name: string;
    category: FontCategory;
    weights: number[];
    italic: boolean;
    licence: FontLicence;
  }[];
} {
  return {
    fonts: FONT_CATALOG.map((row) => ({
      id: row.id,
      name: row.name,
      category: row.category,
      weights: [...row.weights],
      italic: row.italic,
      licence: row.licence,
    })),
  };
}
