// The font catalog (gslides-parity SPEC-5-amendments A5 item 2; MILESTONES-5 B7 "Owns"): the
// faces Google Slides' Font menu also offers, each under the SIL Open Font License 1.1 or the
// Apache License 2.0, with the name PowerPoint and Google Slides use, Google's category, the
// weights, whether an italic ships, the licence, the woff2 files under packages/fonts/assets/<id>/
// and the pinned source in the Google Fonts repository. The ids are the schema's FONT_IDS
// (@turboslide/schema/fonts): the schema holds the ids alone so it stays at the bottom of the
// dependency direction, and catalog.test.ts asserts the two lists agree.
//
// Two tables meet here. FONT_SOURCES is the hand written membership: the repository directory
// of each family and what to take from it (the variable file where the family ships one, else a
// list of static weights). CATALOG_FILES (catalog-files.ts) is generated by
// scripts/fetch-fonts.mjs, which downloads the TrueType files and the licence at
// GOOGLE_FONTS_COMMIT, converts each file to woff2 with fontTools in the fonts venv (a format
// conversion alone: no subsetting, no renaming, no instancing, so a family's Reserved Font Name
// is kept under the OFL), and records the name table facts, the bytes and the sha256 of every
// file. The check chain never fetches; the assets are committed. Browser safe: no `node:` import
// (the picker and the renderer read this module); the file bytes are catalog-node.ts.
//
// Membership is Kevin's list (SPEC-5 17, the row A7 adds): a face joins or leaves as one id in
// FONT_IDS, one row in FONT_SOURCES, one run of the fetch script and one asset folder.
import type { FontCategory, FontId, FontLicence } from '@turboslide/schema/fonts';
import { FONT_IDS } from '@turboslide/schema/fonts';

import type { CatalogFamilyFacts, CatalogFile } from './catalog-files.ts';
import { CATALOG_FILES } from './catalog-files.ts';
import { FONT_NAMES } from './names.ts';
import { licenceUrl, weightsOf } from './summary.ts';

export { CATEGORY_GENERIC, FONT_NAMES, fontFamilyName } from './names.ts';
export {
  STANDARD_WEIGHTS,
  weightsOf,
  fontFamilyStack,
  fontFamilyVariable,
  fontAssetPath,
  catalogSummary,
} from './summary.ts';

/** The repository every fetched family comes from. */
export const GOOGLE_FONTS_REPOSITORY = 'https://github.com/google/fonts';

/** The commit of google/fonts the assets were fetched at (`main` on 2026-09-15, "drop compare meta"). */
export const GOOGLE_FONTS_COMMIT = '1ac2012c34919f5fa2675aacf723fa98edb30b5f';

/**
 * What the fetch script takes from a family's directory: the variable file (and its italic twin
 * where one ships), a list of static weights (both styles where the italic ships), or nothing
 * because the files are already in the repository (Inter, from the rsms release; inter.ts).
 */
export type FontTake =
  { kind: 'variable' } | { kind: 'static'; weights: readonly number[] } | { kind: 'present' };

export type FontSource = {
  id: FontId;
  /** the family's directory in the repository (`ofl/<name>`), or the release for a present face */
  directory: string;
  take: FontTake;
};

/**
 * The membership (A5 item 2), in FONT_IDS order. A static family takes the five weights the
 * inspector offers (TYPE_WEIGHTS of the schema, 300 to 700) where the family ships them, so a
 * block set to any inspector weight renders in a real cut.
 */
export const FONT_SOURCES: readonly FontSource[] = [
  { id: 'inter', directory: 'rsms/inter v4.001 web/', take: { kind: 'present' } },
  { id: 'roboto', directory: 'ofl/roboto', take: { kind: 'variable' } },
  { id: 'open-sans', directory: 'ofl/opensans', take: { kind: 'variable' } },
  {
    id: 'lato',
    directory: 'ofl/lato',
    take: { kind: 'static', weights: [300, 400, 500, 600, 700] },
  },
  { id: 'montserrat', directory: 'ofl/montserrat', take: { kind: 'variable' } },
  {
    id: 'poppins',
    directory: 'ofl/poppins',
    take: { kind: 'static', weights: [300, 400, 500, 600, 700] },
  },
  { id: 'source-sans-3', directory: 'ofl/sourcesans3', take: { kind: 'variable' } },
  { id: 'source-serif-4', directory: 'ofl/sourceserif4', take: { kind: 'variable' } },
  { id: 'merriweather', directory: 'ofl/merriweather', take: { kind: 'variable' } },
  { id: 'playfair-display', directory: 'ofl/playfairdisplay', take: { kind: 'variable' } },
  { id: 'lora', directory: 'ofl/lora', take: { kind: 'variable' } },
  { id: 'pt-serif', directory: 'ofl/ptserif', take: { kind: 'static', weights: [400, 700] } },
  { id: 'libre-baskerville', directory: 'ofl/librebaskerville', take: { kind: 'variable' } },
  { id: 'eb-garamond', directory: 'ofl/ebgaramond', take: { kind: 'variable' } },
  { id: 'nunito', directory: 'ofl/nunito', take: { kind: 'variable' } },
  { id: 'raleway', directory: 'ofl/raleway', take: { kind: 'variable' } },
  { id: 'work-sans', directory: 'ofl/worksans', take: { kind: 'variable' } },
  { id: 'dm-sans', directory: 'ofl/dmsans', take: { kind: 'variable' } },
  { id: 'space-grotesk', directory: 'ofl/spacegrotesk', take: { kind: 'variable' } },
  { id: 'oswald', directory: 'ofl/oswald', take: { kind: 'variable' } },
  { id: 'bebas-neue', directory: 'ofl/bebasneue', take: { kind: 'static', weights: [400] } },
  { id: 'roboto-mono', directory: 'ofl/robotomono', take: { kind: 'variable' } },
  { id: 'jetbrains-mono', directory: 'ofl/jetbrainsmono', take: { kind: 'variable' } },
  { id: 'ibm-plex-sans', directory: 'ofl/ibmplexsans', take: { kind: 'variable' } },
  {
    id: 'ibm-plex-mono',
    directory: 'ofl/ibmplexmono',
    take: { kind: 'static', weights: [300, 400, 500, 600, 700] },
  },
  { id: 'fira-code', directory: 'ofl/firacode', take: { kind: 'variable' } },
];

/** One row of the catalog: the facts every surface reads (A5 item 2). */
export type CatalogFont = {
  id: FontId;
  /** the family name PowerPoint and Google Slides use; the `font-family` value and the `a:latin typeface` */
  name: string;
  category: FontCategory;
  /** the weights the files cover, ascending, from STANDARD_WEIGHTS */
  weights: number[];
  /** true when an italic file ships (a browser synthesizes the slant otherwise) */
  italic: boolean;
  licence: FontLicence;
  /** the Reserved Font Name the OFL text declares, or null; the files keep it because nothing but the container format changed */
  reservedFontName: string | null;
  files: CatalogFile[];
  source: FontSource;
  /** the licence text's address, the link More fonts carries (docs/PRODUCT.md 4.2) */
  licenceUrl: string;
};

const factsById = new Map<string, CatalogFamilyFacts>(CATALOG_FILES.map((row) => [row.id, row]));
const sourceById = new Map<string, FontSource>(FONT_SOURCES.map((row) => [row.id, row]));

function composeRow(id: FontId): CatalogFont {
  const source = sourceById.get(id);
  if (source === undefined) throw new Error(`@turboslide/fonts: no FONT_SOURCES row for "${id}"`);
  const facts = factsById.get(id);
  const files = facts?.files ?? [];
  return {
    id,
    name: facts?.name ?? FONT_NAMES[id],
    category: facts?.category ?? 'sans',
    weights: weightsOf(files),
    italic: files.some((file) => file.style === 'italic'),
    licence: facts?.licence ?? 'OFL 1.1',
    reservedFontName: facts?.reservedFontName ?? null,
    files: [...files],
    source,
    licenceUrl: licenceUrl(id, source.directory, GOOGLE_FONTS_COMMIT),
  };
}

/** Every face, in FONT_IDS order (the picker's "by category" groups sort within a category by this order). */
export const FONT_CATALOG: readonly CatalogFont[] = FONT_IDS.map(composeRow);

const rowById = new Map<string, CatalogFont>(FONT_CATALOG.map((row) => [row.id, row]));

/** The row of an id; throws on an id outside FONT_IDS. */
export function catalogFont(id: FontId): CatalogFont {
  const row = rowById.get(id);
  if (row === undefined) throw new RangeError(`@turboslide/fonts: no catalog row for "${id}"`);
  return row;
}

/** The rows of one category, in catalog order. */
export function fontsInCategory(category: FontCategory): CatalogFont[] {
  return FONT_CATALOG.filter((row) => row.category === category);
}
