// Generated by scripts/build-home-assets.ts --stills and --export (docs/LANDING.md 2.6, 2.8, 4.1, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
// assets.json is its JSON twin; assets.test.ts checks every file under public/home/ against it.

export type HomeAppearance = 'light' | 'dark';

/** What a file under public/home/ is (integrator.md section 6, with Kevin's answer 1). */
export type HomeAssetRole =
  /** slide 6's dithered picture (the Louisbourg lighthouse) as a two colour lossless WebP mask, at most 24 KB */
  | 'lighthouse-still'
  /** the lighthouse's tone map, a 512 by 288 grey JPEG, at most 26 KB, one for both appearances */
  | 'lighthouse-tone'
  /** slide 7's dithered picture (the opener field), requested only by the show and the print */
  | 'field-still'
  /** slide 8's still frame: the exporter's capture of the pattern, lossless WebP, at most 48 KB (V4's) */
  | 'pattern-still'
  /** the still frame's dots as one mask for both appearances, which the show, the print and the miniature draw in the slide's ink, at most 48 KB */
  | 'pattern-mask'
  /** slide 7's picture part from the Perfect file, at most 60 KB */
  | 'export-perfect'
  /** the Editable text file's picture part for slide 7, at most 32 KB */
  | 'export-editable'
  /** the CLI's browser render of slide 7 at scale 2, lossless WebP, at most 60 KB (the loupe, V3's) */
  | 'export-browser'
  /** the page deck's PDF, 9 pages, requested only on the click of Download the PDF */
  | 'pdf'
  /** the glyphs below the first screen: one SVG sprite of icons.tsx's symbols (scripts/home/sprite.ts), at most 48 KB */
  | 'glyphs';

/** A still's grid: `wide` at 2 px cells on the 1,024 px sheet, `narrow` on the 358 px sheet. */
export type HomeAssetVariant = 'wide' | 'narrow';

export type HomeAsset = {
  role: HomeAssetRole;
  /** null for a file both appearances share (a still is a mask in the sheet's ink) */
  appearance: HomeAppearance | null;
  variant: HomeAssetVariant | null;
  /** the served path, content hashed: /home/<role>-<hash>.<ext> */
  path: string;
  bytes: number;
  sha256: string;
  width: number | null;
  height: number | null;
  /** sha256 of the decoded pixels (RGBA, row major); null for a PDF and the glyph sprite */
  pixelsSha256: string | null;
  /** an export picture: sha256 of the part inside the file it was read from */
  partSha256: string | null;
  /** a PDF's page count */
  pages: number | null;
};

export const HOME_ASSETS: readonly HomeAsset[] = [
  {
    role: 'lighthouse-still',
    appearance: null,
    variant: 'wide',
    path: '/home/lighthouse-still-wide-79b80783b6.webp',
    bytes: 4292,
    sha256: '79b80783b699045ab4dfb7dab5b6998e8c2407f12f467e173d2600d34be0c4f9',
    width: 512,
    height: 288,
    pixelsSha256: 'd07aa78f8a9c5d3319eb177c4b7ad796c86beeadc2c7a0d99eacb0c4bdb5040b',
    partSha256: null,
    pages: null,
  },
  {
    role: 'lighthouse-still',
    appearance: null,
    variant: 'narrow',
    path: '/home/lighthouse-still-narrow-c714ece9a4.webp',
    bytes: 672,
    sha256: 'c714ece9a481d4ea0d14d05b811ef2cc679f4bd1fb72546cf430ac7b494b562b',
    width: 179,
    height: 100,
    pixelsSha256: '923479ef228f6ab55403e125eb6ee9693a88e53d29200cd27ba340f171e94c2d',
    partSha256: null,
    pages: null,
  },
  {
    role: 'lighthouse-tone',
    appearance: null,
    variant: null,
    path: '/home/lighthouse-tone-e58fc86d6e.jpg',
    bytes: 12649,
    sha256: 'e58fc86d6efc501471623c54f9b584aaae757fe4a3a4b39e62aecfc552198459',
    width: 512,
    height: 288,
    pixelsSha256: '0b682260e6c30bd9a0f71e8a8dfc544cf5aba8133ea0c5a933277c31a529ee47',
    partSha256: null,
    pages: null,
  },
  {
    role: 'field-still',
    appearance: null,
    variant: 'wide',
    path: '/home/field-still-wide-ce3a434506.webp',
    bytes: 1254,
    sha256: 'ce3a434506d52da2f5524100812ce406f67d2574aa994c1534c9031c99215c65',
    width: 512,
    height: 288,
    pixelsSha256: 'cf58534bc3709f784850c25b957ded89d624aee5d4921c0275c7f1e4b7a07849',
    partSha256: null,
    pages: null,
  },
  {
    role: 'pattern-still',
    appearance: 'light',
    variant: null,
    path: '/home/pattern-still-light-7a43233af0.webp',
    bytes: 1794,
    sha256: '7a43233af029925620fcd96c5df7233b4d2c2bd055931fb51cb23aecf6fa8a96',
    width: 3200,
    height: 1800,
    pixelsSha256: '92db81d32c9669096c712053d5a46ebf1fe0bbe2ba6dd37cd31bd329965d4197',
    partSha256: null,
    pages: null,
  },
  {
    role: 'pattern-still',
    appearance: 'dark',
    variant: null,
    path: '/home/pattern-still-dark-50bd5584fa.webp',
    bytes: 1794,
    sha256: '50bd5584fa5b01a06b0ba2d5dd5eb4a193eedf78849906b0e871d1f98739d4f6',
    width: 3200,
    height: 1800,
    pixelsSha256: 'bc9b3344743459f8a8a1ddcbb7e5834d074c7b43d8dc20f68fa6c8d11129efb2',
    partSha256: null,
    pages: null,
  },
  {
    role: 'pattern-mask',
    appearance: null,
    variant: null,
    path: '/home/pattern-mask-406a3839a2.webp',
    bytes: 1788,
    sha256: '406a3839a2976eb88049dfe076395c7962c3f3ad4cbb4bf88e69420eb3b29e2a',
    width: 3200,
    height: 1800,
    pixelsSha256: 'ee05b93adaed14196dd92cfc6a8ca608db2cbd8e519f4a0c0eeccf76291d9299',
    partSha256: null,
    pages: null,
  },
  {
    role: 'export-browser',
    appearance: 'light',
    variant: null,
    path: '/home/export-browser-light-85c4e76f03.webp',
    bytes: 37722,
    sha256: '85c4e76f033d7197be3a7c6c1045ee08e4c01e713355885974c5069d465a11ee',
    width: 3200,
    height: 1800,
    pixelsSha256: '2d04485ce74cfa3381d2335a36089c353b2da1add576a23c660d7b72c5b3fc0d',
    partSha256: null,
    pages: null,
  },
  {
    role: 'export-browser',
    appearance: 'dark',
    variant: null,
    path: '/home/export-browser-dark-a790262325.webp',
    bytes: 37852,
    sha256: 'a7902623250abea28ac2e0104888bf81c0d9f0c139b1bfe1eeb4e2aab3756989',
    width: 3200,
    height: 1800,
    pixelsSha256: 'e0b3cb35906b92a61ce3bfd89c98098675166a65f28607b679cb0ebf937014ba',
    partSha256: null,
    pages: null,
  },
  {
    role: 'glyphs',
    appearance: null,
    variant: null,
    path: '/home/glyphs-ebf5421cf2.svg',
    bytes: 40131,
    sha256: 'ebf5421cf2d85aa982db2ede5135af7b8ba2d3cf8304d83f3f78a4621227cc25',
    width: null,
    height: null,
    pixelsSha256: null,
    partSha256: null,
    pages: null,
  },
  {
    role: 'export-perfect',
    appearance: 'light',
    variant: null,
    path: '/home/export-perfect-light-3341fd84bb.webp',
    bytes: 35224,
    sha256: '3341fd84bbdf36f78633ac95381d29caa1655ed621920d7e6c243e35735cbfb2',
    width: 3200,
    height: 1800,
    pixelsSha256: '76e849e64a46cc47c066b3e1a0138a992ad71ed453ab836b169b23d103e91b20',
    partSha256: 'e97530537140582eda3f19b192d4517bc34cd24a7d0fff0d616bfc8bc463bd40',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'light',
    variant: null,
    path: '/home/export-editable-light-17811314bf.webp',
    bytes: 2500,
    sha256: '17811314bf0e85744093b08e710f0eabd75f21ed87936fb0ffa63736f58238db',
    width: 1600,
    height: 900,
    pixelsSha256: 'bd381c46928f910925523301af2c534ee8cc854657a383365690f602e6a626a6',
    partSha256: '9a096637364f180880631dfc68bc1f5f2c603617b04dc9cd0347fc9829ce24e5',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'light',
    variant: null,
    path: '/home/export-editable-light-62d608625a.webp',
    bytes: 256,
    sha256: '62d608625a7e5461ac8c776bc725250601b87ad54b8228f58e9c11976db9126a',
    width: 78,
    height: 54,
    pixelsSha256: '12d1f2c09d1e460aafb103b9f302f179e35a07afe98a9cf8029e57cf3e661043',
    partSha256: 'fa7064b5f345ad8a7d3d7eb5d1777ffb8a6434f2059175a96e195cf52760d9c0',
    pages: null,
  },
  {
    role: 'pdf',
    appearance: 'light',
    variant: null,
    path: '/home/pdf-light-651a799f09.pdf',
    bytes: 891016,
    sha256: '651a799f090fcd6d0becdd46465dcdb733d9d69188d798d82db083b9bc1be452',
    width: null,
    height: null,
    pixelsSha256: null,
    partSha256: null,
    pages: 9,
  },
  {
    role: 'export-perfect',
    appearance: 'dark',
    variant: null,
    path: '/home/export-perfect-dark-6c4bf7ea58.webp',
    bytes: 35136,
    sha256: '6c4bf7ea58edf3dc6302d0b7339bfde2f4dec2e0d953ebb72eda45b03c51f340',
    width: 3200,
    height: 1800,
    pixelsSha256: 'a2f9e0c7f8f311b6c63a30103d42c6e4345a96cb15d8b26da9c0a8ddecf36406',
    partSha256: 'fbfe3c52f9bffab479a6fc6334078449de4af96f49050c43bc90ad60c8a64709',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'dark',
    variant: null,
    path: '/home/export-editable-dark-3bab7eaee3.webp',
    bytes: 2500,
    sha256: '3bab7eaee3489d7044962bdd6c9c9b1e182c956c5c9350200f2da603830bfdd9',
    width: 1600,
    height: 900,
    pixelsSha256: '69f7f3959057a84a388f5541d7c33b9c84268272b2bf878cf34ec680233a4b94',
    partSha256: '575999f142d1a49a5348f544d1fe88d80c9a46121a6f45a5a633e6403f061f64',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'dark',
    variant: null,
    path: '/home/export-editable-dark-ec3bf471b9.webp',
    bytes: 254,
    sha256: 'ec3bf471b99b9e918bc7a6319863d3b631ab4c8f96d845b77705852afcbebbdd',
    width: 78,
    height: 54,
    pixelsSha256: '505c37d280cb97a3d18f98cb45690c4c08bef223b654e05e37a81621abf590b3',
    partSha256: '8633cba9c8a1a80ec14a28784f15a3e79e674282dfefa7f28a89e0831226522f',
    pages: null,
  },
  {
    role: 'pdf',
    appearance: 'dark',
    variant: null,
    path: '/home/pdf-dark-884c22b35e.pdf',
    bytes: 896078,
    sha256: '884c22b35ec969b1c2c6fabad104ed9ca53a9a4e93fb581fdf8836cf6157acf6',
    width: null,
    height: null,
    pixelsSha256: null,
    partSha256: null,
    pages: 9,
  },
];

/** The file of a role in an appearance (and a variant); throws when the build has not written it. */
export function homeAsset(
  role: HomeAssetRole,
  appearance: HomeAppearance | null,
  variant: HomeAssetVariant | null = null,
): HomeAsset {
  const found = HOME_ASSETS.find(
    (asset) =>
      asset.role === role &&
      (asset.appearance === null || asset.appearance === appearance) &&
      (variant === null || asset.variant === variant),
  );
  if (found === undefined) throw new RangeError(`no /home asset for ${role} (${appearance})`);
  return found;
}

/** Every file of a role, in the build's order (the Editable text file's pictures by index). */
export function homeAssets(role: HomeAssetRole, appearance: HomeAppearance | null): HomeAsset[] {
  return HOME_ASSETS.filter((asset) => asset.role === role && asset.appearance === appearance);
}
