// Generated by scripts/build-home-assets.ts --stills and --export (docs/LANDING.md 2.6, 2.8, 4.1, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
// assets.json is its JSON twin; assets.test.ts checks every file under public/home/ against it.

export type HomeAppearance = 'light' | 'dark';

/** What a file under public/home/ is (integrator.md section 6, with Kevin's answer 1). */
export type HomeAssetRole =
  /** slide 6's dithered picture (the Louisbourg lighthouse) as a two colour lossless WebP mask, at most 24 KB */
  | 'lighthouse-still'
  /** the lighthouse's tone map, a 512 by 288 grey JPEG, at most 26 KB, one for both appearances */
  | 'lighthouse-tone'
  /** slide 7's dithered picture (the opener field), requested only by the show and the print */
  | 'field-still'
  /** slide 8's still frame: the exporter's capture of the pattern, lossless WebP, at most 48 KB (V4's) */
  | 'pattern-still'
  /** slide 7's picture part from the Perfect file, at most 60 KB */
  | 'export-perfect'
  /** the Editable text file's picture part for slide 7, at most 32 KB */
  | 'export-editable'
  /** the page deck's PDF, 9 pages, requested only on the click of Download the PDF */
  | 'pdf';

/** A still's grid: `wide` at 2 px cells on the 1,024 px sheet, `narrow` on the 358 px sheet. */
export type HomeAssetVariant = 'wide' | 'narrow';

export type HomeAsset = {
  role: HomeAssetRole;
  /** null for a file both appearances share (a still is a mask in the sheet's ink) */
  appearance: HomeAppearance | null;
  variant: HomeAssetVariant | null;
  /** the served path, content hashed: /home/<role>-<hash>.<ext> */
  path: string;
  bytes: number;
  sha256: string;
  width: number | null;
  height: number | null;
  /** sha256 of the decoded pixels (RGBA, row major); null for a PDF */
  pixelsSha256: string | null;
  /** an export picture: sha256 of the part inside the file it was read from */
  partSha256: string | null;
  /** a PDF's page count */
  pages: number | null;
};

export const HOME_ASSETS: readonly HomeAsset[] = [
  {
    role: 'lighthouse-still',
    appearance: null,
    variant: 'wide',
    path: '/home/lighthouse-still-wide-79b80783b6.webp',
    bytes: 4292,
    sha256: '79b80783b699045ab4dfb7dab5b6998e8c2407f12f467e173d2600d34be0c4f9',
    width: 512,
    height: 288,
    pixelsSha256: 'd07aa78f8a9c5d3319eb177c4b7ad796c86beeadc2c7a0d99eacb0c4bdb5040b',
    partSha256: null,
    pages: null,
  },
  {
    role: 'lighthouse-still',
    appearance: null,
    variant: 'narrow',
    path: '/home/lighthouse-still-narrow-c714ece9a4.webp',
    bytes: 672,
    sha256: 'c714ece9a481d4ea0d14d05b811ef2cc679f4bd1fb72546cf430ac7b494b562b',
    width: 179,
    height: 100,
    pixelsSha256: '923479ef228f6ab55403e125eb6ee9693a88e53d29200cd27ba340f171e94c2d',
    partSha256: null,
    pages: null,
  },
  {
    role: 'lighthouse-tone',
    appearance: null,
    variant: null,
    path: '/home/lighthouse-tone-e58fc86d6e.jpg',
    bytes: 12649,
    sha256: 'e58fc86d6efc501471623c54f9b584aaae757fe4a3a4b39e62aecfc552198459',
    width: 512,
    height: 288,
    pixelsSha256: '0b682260e6c30bd9a0f71e8a8dfc544cf5aba8133ea0c5a933277c31a529ee47',
    partSha256: null,
    pages: null,
  },
  {
    role: 'field-still',
    appearance: null,
    variant: 'wide',
    path: '/home/field-still-wide-ce3a434506.webp',
    bytes: 1254,
    sha256: 'ce3a434506d52da2f5524100812ce406f67d2574aa994c1534c9031c99215c65',
    width: 512,
    height: 288,
    pixelsSha256: 'cf58534bc3709f784850c25b957ded89d624aee5d4921c0275c7f1e4b7a07849',
    partSha256: null,
    pages: null,
  },
  {
    role: 'pattern-still',
    appearance: 'light',
    variant: null,
    path: '/home/pattern-still-light-7a43233af0.webp',
    bytes: 1794,
    sha256: '7a43233af029925620fcd96c5df7233b4d2c2bd055931fb51cb23aecf6fa8a96',
    width: 3200,
    height: 1800,
    pixelsSha256: '92db81d32c9669096c712053d5a46ebf1fe0bbe2ba6dd37cd31bd329965d4197',
    partSha256: null,
    pages: null,
  },
  {
    role: 'pattern-still',
    appearance: 'dark',
    variant: null,
    path: '/home/pattern-still-dark-50bd5584fa.webp',
    bytes: 1794,
    sha256: '50bd5584fa5b01a06b0ba2d5dd5eb4a193eedf78849906b0e871d1f98739d4f6',
    width: 3200,
    height: 1800,
    pixelsSha256: 'bc9b3344743459f8a8a1ddcbb7e5834d074c7b43d8dc20f68fa6c8d11129efb2',
    partSha256: null,
    pages: null,
  },
  {
    role: 'export-perfect',
    appearance: 'light',
    variant: null,
    path: '/home/export-perfect-light-c2b3ddbf8d.webp',
    bytes: 35506,
    sha256: 'c2b3ddbf8d116a7cc9508a0fc851f3b8df67e7087a2edcfe6241f5cecf5f38ac',
    width: 3200,
    height: 1800,
    pixelsSha256: 'f6400b90962b644c122c022ef4bf89f1db30cbbdded70726b8910453840a28cd',
    partSha256: 'fb24c9f9739332814b6069f9d642a130b45700ffa4434eb57e5fd83fe8b2e91e',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'light',
    variant: null,
    path: '/home/export-editable-light-17811314bf.webp',
    bytes: 2500,
    sha256: '17811314bf0e85744093b08e710f0eabd75f21ed87936fb0ffa63736f58238db',
    width: 1600,
    height: 900,
    pixelsSha256: 'bd381c46928f910925523301af2c534ee8cc854657a383365690f602e6a626a6',
    partSha256: '9a096637364f180880631dfc68bc1f5f2c603617b04dc9cd0347fc9829ce24e5',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'light',
    variant: null,
    path: '/home/export-editable-light-01bf1d837d.webp',
    bytes: 392,
    sha256: '01bf1d837d2dde161fad42e6ab739017b77b98a6ca0f5bf30b172c957204f189',
    width: 84,
    height: 54,
    pixelsSha256: 'c23609a5167479adb49a863a1547a0ffce9a2ca3a75a707f109b7a124a60433c',
    partSha256: '35a6782a2b9702283cb2c83286f01418536c37e61201c4f1faac6af9a6a21caf',
    pages: null,
  },
  {
    role: 'pdf',
    appearance: 'light',
    variant: null,
    path: '/home/pdf-light-6f207f1381.pdf',
    bytes: 895057,
    sha256: '6f207f138141db34e0699a570e5748c520cf522e60538e5124dfcb0a8767c63d',
    width: null,
    height: null,
    pixelsSha256: null,
    partSha256: null,
    pages: 9,
  },
  {
    role: 'export-perfect',
    appearance: 'dark',
    variant: null,
    path: '/home/export-perfect-dark-51b954599c.webp',
    bytes: 35192,
    sha256: '51b954599c6e1880013d20e87ee38cc5ed778c5328802053957693ea154bbf37',
    width: 3200,
    height: 1800,
    pixelsSha256: '2f2fd7c1070013a8b530004a54ee0edf3587ab837487fc7cb72d492921577bd9',
    partSha256: 'c73b77ee4865b6b393e6b08d426d177eab7efd915ff94b00030cbbfca0bd3b43',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'dark',
    variant: null,
    path: '/home/export-editable-dark-3bab7eaee3.webp',
    bytes: 2500,
    sha256: '3bab7eaee3489d7044962bdd6c9c9b1e182c956c5c9350200f2da603830bfdd9',
    width: 1600,
    height: 900,
    pixelsSha256: '69f7f3959057a84a388f5541d7c33b9c84268272b2bf878cf34ec680233a4b94',
    partSha256: '575999f142d1a49a5348f544d1fe88d80c9a46121a6f45a5a633e6403f061f64',
    pages: null,
  },
  {
    role: 'export-editable',
    appearance: 'dark',
    variant: null,
    path: '/home/export-editable-dark-01bf1d837d.webp',
    bytes: 392,
    sha256: '01bf1d837d2dde161fad42e6ab739017b77b98a6ca0f5bf30b172c957204f189',
    width: 84,
    height: 54,
    pixelsSha256: 'c23609a5167479adb49a863a1547a0ffce9a2ca3a75a707f109b7a124a60433c',
    partSha256: '35a6782a2b9702283cb2c83286f01418536c37e61201c4f1faac6af9a6a21caf',
    pages: null,
  },
  {
    role: 'pdf',
    appearance: 'dark',
    variant: null,
    path: '/home/pdf-dark-a8aa63f53d.pdf',
    bytes: 900126,
    sha256: 'a8aa63f53d53cdc5f96f3749b74bb38d642988b36f1e9b908fdd3d59d27945c9',
    width: null,
    height: null,
    pixelsSha256: null,
    partSha256: null,
    pages: 9,
  },
];

/** The file of a role in an appearance (and a variant); throws when the build has not written it. */
export function homeAsset(
  role: HomeAssetRole,
  appearance: HomeAppearance | null,
  variant: HomeAssetVariant | null = null,
): HomeAsset {
  const found = HOME_ASSETS.find(
    (asset) =>
      asset.role === role &&
      (asset.appearance === null || asset.appearance === appearance) &&
      (variant === null || asset.variant === variant),
  );
  if (found === undefined) throw new RangeError(`no /home asset for ${role} (${appearance})`);
  return found;
}

/** Every file of a role, in the build's order (the Editable text file's pictures by index). */
export function homeAssets(role: HomeAssetRole, appearance: HomeAppearance | null): HomeAsset[] {
  return HOME_ASSETS.filter((asset) => asset.role === role && asset.appearance === appearance);
}
