// Generated by scripts/build-home-assets.ts --stills and --export (docs/LANDING.md 2.6, 2.8, 4.1, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
// assets.json holds every file's whole record; assets.test.ts and the check read every file under
// public/home/ against it, and this module keeps what the page draws with.

export type HomeAppearance = 'light' | 'dark';

/** What a file under public/home/ is (integrator.md section 6, with Kevin's answer 1). */
export type HomeAssetRole =
  /** slide 6's dithered picture (the Louisbourg lighthouse) as a two colour lossless WebP mask, at most 24 KB */
  | 'lighthouse-still'
  /** the lighthouse's tone map, a 512 by 288 grey JPEG, at most 26 KB, one for both appearances */
  | 'lighthouse-tone'
  /** slide 7's dithered picture (the opener field), requested only by the show and the print */
  | 'field-still'
  /** slide 8's still frame: the exporter's capture of the pattern, lossless WebP, at most 48 KB (V4's) */
  | 'pattern-still'
  /** the still frame's dots as one mask for both appearances, which the show, the print and the miniature draw in the slide's ink, at most 48 KB */
  | 'pattern-mask'
  /** slide 7's picture part from the Perfect file, at most 60 KB */
  | 'export-perfect'
  /** the Editable text file's picture part for slide 7, at most 32 KB */
  | 'export-editable'
  /** the CLI's browser render of slide 7 at scale 2, lossless WebP, at most 60 KB (the loupe, V3's) */
  | 'export-browser'
  /** the page deck's PDF, 9 pages, requested only on the click of Download the PDF */
  | 'pdf'
  /** the glyphs below the first screen: one SVG sprite of icons.tsx's symbols (scripts/home/sprite.ts), at most 48 KB */
  | 'glyphs'
  /** the Present band's figure: the product's presenter view of the page deck (scripts/home/capture.ts), at most 25 KB at x1 and 60 KB at x2 */
  | 'presenter'
  /** the export band's figure: the editor's Download dialog on the page deck (scripts/home/capture.ts), at most 20 KB at x1 and 40 KB at x2 */
  | 'download-dialog'
  /** a card of the patterns band: a still of the editor's Insert > Animated pattern gallery, at most 12 KB */
  | 'pattern-card';

/** A still's grid: `wide` at 2 px cells on the 1,024 px sheet, `narrow` on the 358 px sheet; a figure's `x1` and `x2` files. */
export type HomeAssetVariant = 'wide' | 'narrow' | 'x1' | 'x2';

/**
 * A served file as the page reads it. assets.json holds each file's whole record (its bytes,
 * sha256, decoded pixels, part and pages), which the build's check, assets.test.ts and the rows
 * read; the page's script carries only what it draws with.
 */
export type HomeAsset = {
  role: HomeAssetRole;
  /** null for a file both appearances share (a still is a mask in the sheet's ink) */
  appearance: HomeAppearance | null;
  variant: HomeAssetVariant | null;
  /** the served path, content hashed: /home/<role>-<hash>.<ext> */
  path: string;
  width: number | null;
  height: number | null;
};

export const HOME_ASSETS: readonly HomeAsset[] = [
  {
    role: 'lighthouse-still',
    appearance: null,
    variant: 'wide',
    path: '/home/lighthouse-still-wide-79b80783b6.webp',
    width: 512,
    height: 288,
  },
  {
    role: 'lighthouse-still',
    appearance: null,
    variant: 'narrow',
    path: '/home/lighthouse-still-narrow-c714ece9a4.webp',
    width: 179,
    height: 100,
  },
  {
    role: 'lighthouse-tone',
    appearance: null,
    variant: null,
    path: '/home/lighthouse-tone-e58fc86d6e.jpg',
    width: 512,
    height: 288,
  },
  {
    role: 'field-still',
    appearance: null,
    variant: 'wide',
    path: '/home/field-still-wide-ce3a434506.webp',
    width: 512,
    height: 288,
  },
  {
    role: 'pattern-still',
    appearance: 'light',
    variant: null,
    path: '/home/pattern-still-light-7a43233af0.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'pattern-still',
    appearance: 'dark',
    variant: null,
    path: '/home/pattern-still-dark-50bd5584fa.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'pattern-mask',
    appearance: null,
    variant: null,
    path: '/home/pattern-mask-406a3839a2.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'export-browser',
    appearance: 'light',
    variant: null,
    path: '/home/export-browser-light-85c4e76f03.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'export-browser',
    appearance: 'dark',
    variant: null,
    path: '/home/export-browser-dark-a790262325.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'glyphs',
    appearance: null,
    variant: null,
    path: '/home/glyphs-9b32b6f55a.svg',
    width: null,
    height: null,
  },
  {
    role: 'presenter',
    appearance: 'light',
    variant: 'x1',
    path: '/home/presenter-light-x1-263f415b1e.webp',
    width: 1024,
    height: 640,
  },
  {
    role: 'presenter',
    appearance: 'light',
    variant: 'x2',
    path: '/home/presenter-light-x2-3fa0913544.webp',
    width: 2048,
    height: 1280,
  },
  {
    role: 'presenter',
    appearance: 'dark',
    variant: 'x1',
    path: '/home/presenter-dark-x1-fe5de5928a.webp',
    width: 1024,
    height: 640,
  },
  {
    role: 'presenter',
    appearance: 'dark',
    variant: 'x2',
    path: '/home/presenter-dark-x2-25654610f2.webp',
    width: 2048,
    height: 1280,
  },
  {
    role: 'download-dialog',
    appearance: 'light',
    variant: 'x1',
    path: '/home/download-dialog-light-x1-a0779cb05f.webp',
    width: 544,
    height: 499,
  },
  {
    role: 'download-dialog',
    appearance: 'light',
    variant: 'x2',
    path: '/home/download-dialog-light-x2-fd9cbe5b45.webp',
    width: 1088,
    height: 998,
  },
  {
    role: 'download-dialog',
    appearance: 'dark',
    variant: 'x1',
    path: '/home/download-dialog-dark-x1-0cb1087ea4.webp',
    width: 544,
    height: 499,
  },
  {
    role: 'download-dialog',
    appearance: 'dark',
    variant: 'x2',
    path: '/home/download-dialog-dark-x2-496b82f5c2.webp',
    width: 1088,
    height: 998,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-f9f953be25.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-d98f6d47d0.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-74f114db66.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-196583cccc.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-b878423966.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-c83f50d859.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-d7dc077496.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-3ac0ab4a76.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-96dc3052e7.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-fcac76ec6c.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-9a9254e722.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-b44ca6bdc9.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-b31ba02f07.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-33f038a932.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-ed481b7f42.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-09b55fe4c9.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'pattern-card',
    appearance: null,
    variant: null,
    path: '/home/pattern-card-6c6e0954dc.webp',
    width: 320,
    height: 200,
  },
  {
    role: 'export-perfect',
    appearance: 'light',
    variant: null,
    path: '/home/export-perfect-light-3341fd84bb.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'export-editable',
    appearance: 'light',
    variant: null,
    path: '/home/export-editable-light-17811314bf.webp',
    width: 1600,
    height: 900,
  },
  {
    role: 'export-editable',
    appearance: 'light',
    variant: null,
    path: '/home/export-editable-light-62d608625a.webp',
    width: 78,
    height: 54,
  },
  {
    role: 'pdf',
    appearance: 'light',
    variant: null,
    path: '/home/pdf-light-651a799f09.pdf',
    width: null,
    height: null,
  },
  {
    role: 'export-perfect',
    appearance: 'dark',
    variant: null,
    path: '/home/export-perfect-dark-6c4bf7ea58.webp',
    width: 3200,
    height: 1800,
  },
  {
    role: 'export-editable',
    appearance: 'dark',
    variant: null,
    path: '/home/export-editable-dark-3bab7eaee3.webp',
    width: 1600,
    height: 900,
  },
  {
    role: 'export-editable',
    appearance: 'dark',
    variant: null,
    path: '/home/export-editable-dark-ec3bf471b9.webp',
    width: 78,
    height: 54,
  },
  {
    role: 'pdf',
    appearance: 'dark',
    variant: null,
    path: '/home/pdf-dark-884c22b35e.pdf',
    width: null,
    height: null,
  },
];

/** The file of a role in an appearance (and a variant); throws when the build has not written it. */
export function homeAsset(
  role: HomeAssetRole,
  appearance: HomeAppearance | null,
  variant: HomeAssetVariant | null = null,
): HomeAsset {
  const found = HOME_ASSETS.find(
    (asset) =>
      asset.role === role &&
      (asset.appearance === null || asset.appearance === appearance) &&
      (variant === null || asset.variant === variant),
  );
  if (found === undefined) throw new RangeError(`no /home asset for ${role} (${appearance})`);
  return found;
}

/** Every file of a role, in the build's order (the Editable text file's pictures by index). */
export function homeAssets(role: HomeAssetRole, appearance: HomeAppearance | null): HomeAsset[] {
  return HOME_ASSETS.filter((asset) => asset.role === role && asset.appearance === appearance);
}
