// Generated by scripts/build-home-assets.ts --slides (docs/LANDING.md 2.0, 4.2, 6.1, 6.3); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The bands below the first screen (docs/LANDING.md 2.0 "Slides", 4.2): the types of their
// generated markup. The markup itself is one module per band chunk under `bands/`, imported only
// by that band's chunk, never by the route or the core, so the document and the route chunk carry
// none of it: `bands/<band>.generated.ts` (`FILLS`) for canvas, tailor, agents, people, present, export, patterns, close; `bands/deck.generated.ts`
// (the nine slides once, for the bands that place their own copies); `bands/live.generated.ts`
// (the show's slide 7 and slide 5's two earlier states). Each band's reserved box
// (`[data-reserve="<band>"]`) holds empty placeholders `[data-fill="<key>"]`, which the band loader
// writes from its chunk's `FILLS[key]` before the band starts.

/** The bands whose reserved box the build fills (docs/LANDING.md 6.3). */
export type HomeBandId =
  'canvas' | 'tailor' | 'agents' | 'people' | 'present' | 'export' | 'patterns' | 'close';

/** A band's placeholders by their `data-fill` key: the renderer's markup for each. */
export type BandFills = Readonly<Record<string, string>>;

export type LiveSlides = {
  /** slide 7, the opener field's slide, for the show and the print */
  field: string;
  /** slide 5 after step 1 (the layout's placeholders) and after step 2 (the title written) */
  nextSteps: { placeholders: string; titled: string };
};
