// Generated by scripts/build-home-assets.ts --boot (docs/LANDING.md 3.2, 4.1, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// `BOOT_SCRIPT` is `bootSource(HERO.visit)` of src/components/home/boot.ts (V4's) minified by the
// minifier Vite carries (scripts/home/boot.ts); src/routes/home.tsx inlines it as the first child of
// main#top. At most 1,000 bytes minified, and it reads no layout.

/** The minified boot script. */
export const BOOT_SCRIPT: string =
  '(function(e){let t=document,n=t.documentElement,r=n.dataset,i=`paused`,a=`ts-home-motion`,o=`ts-home-visit`,s=e.s.length,c=0;try{c=+localStorage[o]%s||0,localStorage[o]=(c+1)%s,localStorage[a]==i&&(r.motion=i)}catch{}let l={ended:matchMedia(`(prefers-reduced-motion:reduce)`).matches||r.motion==i,end:u};window.tsHomeBoot=l,l.ended||(n.classList.add(`ts-intro`),setTimeout(u,3e3));function u(){l.ended=!0,n.classList.remove(`ts-intro`)}t.addEventListener(`click`,e=>{let t=e.target.closest?.(`[data-motion-toggle]`);if(!t)return;let n=r.motion!=i;n?(r.motion=i,u()):delete r.motion,t.ariaPressed=`${n}`;try{n?localStorage[a]=i:delete localStorage[a]}catch{}});function d(){let n=t.querySelector(`[data-visit]`);return n?(l.t0=performance.now(),c&&(n.textContent=e.s[c]+n.textContent.slice(e.n)),0):t.readyState>`l`&&requestAnimationFrame(d)}requestAnimationFrame(d)})({s:[``,`Turboslide puts one customer name on every slide.`,`Turboslide downloads PDF and PowerPoint files.`],n:45});';

/** sha256 of BOOT_SCRIPT, checked by `build-home-assets.ts --check` */
export const BOOT_SHA256: string =
  'dd5f5495a99ca5245e1f40132ea9242631683fb632995eff45b29e6223b625e2';
