// Generated by scripts/build-home-assets.ts --boot from src/components/home/boot.ts and the three
// visit sentences of copy.ts (docs/LANDING.md 2.2, 3.2 H2 to H4, 6.1); never edited by hand. Day 0
// stub: the integrator wrote the types and placeholder values on day 0
// (docs/gslides-parity/landing/build/integrator.md "Landing, day 0", section 4.2); L4 writes the
// boot script and L1's build writes the values.
//
// `BOOT_SCRIPT` is inlined by src/routes/home.tsx the way __root.tsx inlines
// APPEARANCE_BOOT_SCRIPT, at most 1.5 KB minified, and reads no layout.

/** One visit sentence's typing clock (H3): a person's uneven rhythm from the build's gap table. */
export type GapTable = {
  sentence: string;
  /** the gap before each key in ms, 34 to 60, plus 30 after a space */
  gapsMs: readonly number[];
  /** the last key's time from T0: 700 ms plus the gaps; at most 3,970 ms (row home.motion.hero) */
  lastKeyMs: number;
};

/** The minified boot script; '' until L4's boot.ts and L1's build land. */
export const BOOT_SCRIPT: string = '';

/** sha256 of BOOT_SCRIPT, checked by `build-home-assets.ts --check` */
export const BOOT_SHA256: string = '';

/** The three sentences' tables in visit order (answer 9); empty until the build writes them. */
export const VISIT_GAPS: readonly GapTable[] = [];
