// Generated by scripts/home/run.ts (docs/LANDING.md 2.2, 2.9, 6.1); never edited by hand.
// node scripts/home/run.ts --check compares this file with its sources.
//
// The agents band's chips and typed forms and the hero's staged loop, every command and answer
// recorded from the CLI by `scripts/home/run.ts --record` under apps/studio/home-deck/recorded-chips/.
// Each answer is a write's summary line as the CLI printed it on the page deck at rest; the build
// recorded every chip on the deck after each other chip as well and proved the answers differ only
// in the revision (and, once slide 5 is arranged by hand, in the finding count, `answerFreeform`).
// The page substitutes the customer's name and the page deck's revision, nothing else.

export type ChipId = 'tailor' | 'turn' | 'row' | 'skip';

export type StepLanding =
  | { kind: 'cut' }
  | { kind: 'rails' }
  | { kind: 'words'; chars: number }
  | { kind: 'rows'; count: number }
  | { kind: 'names' }
  | { kind: 'turn'; degrees: number }
  | { kind: 'mark' };

/** A step's scheduled lengths in ms with the fixture's name (LANDING.md 3.4 L-H, 3.6 A1 to A6). */
export type StepSchedule = {
  type: number;
  answer: number;
  beat: number;
  ring: number;
  land: number;
  flag: number;
  total: number;
};

/** One step of the hero's staged loop (2.2): Restore, then the run's three writes. */
export type LoopStep = {
  id: 'restore' | 'new' | 'title' | 'rows';
  /** the command as the terminal prints it, with the fixture's name */
  command: string;
  /** the characters typed at 24 ms (A1); the rest, a quoted value, prints whole one frame later */
  typedChars: number;
  answer: readonly string[];
  /** where the ring travels; null for Restore (no ring) */
  target: 'next-steps' | 'next-steps#h' | 'next-steps#rows' | null;
  landing: StepLanding;
  schedule: StepSchedule;
};

export type ChipRequest = {
  mcp: { name: string; arguments: Readonly<Record<string, unknown>> };
  http: { method: 'POST'; path: string; body: Readonly<Record<string, unknown>> };
};

/** One chip's command in one direction (`on`: the chip's label; `off`: the label it reads after). */
export type ChipCommand = ChipRequest & {
  chip: ChipId;
  dir: 'on' | 'off';
  action: 'deck.tailor' | 'block.rotate' | 'block.set' | 'slide.skip';
  argv: readonly string[];
  command: string;
  typedChars: number;
  /** the summary line at rest, its revision `revision` */
  answer: readonly string[];
  /** the summary line once slide 5 is arranged by hand, where its finding count differs; null when the same */
  answerFreeform: readonly string[] | null;
  revision: number;
  /** the names of a tailor command, which the page replaces with the deck's */
  names: { from: string; to: string } | null;
  target: 'next-steps' | 'next-steps#h' | 'next-steps#rows';
  /** the rows block's item the row chip writes */
  row: number | null;
  landing: StepLanding;
  schedule: StepSchedule;
};

/** A line of `version list` (apps/cli/src/commands/version.ts `formatVersion`). */
export type VersionFact = {
  n: number;
  revision: number;
  createdAt: string;
  author: string;
  what: string;
};

export type HomeChips = {
  deckTitle: string;
  customer: string;
  chipCustomer: string;
  /** the page deck's revision at rest (the run's third write) */
  restRevision: number;
  turnTo: number;
  row: { index: number; before: string; after: string };
  commands: Readonly<Record<ChipId, { on: ChipCommand; off: ChipCommand }>>;
  /** each chip's answer on the deck before the run (slide 5 absent): tailor runs, the others are refused */
  absent: Readonly<
    Record<ChipId, { refused: boolean; on: readonly string[]; off: readonly string[] | null }>
  >;
  /** the recorded versions: the save before the run and the run's three writes */
  versions: readonly VersionFact[];
  versionList: { command: string; authorAgent: string };
  restore: ChipRequest & { absent: readonly string[] };
  list: ChipRequest;
  /** `tailor --replace=<a name the deck does not hold>=<to>` */
  tailorAbsent: readonly string[];
  tailorCounts: {
    start: { places: number; slides: number };
    rest: { places: number; slides: number };
  };
  help: readonly string[];
  cliCommands: number;
  refusal: string;
  /** the editor's skipped slide glyph, Heroicons 20 solid `eye-slash` from the theme's sprite */
  skipGlyph: { viewBox: string; body: string };
};

export type HomeLoop = {
  steps: readonly LoopStep[];
  holdFirstMs: number;
  holdLastMs: number;
  /** a cycle's length: the holds and the four steps (the caption's figure, rounded) */
  cycleMs: number;
  captionSeconds: number;
};

export const HOME_CHIPS: HomeChips = {
  deckTitle: 'Onboarding plan',
  customer: 'Northwind',
  chipCustomer: 'Initech',
  restRevision: 3,
  turnTo: 8,
  row: {
    index: 2,
    before: 'The first call uses this deck',
    after: 'The first call uses this deck and its notes',
  },
  commands: {
    tailor: {
      on: {
        chip: 'tailor',
        dir: 'on',
        action: 'deck.tailor',
        argv: ['tailor', '--replace=Northwind=Initech'],
        command: 'turboslide tailor --replace=Northwind=Initech',
        typedChars: 45,
        answer: ['13 replacements on 6 slides, 0 pictures swapped, 0 skipped; revision 4'],
        answerFreeform: null,
        revision: 4,
        names: {
          from: 'Northwind',
          to: 'Initech',
        },
        mcp: {
          name: 'deck_tailor',
          arguments: {
            replacements: [
              {
                from: 'Northwind',
                to: 'Initech',
              },
            ],
            baseRevision: 3,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/deck.tailor',
          body: {
            replacements: [
              {
                from: 'Northwind',
                to: 'Initech',
              },
            ],
            baseRevision: 3,
          },
        },
        target: 'next-steps#h',
        row: null,
        landing: {
          kind: 'names',
        },
        schedule: {
          type: 1080,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 0,
          flag: 960,
          total: 3560,
        },
      },
      off: {
        chip: 'tailor',
        dir: 'off',
        action: 'deck.tailor',
        argv: ['tailor', '--replace=Initech=Northwind'],
        command: 'turboslide tailor --replace=Initech=Northwind',
        typedChars: 45,
        answer: ['13 replacements on 6 slides, 0 pictures swapped, 0 skipped; revision 5'],
        answerFreeform: null,
        revision: 5,
        names: {
          from: 'Initech',
          to: 'Northwind',
        },
        mcp: {
          name: 'deck_tailor',
          arguments: {
            replacements: [
              {
                from: 'Initech',
                to: 'Northwind',
              },
            ],
            baseRevision: 4,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/deck.tailor',
          body: {
            replacements: [
              {
                from: 'Initech',
                to: 'Northwind',
              },
            ],
            baseRevision: 4,
          },
        },
        target: 'next-steps#h',
        row: null,
        landing: {
          kind: 'names',
        },
        schedule: {
          type: 1080,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 0,
          flag: 960,
          total: 3560,
        },
      },
    },
    turn: {
      on: {
        chip: 'turn',
        dir: 'on',
        action: 'block.rotate',
        argv: ['block', 'rotate', 'next-steps#h', '--to', '8'],
        command: 'turboslide block rotate next-steps#h --to 8',
        typedChars: 43,
        answer: ['rotated h to 8 degrees on next-steps: revision 4, 3 finding(s)'],
        answerFreeform: null,
        revision: 4,
        names: null,
        mcp: {
          name: 'deck_rotate_block',
          arguments: {
            slideId: 'next-steps',
            blockIds: ['h'],
            to: 8,
            baseRevision: 3,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/block.rotate',
          body: {
            slideId: 'next-steps',
            blockIds: ['h'],
            to: 8,
            baseRevision: 3,
          },
        },
        target: 'next-steps#h',
        row: null,
        landing: {
          kind: 'turn',
          degrees: 8,
        },
        schedule: {
          type: 1032,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 700,
          flag: 960,
          total: 3512,
        },
      },
      off: {
        chip: 'turn',
        dir: 'off',
        action: 'block.rotate',
        argv: ['block', 'rotate', 'next-steps#h', '--to', '0'],
        command: 'turboslide block rotate next-steps#h --to 0',
        typedChars: 43,
        answer: ['rotated h to 0 degrees on next-steps: revision 5, 3 finding(s)'],
        answerFreeform: null,
        revision: 5,
        names: null,
        mcp: {
          name: 'deck_rotate_block',
          arguments: {
            slideId: 'next-steps',
            blockIds: ['h'],
            to: 0,
            baseRevision: 4,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/block.rotate',
          body: {
            slideId: 'next-steps',
            blockIds: ['h'],
            to: 0,
            baseRevision: 4,
          },
        },
        target: 'next-steps#h',
        row: null,
        landing: {
          kind: 'turn',
          degrees: 0,
        },
        schedule: {
          type: 1032,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 700,
          flag: 960,
          total: 3512,
        },
      },
    },
    row: {
      on: {
        chip: 'row',
        dir: 'on',
        action: 'block.set',
        argv: [
          'block',
          'set',
          'next-steps#rows',
          '/items/2/value',
          'The first call uses this deck and its notes',
        ],
        command:
          'turboslide block set next-steps#rows /items/2/value "The first call uses this deck and its notes"',
        typedChars: 51,
        answer: ['set rows /items/2/value on next-steps: revision 4, 2 finding(s)'],
        answerFreeform: ['set rows /items/2/value on next-steps: revision 4, 3 finding(s)'],
        revision: 4,
        names: null,
        mcp: {
          name: 'deck_update_block',
          arguments: {
            slideId: 'next-steps',
            blockId: 'rows',
            path: '/items/2/value',
            value: 'The first call uses this deck and its notes',
            baseRevision: 3,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/block.set',
          body: {
            slideId: 'next-steps',
            blockId: 'rows',
            path: '/items/2/value',
            value: 'The first call uses this deck and its notes',
            baseRevision: 3,
          },
        },
        target: 'next-steps#rows',
        row: 2,
        landing: {
          kind: 'words',
          chars: 43,
        },
        schedule: {
          type: 1224,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 1032,
          flag: 960,
          total: 4036,
        },
      },
      off: {
        chip: 'row',
        dir: 'off',
        action: 'block.set',
        argv: [
          'block',
          'set',
          'next-steps#rows',
          '/items/2/value',
          'The first call uses this deck',
        ],
        command:
          'turboslide block set next-steps#rows /items/2/value "The first call uses this deck"',
        typedChars: 51,
        answer: ['set rows /items/2/value on next-steps: revision 5, 2 finding(s)'],
        answerFreeform: ['set rows /items/2/value on next-steps: revision 5, 3 finding(s)'],
        revision: 5,
        names: null,
        mcp: {
          name: 'deck_update_block',
          arguments: {
            slideId: 'next-steps',
            blockId: 'rows',
            path: '/items/2/value',
            value: 'The first call uses this deck',
            baseRevision: 4,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/block.set',
          body: {
            slideId: 'next-steps',
            blockId: 'rows',
            path: '/items/2/value',
            value: 'The first call uses this deck',
            baseRevision: 4,
          },
        },
        target: 'next-steps#rows',
        row: 2,
        landing: {
          kind: 'words',
          chars: 29,
        },
        schedule: {
          type: 1224,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 696,
          flag: 960,
          total: 3704,
        },
      },
    },
    skip: {
      on: {
        chip: 'skip',
        dir: 'on',
        action: 'slide.skip',
        argv: ['slide', 'skip', 'next-steps'],
        command: 'turboslide slide skip next-steps',
        typedChars: 32,
        answer: ['skipped next-steps: revision 4'],
        answerFreeform: null,
        revision: 4,
        names: null,
        mcp: {
          name: 'deck_skip_slide',
          arguments: {
            slideIds: ['next-steps'],
            skip: true,
            baseRevision: 3,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/slide.skip',
          body: {
            slideIds: ['next-steps'],
            skip: true,
            baseRevision: 3,
          },
        },
        target: 'next-steps',
        row: null,
        landing: {
          kind: 'mark',
        },
        schedule: {
          type: 768,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 0,
          flag: 960,
          total: 3248,
        },
      },
      off: {
        chip: 'skip',
        dir: 'off',
        action: 'slide.skip',
        argv: ['slide', 'skip', 'next-steps', '--off'],
        command: 'turboslide slide skip next-steps --off',
        typedChars: 38,
        answer: ['showing next-steps: revision 5'],
        answerFreeform: null,
        revision: 5,
        names: null,
        mcp: {
          name: 'deck_skip_slide',
          arguments: {
            slideIds: ['next-steps'],
            skip: false,
            baseRevision: 4,
          },
        },
        http: {
          method: 'POST',
          path: '/api/actions/slide.skip',
          body: {
            slideIds: ['next-steps'],
            skip: false,
            baseRevision: 4,
          },
        },
        target: 'next-steps',
        row: null,
        landing: {
          kind: 'mark',
        },
        schedule: {
          type: 912,
          answer: 320,
          beat: 500,
          ring: 700,
          land: 0,
          flag: 960,
          total: 3392,
        },
      },
    },
  },
  absent: {
    tailor: {
      refused: false,
      on: ['11 replacements on 5 slides, 0 pictures swapped, 0 skipped; revision 1'],
      off: ['11 replacements on 5 slides, 0 pictures swapped, 0 skipped; revision 2'],
    },
    turn: {
      refused: true,
      on: ['turboslide: No slide "next-steps"'],
      off: null,
    },
    row: {
      refused: true,
      on: ['turboslide: mutation 0 (block.set): No slide "next-steps"'],
      off: null,
    },
    skip: {
      refused: true,
      on: ['turboslide: No slide "next-steps"'],
      off: null,
    },
  },
  versions: [
    {
      n: 1,
      revision: 0,
      createdAt: '2026-10-03T18:19:31.770Z',
      author: 'agent:landing',
      what: '"Onboarding plan"',
    },
    {
      n: 2,
      revision: 1,
      createdAt: '2026-10-03T18:19:35.353Z',
      author: 'agent:landing',
      what: '1 mutation(s): slide.insert',
    },
    {
      n: 3,
      revision: 2,
      createdAt: '2026-10-03T18:19:38.768Z',
      author: 'agent:landing',
      what: '1 mutation(s): block.set',
    },
    {
      n: 4,
      revision: 3,
      createdAt: '2026-10-03T18:19:42.044Z',
      author: 'agent:landing',
      what: '1 mutation(s): block.set',
    },
  ],
  versionList: {
    command: 'turboslide version list',
    authorAgent: 'agent:landing',
  },
  restore: {
    mcp: {
      name: 'deck_version_restore',
      arguments: {
        n: 1,
        baseRevision: 3,
      },
    },
    http: {
      method: 'POST',
      path: '/api/actions/version.restore',
      body: {
        n: 1,
        baseRevision: 3,
      },
    },
    absent: ['turboslide: mutation 0 (version.restore): No version 9 in the log'],
  },
  list: {
    mcp: {
      name: 'deck_version_list',
      arguments: {},
    },
    http: {
      method: 'POST',
      path: '/api/actions/version.list',
      body: {},
    },
  },
  tailorAbsent: ['0 replacements on 0 slides, 0 pictures swapped, 0 skipped; revision 3'],
  tailorCounts: {
    start: {
      places: 11,
      slides: 5,
    },
    rest: {
      places: 13,
      slides: 6,
    },
  },
  help: [
    'This page runs these six commands.',
    'turboslide tailor --replace=<from>=<to>',
    'turboslide block rotate next-steps#h --to 8',
    'turboslide block set next-steps#rows /items/2/value "<text>"',
    'turboslide slide skip next-steps',
    'turboslide version list',
    'turboslide version restore <n>',
  ],
  cliCommands: 180,
  refusal: "This page runs 6 of the CLI's 180 commands.",
  skipGlyph: {
    viewBox: '0 0 20 20',
    body: '<path fill-rule="evenodd" d="M3.28 2.22a.75.75 0 0 0-1.06 1.06l14.5 14.5a.75.75 0 1 0 1.06-1.06l-1.745-1.745a10.029 10.029 0 0 0 3.3-4.38 1.651 1.651 0 0 0 0-1.185A10.004 10.004 0 0 0 9.999 3a9.956 9.956 0 0 0-4.744 1.194L3.28 2.22ZM7.752 6.69l1.092 1.092a2.5 2.5 0 0 1 3.374 3.373l1.091 1.092a4 4 0 0 0-5.557-5.557Z" clip-rule="evenodd"/> <path d="m10.748 13.93 2.523 2.523a9.987 9.987 0 0 1-3.27.547c-4.258 0-7.894-2.66-9.337-6.41a1.651 1.651 0 0 1 0-1.186A10.007 10.007 0 0 1 2.839 6.02L6.07 9.252a4 4 0 0 0 4.678 4.678Z"/>',
  },
};

export const HOME_LOOP: HomeLoop = {
  steps: [
    {
      id: 'restore',
      command: 'turboslide version restore 1',
      typedChars: 28,
      answer: ['restored version 1: revision 4'],
      target: null,
      landing: {
        kind: 'cut',
      },
      schedule: {
        type: 672,
        answer: 320,
        beat: 500,
        ring: 0,
        land: 0,
        flag: 960,
        total: 2452,
      },
    },
    {
      id: 'new',
      command: 'turboslide slide new --layout rows --after ships --id next-steps',
      typedChars: 64,
      answer: ['new rows slide next-steps after ships: revision 5'],
      target: 'next-steps',
      landing: {
        kind: 'rails',
      },
      schedule: {
        type: 1536,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 780,
        flag: 960,
        total: 4096,
      },
    },
    {
      id: 'title',
      command: 'turboslide block set next-steps#h /text "Next steps with Northwind"',
      typedChars: 67,
      answer: ['set h /text on next-steps: revision 6, 8 finding(s)'],
      target: 'next-steps#h',
      landing: {
        kind: 'words',
        chars: 25,
      },
      schedule: {
        type: 1608,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 600,
        flag: 960,
        total: 4088,
      },
    },
    {
      id: 'rows',
      command:
        'turboslide block set next-steps#rows /items \'[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]\'',
      typedChars: 43,
      answer: ['set rows /items on next-steps: revision 7, 2 finding(s)'],
      target: 'next-steps#rows',
      landing: {
        kind: 'rows',
        count: 3,
      },
      schedule: {
        type: 1032,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 270,
        flag: 960,
        total: 3512,
      },
    },
  ],
  holdFirstMs: 3000,
  holdLastMs: 2000,
  cycleMs: 19148,
  captionSeconds: 19,
};

/** Slide 5's two looks the chips set, apart from the chips' recordings so the live core can draw them alone. */
export const HOME_NEXT_STEPS: {
  turnTo: number;
  row: { index: number; before: string; after: string };
} = {
  turnTo: 8,
  row: {
    index: 2,
    before: 'The first call uses this deck',
    after: 'The first call uses this deck and its notes',
  },
};
