// Generated by scripts/build-home-assets.ts --slides (docs/DESIGN.md 8.2); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The hero frame's editor chrome, read from the editor at build (scripts/home/chrome.ts): the
// toolbar's sixteen controls from the menu model and the title row's words and glyphs from
// TitleRow.tsx's strings, so the frame draws the editor's own controls.

export type HomeToolbarCell = {
  control: string;
  /** the undo's name, the one control of the frame a screen reader meets */
  label?: string;
  /** the glyph of packages/chrome/src/icons.tsx, drawn as a mask of icons.generated.css; null for a word */
  icon: string | null;
  word: string | null;
  divider: boolean;
};

export const HOME_TOOLBAR: readonly HomeToolbarCell[] = [
  {
    control: 'toolbar.search',
    icon: 'search',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.newSlide',
    icon: 'plus',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.undo',
    label: 'Undo',
    icon: 'arrow-uturn-left',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.redo',
    icon: 'arrow-uturn-right',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.print',
    icon: 'printer',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.paintFormat',
    icon: 'paint-brush',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.zoom',
    icon: null,
    word: 'Fit',
    divider: false,
  },
  {
    control: 'toolbar.select',
    icon: 'cursor-arrow',
    word: null,
    divider: true,
  },
  {
    control: 'toolbar.textBox',
    icon: 'text',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.insertImage',
    icon: 'photo',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.insertShape',
    icon: 'square-2-stack',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.insertLine',
    icon: 'minus',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.insertComment',
    icon: 'chat',
    word: null,
    divider: false,
  },
  {
    control: 'toolbar.background',
    icon: null,
    word: 'Background',
    divider: true,
  },
  {
    control: 'toolbar.layout',
    icon: null,
    word: 'Layout',
    divider: false,
  },
  {
    control: 'toolbar.theme',
    icon: null,
    word: 'Theme',
    divider: false,
  },
];

export const HOME_TITLE_ROW = {
  saved: 'All changes saved',
  savedIcon: 'cloud',
  comments: 'Show all comments',
  commentsIcon: 'chat',
  slideshow: 'Slideshow',
  slideshowIcon: 'play',
  slideshowMore: 'chevron-down',
  share: 'Share',
  shareIcon: 'lock-closed',
  agentIcon: 'command-line',
} as const;

export const HOME_STEP_ICONS = {
  done: 'check-circle',
  playing: 'play',
} as const;

/** The Format options panel's words, as FormatOptions.tsx draws them (the canvas band's readout). */
export const HOME_FORMAT_PANEL = {
  title: 'Format options',
  size: 'Size & rotation',
  position: 'Position',
  layout: 'Layout',
  width: 'Width',
  height: 'Height',
  rotate: 'Rotate',
  x: 'X',
  y: 'Y',
  icons: ['arrows-pointing-in', 'move', 'columns', 'command-line'],
} as const;

/** View > Slideshow's shortcut on the Present button: the Mac chips, the other form. */
export const HOME_SLIDESHOW_KEYS = {
  mac: ['⌘', '↩'],
  other: 'Ctrl+F5',
} as const;
