// Generated by scripts/build-home-assets.ts --slides (docs/LANDING.md 2.0, 6.1; integrator.md 4.2); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The client safe facts of the page deck: the ids, the order, the titles, the notes and the
// boxes of the selectable objects in sheet units. No slide markup and no still lives here (they
// are in slides.generated.ts, read only on the server, and live-slides.generated.ts, which only
// the live module imports), so the route chunk and the live module may both import this file.

/** The eight slides of the page deck, by id (docs/LANDING.md 2.0 with Kevin's answer 1). */
export type HomeSlideId =
  'title' | 'plan' | 'gets' | 'ships' | 'next-steps' | 'rosetta' | 'field' | 'close';

/** A box in sheet units (1 unit is 1/1600 of the sheet's width), turned `rot` degrees clockwise. */
export type SheetBox = { x: number; y: number; w: number; h: number; rot: number };

/** A selectable object, `<slide>#<object>`: the value of its wrapper's `data-object`. */
export type HomeObjectId = `${HomeSlideId}#${string}`;

/** The word the selection chip shows (the editor's role chip). */
export type HomeObjectRole = 'Title' | 'Subtitle' | 'Heading' | 'Text' | 'Credit' | 'Plate';

export type HomeObject = {
  id: HomeObjectId;
  role: HomeObjectRole;
  /** the box at rest: the hero's hand set boxes, the Rosetta Stone's from `slide to-canvas` */
  box: SheetBox;
  /** the text at rest; '' for the plate */
  text: string;
  /** a second click or Enter types in it */
  editable: boolean;
  /** the block id the CLI prints for this object after `slide to-canvas`; null on the hero */
  canvasBlock: string | null;
};

export type HomeSlideFacts = {
  id: HomeSlideId;
  /** the deck number at rest (1 to 8) */
  n: number;
  /** `slideTitle` of the slide, the Present list's row */
  title: string;
  /** the speaker notes, which the show's bar reads */
  notes: string;
  /** the layout id of `packages/schema/src/layouts.ts` */
  layout: string;
  objects: readonly HomeObject[];
};

/** Where the hero's picture sits on the sheet, in sheet units (integrator.md 2.2, answer 1). */
export type FieldDisc = { cx: number; cy: number; r: number };

export type HomeDeckFacts = {
  /** sha256 over apps/studio/home-deck (deck.json, slides, assets), every file in path order */
  fixtureSha256: string;
  /** sha256 over the page deck: the fixture, the run's sections and its slide 5 */
  pageDeckSha256: string;
  /** the customer name the fixture spells */
  customer: string;
  /** the page deck at rest: eight ids */
  order: readonly HomeSlideId[];
  /** the fixture, the run's start: seven ids, `next-steps` absent */
  startOrder: readonly HomeSlideId[];
  slides: Readonly<Record<HomeSlideId, HomeSlideFacts>>;
  /** the hero's Blue Marble disc (answer 1) */
  heroDisc: FieldDisc;
};

export const HOME_DECK: HomeDeckFacts = {
  fixtureSha256: 'f8b65f43796ff04ddf64d83b53ec8c9feb864f72691336ff75fbe27212c93d5b',
  pageDeckSha256: '71d22b311b740c58caf8718981c32dad641de18a2ef48f7cae4a47a92aeadeba',
  customer: 'Northwind',
  order: ['title', 'plan', 'gets', 'ships', 'next-steps', 'rosetta', 'field', 'close'],
  startOrder: ['title', 'plan', 'gets', 'ships', 'rosetta', 'field', 'close'],
  slides: {
    title: {
      id: 'title',
      n: 1,
      title: 'Build the pitch, present it and send the link',
      notes: 'Turboslide opens on a blank deck. No account is needed.',
      layout: 'title',
      objects: [
        {
          id: 'title#heading',
          role: 'Title',
          box: {
            x: 137,
            y: 150,
            w: 884,
            h: 441,
            rot: 0,
          },
          text: 'Build the pitch, present it and send the link',
          editable: true,
          canvasBlock: null,
        },
        {
          id: 'title#lead',
          role: 'Subtitle',
          box: {
            x: 137,
            y: 640,
            w: 744,
            h: 48,
            rot: 0,
          },
          text: 'Turboslide is a slides editor in the browser.',
          editable: true,
          canvasBlock: null,
        },
      ],
    },
    plan: {
      id: 'plan',
      n: 2,
      title: 'Onboarding plan for Northwind',
      notes: 'Open with the goals Northwind named on the call.',
      layout: 'one-column',
      objects: [],
    },
    gets: {
      id: 'gets',
      n: 3,
      title: 'What Northwind gets',
      notes: 'Read the three rows aloud, then ask Northwind which one matters most.',
      layout: 'rows',
      objects: [],
    },
    ships: {
      id: 'ships',
      n: 4,
      title: 'The first Northwind deck ships in week one',
      notes: 'Ask Northwind who presents the first deck.',
      layout: 'statement',
      objects: [],
    },
    'next-steps': {
      id: 'next-steps',
      n: 5,
      title: 'Next steps with Northwind',
      notes: '',
      layout: 'rows',
      objects: [],
    },
    rosetta: {
      id: 'rosetta',
      n: 6,
      title: 'The Rosetta Stone',
      notes: 'Drag the heading off the plate, then press Undo.',
      layout: 'mood',
      objects: [
        {
          id: 'rosetta#plate',
          role: 'Plate',
          box: {
            x: 1031.03,
            y: 602.73,
            w: 431.97,
            h: 168.27,
            rot: 0,
          },
          text: '',
          editable: false,
          canvasBlock: 'plate',
        },
        {
          id: 'rosetta#h',
          role: 'Heading',
          box: {
            x: 612,
            y: 388,
            w: 520,
            h: 96,
            rot: 0,
          },
          text: 'The Rosetta Stone',
          editable: true,
          canvasBlock: 'h',
        },
        {
          id: 'rosetta#p1',
          role: 'Text',
          box: {
            x: 1057.03,
            y: 684.25,
            w: 379.97,
            h: 33,
            rot: 0,
          },
          text: 'One decree of 196 BC in three scripts.',
          editable: true,
          canvasBlock: 'p1',
        },
        {
          id: 'rosetta#credit',
          role: 'Credit',
          box: {
            x: 1057.03,
            y: 729.25,
            w: 379.97,
            h: 21.75,
            rot: 0,
          },
          text: 'Photograph: Hans Hillewaert, CC BY-SA 4.0',
          editable: true,
          canvasBlock: 'credit',
        },
      ],
    },
    field: {
      id: 'field',
      n: 7,
      title: 'The opener field',
      notes: 'Download this deck as a PDF or a PowerPoint file.',
      layout: 'mood',
      objects: [],
    },
    close: {
      id: 'close',
      n: 8,
      title: 'Turboslide',
      notes: 'New Presentation opens a blank deck.',
      layout: 'big-number',
      objects: [],
    },
  },
  heroDisc: {
    cx: 1450,
    cy: 1180,
    r: 600,
  },
};

/**
 * The Tailor dialog's own words, copied from @turboslide/chrome's TAILOR
 * (packages/chrome/src/panels/assist-strings.ts) for the band's resting rows until the package
 * exports the module; `countRest` is TAILOR.count over the CLI's recorded answer on the page deck.
 */
export const HOME_TAILOR_WORDS = {
  from: 'Replace',
  to: 'With',
  apply: 'Apply',
  undo: 'Undo',
  countRest: '8 places on 4 slides',
} as const;

/** The Perfect file's picture size, read from the file the CLI wrote (docs/LANDING.md 2.8). */
export const HOME_EXPORT_FACTS = {
  perfectWidth: 3200,
  perfectHeight: 1800,
} as const;

/** The run's figures the route prints (the caption's seconds, run.generated.ts `captionSeconds`). */
export const HOME_RUN_FACTS = {
  captionSeconds: 12,
  steps: 3,
} as const;
