// Generated by scripts/build-home-assets.ts --slides from apps/studio/home-deck and the agents run
// (docs/LANDING.md 2.0, 6.1); never edited by hand. Day 0 stub: the integrator wrote the types and
// placeholder values on day 0 (docs/gslides-parity/landing/build/integrator.md "Landing, day 0",
// section 4.2). The types are the contract between the lanes; L1's push 1 writes the values.
//
// The client safe facts of the page deck: the ids, the order, the titles, the notes and the
// boxes of the selectable objects in sheet units. No slide markup and no still lives here (they
// are in slides.generated.ts, read only on the server, and live-slides.generated.ts, which only
// the live module imports), so the route chunk and the live module may both import this file.

/** The eight slides of the page deck, by id (docs/LANDING.md 2.0 with Kevin's answer 1). */
export type HomeSlideId =
  'title' | 'plan' | 'gets' | 'ships' | 'next-steps' | 'rosetta' | 'field' | 'close';

/** A box in sheet units (1 unit is 1/1600 of the sheet's width), turned `rot` degrees clockwise. */
export type SheetBox = { x: number; y: number; w: number; h: number; rot: number };

/** A selectable object, `<slide>#<object>`: the value of its wrapper's `data-object`. */
export type HomeObjectId = `${HomeSlideId}#${string}`;

/** The word the selection chip shows (the editor's role chip). */
export type HomeObjectRole = 'Title' | 'Subtitle' | 'Heading' | 'Text' | 'Credit' | 'Plate';

export type HomeObject = {
  id: HomeObjectId;
  role: HomeObjectRole;
  /** the rendered box at rest, from `RenderedSlide.slots` */
  box: SheetBox;
  /** the text at rest; '' for the plate */
  text: string;
  /** a second click or Enter types in it */
  editable: boolean;
  /**
   * The block id the CLI prints for this object after `slide to-canvas` (the canvas band's
   * Command row); the build reads it from the converted temporary deck. Null on the hero.
   */
  canvasBlock: string | null;
};

export type HomeSlideFacts = {
  id: HomeSlideId;
  /** the deck number at rest (1 to 8) */
  n: number;
  /** `slideTitle` of the slide, the Present list's row */
  title: string;
  /** the speaker notes, which the show's bar reads */
  notes: string;
  /** the layout id of `packages/schema/src/layouts.ts` */
  layout: string;
  objects: readonly HomeObject[];
};

/** Where a field's picture sits on the hero sheet, in sheet units (integrator.md 3.1, answer 1). */
export type FieldDisc = { cx: number; cy: number; r: number };

export type HomeDeckFacts = {
  /** sha256 over apps/studio/home-deck, every file in path order */
  fixtureSha256: string;
  /** sha256 over the temporary page deck after the run */
  pageDeckSha256: string;
  /** the customer name the fixture spells */
  customer: string;
  /** the page deck at rest: eight ids */
  order: readonly HomeSlideId[];
  /** the fixture, the run's start: seven ids, `next-steps` absent */
  startOrder: readonly HomeSlideId[];
  slides: Readonly<Record<HomeSlideId, HomeSlideFacts>>;
  /** the hero's Blue Marble disc (answer 1) */
  heroDisc: FieldDisc;
};

/** Day 0 placeholder values; L1's build replaces every one. */
const STUB_SLIDE = (id: HomeSlideId, n: number, layout: string): HomeSlideFacts => ({
  id,
  n,
  title: '',
  notes: '',
  layout,
  objects: [],
});

export const HOME_DECK: HomeDeckFacts = {
  fixtureSha256: '',
  pageDeckSha256: '',
  customer: 'Northwind',
  order: ['title', 'plan', 'gets', 'ships', 'next-steps', 'rosetta', 'field', 'close'],
  startOrder: ['title', 'plan', 'gets', 'ships', 'rosetta', 'field', 'close'],
  slides: {
    title: STUB_SLIDE('title', 1, 'title'),
    plan: STUB_SLIDE('plan', 2, 'statement'),
    gets: STUB_SLIDE('gets', 3, 'rows'),
    ships: STUB_SLIDE('ships', 4, 'statement'),
    'next-steps': STUB_SLIDE('next-steps', 5, 'rows'),
    rosetta: STUB_SLIDE('rosetta', 6, 'mood'),
    field: STUB_SLIDE('field', 7, 'mood'),
    close: STUB_SLIDE('close', 8, 'closing'),
  },
  heroDisc: { cx: 1380, cy: 1240, r: 760 },
};
