// Generated by scripts/build-home-assets.ts from packages/theme/brand/facts.json; do not edit
// by hand. The counts the /home page states (gslides-parity SPEC-4 0.25), copied from the facts
// file B1's build writes so the page's JavaScript carries ten values and not the file's 141
// measured rows; `--check` fails when facts.json has changed since this copy (its sha256 is
// recorded here).
export const FACTS_DATA = {
  factsSha256: '3b543bf3790527d5fed49dbff4c67b83c0387be8073a5811a68e451d432b32bc',
  actions: 192,
  mcpTools: 169,
  httpPaths: 176,
  layouts: 22,
  materials: 17,
  checkSteps: 32,
  parityRows: 3369,
  mismatchPercent: 0.003,
  licence: 'MIT',
} as const;
