// Generated by scripts/build-home-assets.ts from packages/theme/brand/facts.json; do not edit
// by hand. The counts the /home page states (gslides-parity SPEC-4 0.25), copied from the facts
// file B1's build writes so the page's JavaScript carries ten values and not the file's 141
// measured rows; `--check` fails when facts.json has changed since this copy (its sha256 is
// recorded here).
export const FACTS_DATA = {
  factsSha256: '85a0b2d5ba1e5a13672c9b466a230b1c803cabb8c1a8f34ad157a03ec6294b77',
  actions: 183,
  mcpTools: 160,
  httpPaths: 167,
  layouts: 22,
  materials: 17,
  checkSteps: 32,
  parityRows: 3369,
  mismatchPercent: 0.003,
  licence: 'MIT',
} as const;
