// Generated by scripts/home/run.ts (docs/LANDING.md 2.2, 2.9, 6.1); never edited by hand.
// node scripts/home/run.ts --check compares this file with its sources.
//
// The hero's staged loop (2.2) and slide 5's two looks the chips set (2.9), recorded from the CLI
// by `scripts/home/run.ts --record` with the chips in chips.generated.ts. Apart from the chips so
// the live core plays the loop and draws the looks without the agents band's recordings.

export type StepLanding =
  | { kind: 'cut' }
  | { kind: 'rails' }
  | { kind: 'words'; chars: number }
  | { kind: 'rows'; count: number }
  | { kind: 'names' }
  | { kind: 'turn'; degrees: number }
  | { kind: 'mark' };

/** A step's scheduled lengths in ms with the fixture's name (LANDING.md 3.4 L-H, 3.6 A1 to A6). */
export type StepSchedule = {
  type: number;
  answer: number;
  beat: number;
  ring: number;
  land: number;
  flag: number;
  total: number;
};

/** One step of the hero's staged loop (2.2): Restore, then the run's three writes. */
export type LoopStep = {
  id: 'restore' | 'new' | 'title' | 'rows';
  /** the command as the terminal prints it, with the fixture's name */
  command: string;
  /** the characters typed at 24 ms (A1); the rest, a quoted value, prints whole one frame later */
  typedChars: number;
  answer: readonly string[];
  /** where the ring travels; null for Restore (no ring) */
  target: 'next-steps' | 'next-steps#h' | 'next-steps#rows' | null;
  landing: StepLanding;
  schedule: StepSchedule;
};

export type HomeLoop = {
  /** the customer the loop's commands spell, which the page replaces with the deck's */
  customer: string;
  steps: readonly LoopStep[];
  holdFirstMs: number;
  holdLastMs: number;
  /** a cycle's length: the holds and the four steps (the caption's figure, rounded) */
  cycleMs: number;
  captionSeconds: number;
};

export const HOME_LOOP: HomeLoop = {
  customer: 'Northwind',
  steps: [
    {
      id: 'restore',
      command: 'turboslide version restore 1',
      typedChars: 28,
      answer: ['restored version 1: revision 4'],
      target: null,
      landing: {
        kind: 'cut',
      },
      schedule: {
        type: 672,
        answer: 320,
        beat: 500,
        ring: 0,
        land: 0,
        flag: 960,
        total: 2452,
      },
    },
    {
      id: 'new',
      command: 'turboslide slide new --layout rows --after ships --id next-steps',
      typedChars: 64,
      answer: ['new rows slide next-steps after ships: revision 5'],
      target: 'next-steps',
      landing: {
        kind: 'rails',
      },
      schedule: {
        type: 1536,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 780,
        flag: 960,
        total: 4096,
      },
    },
    {
      id: 'title',
      command: 'turboslide block set next-steps#h /text "Next steps with Northwind"',
      typedChars: 67,
      answer: ['set h /text on next-steps: revision 6, 8 finding(s)'],
      target: 'next-steps#h',
      landing: {
        kind: 'words',
        chars: 25,
      },
      schedule: {
        type: 1608,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 600,
        flag: 960,
        total: 4088,
      },
    },
    {
      id: 'rows',
      command:
        'turboslide block set next-steps#rows /items \'[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]\'',
      typedChars: 43,
      answer: ['set rows /items on next-steps: revision 7, 2 finding(s)'],
      target: 'next-steps#rows',
      landing: {
        kind: 'rows',
        count: 3,
      },
      schedule: {
        type: 1032,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 270,
        flag: 960,
        total: 3512,
      },
    },
  ],
  holdFirstMs: 3000,
  holdLastMs: 2000,
  cycleMs: 19148,
  captionSeconds: 19,
};

/** Slide 5's two looks the chips set, apart from the chips' recordings so the live core can draw them alone. */
export const HOME_NEXT_STEPS: {
  turnTo: number;
  row: { index: number; before: string; after: string };
} = {
  turnTo: 8,
  row: {
    index: 2,
    before: 'The first call uses this deck',
    after: 'The first call uses this deck and its notes',
  },
};
