// Generated by scripts/build-home-assets.ts --slides (docs/DESIGN.md 8.4); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The miniature's menu rows' glyphs (docs/DESIGN.md 8.4; scripts/home/sprite.ts): for each row of
// `MINI_MENUS`, depth first, its glyph's index in the sprite (the symbol `g<index>`), -1 for a
// row that draws none. The menus chunk imports this module on its own, so the list travels apart
// from the menus.

export const MENU_GLYPHS: readonly number[] = [
  74, 42, 2, 43, 61, 98, 61, 4, 4, 4, 4, 4, 4, 4, 4, 37, 71, 1, 36, 94, 36, 42, 44, 76, 9, 10, 79,
  43, 34, 35, 96, 86, 87, 86, 80, 75, 64, 64, 63, 101, 101, 101, 101, 15, 100, 100, 100, 100, 100,
  88, 88, 88, 28, 28, 28, 28, 28, -1, -1, -1, 42, 84, 71, 71, 28, 44, 46, 72, 8, 94, 61, 95, 23, 82,
  83, 81, 87, 5, 29, 99, 92, 24, 25, 24, 26, 27, 78, 102, 66, 58, 53, 56, 54, 61, 28, 74, 47, 41,
  95, 22, 50, 97, 89, 7, 3, 51, 47, 74, 74, 66, 95, 95, 95, 95, 19, 17, 19, 18, 16, 20, 21, 20, 20,
  20, 20, 20, 21, 20, 20, 62, 70, 62, 92, 88, 88, 88, 88, 96, 96, 96, 13, 12, 92, 11, 93, 72, 101,
  65, 6, 8, 61, 94, 15, 9, 85, 0, 60, 91, 60, 55, 55, 55, 55, 55, 55, 55, 59, 59, 59, 59, 59, 59,
  59, 59, 59, 59, 59, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 0, 14, 49, 74, 85, 96, 45, 21, 21,
  20, 21, 20, 72, 38, 91, 77, 33, 33, 32, 32, 38, 17, 19, 18, 16, 16, 16, 12, 12, 13, 101, 101, 101,
  6, 6, 9, 12, 13, 78, 78, 78, 37, 37, 41, 73, 73, 73, 91, 90, 67, 40, 44, 71, 31, 103, 80, 48, 52,
  39,
];
