// Generated by scripts/build-home-assets.ts --stills (docs/LANDING.md 2.13, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The Animated pattern of slide 8 as the patterns band's shader draws it (scripts/home/pattern.ts,
// V4's): the recipe of the fixture's `pattern` asset, the exporter's capture of
// `paper:dithering`, with its uniforms converted at build by the materials package's `toShaderUniforms`
// and its two colours left to the page, which maps them to the slide's --ink and --paper.

export type HomePattern = {
  materialId: string;
  /** the capture's anchor in ms: the still frame the exporter stores is the shader at this frame */
  frame: number;
  /** the editor's live preview speed */
  speed: number;
  /** the capture's recipe key, or null */
  recipeKey: string | null;
  /** every uniform but u_colorBack and u_colorFront, as ShaderMount takes them */
  uniforms: Readonly<Record<string, number>>;
};

export const HOME_PATTERN: HomePattern = {
  materialId: 'paper:dithering',
  frame: 0,
  speed: 1,
  recipeKey: 'sha256:26d20700ed94468a827bb7f800c5c3cb2c6e8bc01621d92a49c4de55c115922a',
  uniforms: {
    u_shape: 7,
    u_type: 4,
    u_pxSize: 3,
    u_fit: 0,
    u_scale: 0.62,
    u_rotation: 0,
    u_offsetX: -0.28,
    u_offsetY: 0.04,
    u_originX: 0.5,
    u_originY: 0.5,
    u_worldWidth: 0,
    u_worldHeight: 0,
  },
};
