// Generated by scripts/build-home-assets.ts --stills (docs/DESIGN.md 8.12); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The patterns band's cards (docs/DESIGN.md 8.12): the stills of the editor's Insert > Animated
// pattern gallery (packages/materials/previews, GALLERY_MATERIAL_IDS of the catalog), each with
// the gallery's name, served under /home/ (assets.json role `pattern-card`).
export const HOME_PATTERN_CARDS: readonly { name: string; path: string }[] = [
  {
    name: 'Liquid metal',
    path: '/home/pattern-card-f9f953be25.webp',
  },
  {
    name: 'Gem smoke',
    path: '/home/pattern-card-d98f6d47d0.webp',
  },
  {
    name: 'God rays',
    path: '/home/pattern-card-74f114db66.webp',
  },
  {
    name: 'Mesh gradient',
    path: '/home/pattern-card-196583cccc.webp',
  },
  {
    name: 'Smoke ring',
    path: '/home/pattern-card-b878423966.webp',
  },
  {
    name: 'Grain gradient',
    path: '/home/pattern-card-c83f50d859.webp',
  },
  {
    name: 'Simplex noise',
    path: '/home/pattern-card-d7dc077496.webp',
  },
  {
    name: 'Swirl',
    path: '/home/pattern-card-3ac0ab4a76.webp',
  },
  {
    name: 'Spiral',
    path: '/home/pattern-card-96dc3052e7.webp',
  },
  {
    name: 'Dithering',
    path: '/home/pattern-card-fcac76ec6c.webp',
  },
  {
    name: 'Static radial gradient',
    path: '/home/pattern-card-9a9254e722.webp',
  },
  {
    name: 'Neuro noise',
    path: '/home/pattern-card-b44ca6bdc9.webp',
  },
  {
    name: 'Metaballs',
    path: '/home/pattern-card-b31ba02f07.webp',
  },
  {
    name: 'Waves',
    path: '/home/pattern-card-33f038a932.webp',
  },
  {
    name: 'Dot grid',
    path: '/home/pattern-card-ed481b7f42.webp',
  },
  {
    name: 'Perlin noise',
    path: '/home/pattern-card-09b55fe4c9.webp',
  },
  {
    name: 'Static mesh gradient',
    path: '/home/pattern-card-6c6e0954dc.webp',
  },
];

/** Every card's size in pixels, which the page writes on each `img` so nothing moves on load. */
export const HOME_PATTERN_CARD_SIZE = { width: 320, height: 200 } as const;
