// Generated by scripts/build-home-assets.ts --run (docs/LANDING.md 2.4, 6.1); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
// The route reads this module only behind `import.meta.env.SSR` (the agents band's resting
// screen and the MCP and HTTP tab panels are server markup); the live module imports it, so it
// travels in the live chunk. Every row reads the commands from here, never from literal text.
// The answers are the CLI's human lines recorded by --run under apps/studio/home-deck/recorded/;
// each step prints its first line, the summary, and keeps the finding lines the CLI added after
// it (the rows layout's empty placeholders and the customer's name in a heading) in `findings`.
import type { HomeObjectId, HomeSlideId } from './deck.generated';

/** A screen formatted by panel-format.ts at both widths: 64 columns and 44 columns. */
export type PanelText = { wide: readonly string[]; narrow: readonly string[] };

export type RunLanding =
  { kind: 'rails' } | { kind: 'words'; chars: number } | { kind: 'rows'; count: number };

/** The step's scheduled lengths in ms (docs/LANDING.md 2.4, A1 to A6), with the fixture's name. */
export type RunSchedule = {
  /** typed characters times 24 ms (A1) */
  type: number;
  /** 200 ms, then 120 ms and 55 ms a further line (A2) */
  answer: number;
  /** the 500 ms beat */
  beat: number;
  /** 300 ms plus the distance over two, at most 700 ms (A3); the bound */
  ring: number;
  /** the landing (A4, A5) */
  land: number;
  /** the flag's 800 ms hold and 160 ms exit */
  flag: number;
  total: number;
};

export type RunStep = {
  n: 1 | 2 | 3;
  action: 'slide.new' | 'block.set';
  /** the arguments after `turboslide`, as the CLI received them */
  argv: readonly string[];
  /** the command as the panel prints it, `turboslide ...`, the newlines inside its quotes kept */
  command: string;
  /** the characters typed at 24 ms: the command up to its value (A1); a JSON value pastes whole */
  typedChars: number;
  /** the CLI's human answer as the panel prints it: its first line */
  answer: readonly string[];
  /** the finding lines the CLI printed under that line */
  findings: readonly string[];
  /** the revision the CLI read before the step, the bodies' `baseRevision` */
  revisionBefore: string;
  /** the `tools/call` params: the tool of mcp-tools.json and its arguments */
  mcp: { name: string; arguments: Readonly<Record<string, unknown>> };
  /** the request of openapi.json */
  http: { method: 'POST'; path: string; body: Readonly<Record<string, unknown>> };
  /** where the agent's ring travels */
  target: HomeObjectId | HomeSlideId;
  landing: RunLanding;
  schedule: RunSchedule;
  /** the Version history row's words */
  history: string;
};

/** The deck states the typed line can meet (slide 5 absent, placeholders, titled, filled). */
export type RunDeckState = 'absent' | 'placeholders' | 'titled' | 'filled';

/** One recorded answer to a typed form (docs/LANDING.md 2.4, "The typed line"). */
export type TypedRecording = {
  /** `tailor-spaced` is `tailor --replace <from>=<to>`, which this CLI refuses (it takes --replace=<value>) */
  form: 'tailor' | 'tailor-spaced' | 'version-list' | 'step';
  state: RunDeckState;
  /** for `tailor`: whether the deck held the name; null otherwise */
  nameFound: boolean | null;
  /** for `step`: the step run in that state; null otherwise */
  step: 1 | 2 | 3 | null;
  argv: readonly string[];
  /** the CLI's exit code: 0 ran, 2 refused */
  code: number;
  /** the human answer the panel prints (a write's summary line) */
  answer: readonly string[];
  /** the finding lines a write printed under its summary */
  findings: readonly string[];
  /** the names the recording was made with, which the page substitutes; null when none */
  names: { from: string; to: string } | null;
};

export type HomeRun = {
  /** `turboslide --version`'s version, equal to the banner's */
  cliVersion: string;
  /** the banner, the CLI's own lines, the fourth line's fact (the checkout's path) left out */
  banner: readonly string[];
  steps: readonly [RunStep, RunStep, RunStep];
  /** the sum of the three schedules with the fixture's name */
  totalMs: number;
  /** totalMs in whole seconds, the caption's figure */
  captionSeconds: number;
  /** the help lines: the five commands this page runs */
  help: readonly string[];
  typed: readonly TypedRecording[];
  /** `tailor --replace=Northwind=Globex` on the fixture (7 slides) and on the page deck (8) */
  tailorCounts: {
    start: { places: number; slides: number };
    rest: { places: number; slides: number };
  };
  /** every resting screen, formatted and checked against the slots */
  screens: {
    banner: PanelText;
    transcript: PanelText;
    mcp: PanelText;
    http: PanelText;
    help: PanelText;
  };
  /** the length of cli.json `actions` */
  cliCommands: number;
  /** the answer to a line this page does not run */
  refusal: string;
  /** the canvas band's gesture forms, each accepted by the CLI on the page deck */
  gestures: readonly { argv: readonly string[]; answer: readonly string[] }[];
};

export const HOME_RUN: HomeRun = {
  cliVersion: '2026.1001.3',
  banner: [
    ' ███████████  Turboslide 2026.1001.3',
    ' ▀▀▀▀▀███▀▀▀  https://www.turboslide.com',
    '▄▄▄▄▄ ███     193 actions, effects backend: wasm',
    '▄▄▄▄ ▄▄▄',
    '     ███',
    '███ ███',
  ],
  steps: [
    {
      n: 1,
      action: 'slide.new',
      argv: ['slide', 'new', '--layout', 'rows', '--after', 'ships', '--id', 'next-steps'],
      command: 'turboslide slide new --layout rows --after ships --id next-steps',
      typedChars: 64,
      answer: ['new rows slide next-steps after ships: revision 1'],
      findings: [],
      revisionBefore: '0',
      mcp: {
        name: 'deck_new_slide',
        arguments: {
          layout: 'rows',
          after: 'ships',
          id: 'next-steps',
          baseRevision: 0,
        },
      },
      http: {
        method: 'POST',
        path: '/api/actions/slide.new',
        body: {
          layout: 'rows',
          after: 'ships',
          id: 'next-steps',
          baseRevision: 0,
        },
      },
      target: 'next-steps',
      landing: {
        kind: 'rails',
      },
      schedule: {
        type: 1536,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 780,
        flag: 960,
        total: 4096,
      },
      history: 'Added slide 5 with the Ruled rows layout',
    },
    {
      n: 2,
      action: 'block.set',
      argv: ['block', 'set', 'next-steps#h', '/text', 'Next steps with Northwind'],
      command: 'turboslide block set next-steps#h /text "Next steps with Northwind"',
      typedChars: 67,
      answer: ['set h /text on next-steps: revision 2, 8 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
      ],
      revisionBefore: '1',
      mcp: {
        name: 'deck_update_block',
        arguments: {
          slideId: 'next-steps',
          blockId: 'h',
          path: '/text',
          value: 'Next steps with Northwind',
          baseRevision: 1,
        },
      },
      http: {
        method: 'POST',
        path: '/api/actions/block.set',
        body: {
          slideId: 'next-steps',
          blockId: 'h',
          path: '/text',
          value: 'Next steps with Northwind',
          baseRevision: 1,
        },
      },
      target: 'next-steps#h',
      landing: {
        kind: 'words',
        chars: 25,
      },
      schedule: {
        type: 1608,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 600,
        flag: 960,
        total: 4088,
      },
      history: 'Set the title of slide 5',
    },
    {
      n: 3,
      action: 'block.set',
      argv: [
        'block',
        'set',
        'next-steps#rows',
        '/items',
        '[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]',
      ],
      command:
        'turboslide block set next-steps#rows /items \'[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]\'',
      typedChars: 43,
      answer: ['set rows /items on next-steps: revision 3, 2 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
      ],
      revisionBefore: '2',
      mcp: {
        name: 'deck_update_block',
        arguments: {
          slideId: 'next-steps',
          blockId: 'rows',
          path: '/items',
          value: [
            {
              key: 'Monday',
              value: 'Northwind sellers get the deck',
            },
            {
              key: 'Wednesday',
              value: 'Agents draft slides over MCP',
            },
            {
              key: 'Friday',
              value: 'The first call uses this deck',
            },
          ],
          baseRevision: 2,
        },
      },
      http: {
        method: 'POST',
        path: '/api/actions/block.set',
        body: {
          slideId: 'next-steps',
          blockId: 'rows',
          path: '/items',
          value: [
            {
              key: 'Monday',
              value: 'Northwind sellers get the deck',
            },
            {
              key: 'Wednesday',
              value: 'Agents draft slides over MCP',
            },
            {
              key: 'Friday',
              value: 'The first call uses this deck',
            },
          ],
          baseRevision: 2,
        },
      },
      target: 'next-steps#rows',
      landing: {
        kind: 'rows',
        count: 3,
      },
      schedule: {
        type: 1032,
        answer: 320,
        beat: 500,
        ring: 700,
        land: 270,
        flag: 960,
        total: 3512,
      },
      history: 'Set the rows of slide 5',
    },
  ],
  totalMs: 11696,
  captionSeconds: 12,
  help: [
    'This page runs these five commands.',
    'turboslide slide new --layout rows --after ships --id next-steps',
    'turboslide block set next-steps#h /text "<title>"',
    "turboslide block set next-steps#rows /items '<rows>'",
    'turboslide tailor --replace=<from>=<to>',
    'turboslide version list',
  ],
  typed: [
    {
      form: 'tailor',
      state: 'absent',
      nameFound: true,
      step: null,
      argv: ['tailor', '--replace=Northwind=Globex'],
      code: 0,
      answer: ['6 replacements on 3 slides, 0 pictures swapped, 0 skipped; revision 1'],
      findings: [],
      names: {
        from: 'Northwind',
        to: 'Globex',
      },
    },
    {
      form: 'tailor',
      state: 'absent',
      nameFound: false,
      step: null,
      argv: ['tailor', '--replace=Initech=Globex'],
      code: 0,
      answer: ['0 replacements on 0 slides, 0 pictures swapped, 0 skipped; revision 0'],
      findings: [],
      names: {
        from: 'Initech',
        to: 'Globex',
      },
    },
    {
      form: 'version-list',
      state: 'absent',
      nameFound: null,
      step: null,
      argv: ['version', 'list'],
      code: 0,
      answer: ['no versions yet'],
      findings: [],
      names: null,
    },
    {
      form: 'step',
      state: 'absent',
      nameFound: null,
      step: 1,
      argv: ['slide', 'new', '--layout', 'rows', '--after', 'ships', '--id', 'next-steps'],
      code: 0,
      answer: ['new rows slide next-steps after ships: revision 1'],
      findings: [],
      names: null,
    },
    {
      form: 'step',
      state: 'absent',
      nameFound: null,
      step: 2,
      argv: ['block', 'set', 'next-steps#h', '/text', 'Next steps with Northwind'],
      code: 2,
      answer: ['turboslide: mutation 0 (block.set): No slide "next-steps"'],
      findings: [],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'step',
      state: 'absent',
      nameFound: null,
      step: 3,
      argv: [
        'block',
        'set',
        'next-steps#rows',
        '/items',
        '[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]',
      ],
      code: 2,
      answer: ['turboslide: mutation 0 (block.set): No slide "next-steps"'],
      findings: [],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'tailor',
      state: 'placeholders',
      nameFound: true,
      step: null,
      argv: ['tailor', '--replace=Northwind=Globex'],
      code: 0,
      answer: ['6 replacements on 3 slides, 0 pictures swapped, 0 skipped; revision 2'],
      findings: [],
      names: {
        from: 'Northwind',
        to: 'Globex',
      },
    },
    {
      form: 'tailor',
      state: 'placeholders',
      nameFound: false,
      step: null,
      argv: ['tailor', '--replace=Initech=Globex'],
      code: 0,
      answer: ['0 replacements on 0 slides, 0 pictures swapped, 0 skipped; revision 1'],
      findings: [],
      names: {
        from: 'Initech',
        to: 'Globex',
      },
    },
    {
      form: 'version-list',
      state: 'placeholders',
      nameFound: null,
      step: null,
      argv: ['version', 'list'],
      code: 0,
      answer: [],
      findings: [
        '1  r1     2026-10-03T04:01:33.834Z  agent:landing      1 mutation(s): slide.insert',
      ],
      names: null,
    },
    {
      form: 'step',
      state: 'placeholders',
      nameFound: null,
      step: 1,
      argv: ['slide', 'new', '--layout', 'rows', '--after', 'ships', '--id', 'next-steps'],
      code: 2,
      answer: ['turboslide: Slide "next-steps" exists already'],
      findings: [],
      names: null,
    },
    {
      form: 'step',
      state: 'placeholders',
      nameFound: null,
      step: 2,
      argv: ['block', 'set', 'next-steps#h', '/text', 'Next steps with Northwind'],
      code: 0,
      answer: ['set h /text on next-steps: revision 2, 8 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
      ],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'step',
      state: 'placeholders',
      nameFound: null,
      step: 3,
      argv: [
        'block',
        'set',
        'next-steps#rows',
        '/items',
        '[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]',
      ],
      code: 0,
      answer: ['set rows /items on next-steps: revision 2, 2 finding(s)'],
      findings: [
        'next-steps#h copy/empty-placeholder (1): Slide 5 has an empty title. Type the copy or remove the placeholder.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
      ],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'tailor',
      state: 'titled',
      nameFound: true,
      step: null,
      argv: ['tailor', '--replace=Northwind=Globex'],
      code: 0,
      answer: ['7 replacements on 4 slides, 0 pictures swapped, 0 skipped; revision 3'],
      findings: [],
      names: {
        from: 'Northwind',
        to: 'Globex',
      },
    },
    {
      form: 'tailor',
      state: 'titled',
      nameFound: false,
      step: null,
      argv: ['tailor', '--replace=Initech=Globex'],
      code: 0,
      answer: ['0 replacements on 0 slides, 0 pictures swapped, 0 skipped; revision 2'],
      findings: [],
      names: {
        from: 'Initech',
        to: 'Globex',
      },
    },
    {
      form: 'version-list',
      state: 'titled',
      nameFound: null,
      step: null,
      argv: ['version', 'list'],
      code: 0,
      answer: [],
      findings: [
        '1  r1     2026-10-03T04:01:33.834Z  agent:landing      1 mutation(s): slide.insert',
        '2  r2     2026-10-03T04:01:34.707Z  agent:landing      1 mutation(s): block.set',
      ],
      names: null,
    },
    {
      form: 'step',
      state: 'titled',
      nameFound: null,
      step: 1,
      argv: ['slide', 'new', '--layout', 'rows', '--after', 'ships', '--id', 'next-steps'],
      code: 2,
      answer: ['turboslide: Slide "next-steps" exists already'],
      findings: [],
      names: null,
    },
    {
      form: 'step',
      state: 'titled',
      nameFound: null,
      step: 2,
      argv: ['block', 'set', 'next-steps#h', '/text', 'Next steps with Northwind'],
      code: 0,
      answer: ['set h /text on next-steps: revision 3, 8 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty key. Type the copy or remove the placeholder.',
        'next-steps#rows copy/empty-placeholder (1): Slide 5 has an empty value. Type the copy or remove the placeholder.',
      ],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'step',
      state: 'titled',
      nameFound: null,
      step: 3,
      argv: [
        'block',
        'set',
        'next-steps#rows',
        '/items',
        '[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]',
      ],
      code: 0,
      answer: ['set rows /items on next-steps: revision 3, 2 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
      ],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'tailor',
      state: 'filled',
      nameFound: true,
      step: null,
      argv: ['tailor', '--replace=Northwind=Globex'],
      code: 0,
      answer: ['8 replacements on 4 slides, 0 pictures swapped, 0 skipped; revision 4'],
      findings: [],
      names: {
        from: 'Northwind',
        to: 'Globex',
      },
    },
    {
      form: 'tailor',
      state: 'filled',
      nameFound: false,
      step: null,
      argv: ['tailor', '--replace=Initech=Globex'],
      code: 0,
      answer: ['0 replacements on 0 slides, 0 pictures swapped, 0 skipped; revision 3'],
      findings: [],
      names: {
        from: 'Initech',
        to: 'Globex',
      },
    },
    {
      form: 'version-list',
      state: 'filled',
      nameFound: null,
      step: null,
      argv: ['version', 'list'],
      code: 0,
      answer: [],
      findings: [
        '1  r1     2026-10-03T04:01:33.834Z  agent:landing      1 mutation(s): slide.insert',
        '2  r2     2026-10-03T04:01:34.707Z  agent:landing      1 mutation(s): block.set',
        '3  r3     2026-10-03T04:01:35.630Z  agent:landing      1 mutation(s): block.set',
      ],
      names: null,
    },
    {
      form: 'step',
      state: 'filled',
      nameFound: null,
      step: 1,
      argv: ['slide', 'new', '--layout', 'rows', '--after', 'ships', '--id', 'next-steps'],
      code: 2,
      answer: ['turboslide: Slide "next-steps" exists already'],
      findings: [],
      names: null,
    },
    {
      form: 'step',
      state: 'filled',
      nameFound: null,
      step: 2,
      argv: ['block', 'set', 'next-steps#h', '/text', 'Next steps with Northwind'],
      code: 0,
      answer: ['set h /text on next-steps: revision 4, 2 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
      ],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'step',
      state: 'filled',
      nameFound: null,
      step: 3,
      argv: [
        'block',
        'set',
        'next-steps#rows',
        '/items',
        '[\n{"key": "Monday", "value": "Northwind sellers get the deck"},\n{"key": "Wednesday", "value": "Agents draft slides over MCP"},\n{"key": "Friday", "value": "The first call uses this deck"}\n]',
      ],
      code: 0,
      answer: ['set rows /items on next-steps: revision 4, 2 finding(s)'],
      findings: [
        'next-steps#h copy/sentence-case (2): Sentence case: lowercase "Northwind" unless it is a proper noun. A proper noun goes on the list.',
        'next-steps#p1 copy/empty-placeholder (1): Slide 5 has an empty paragraph. Type the copy or remove the placeholder.',
      ],
      names: {
        from: 'Northwind',
        to: 'Northwind',
      },
    },
    {
      form: 'tailor-spaced',
      state: 'absent',
      nameFound: true,
      step: null,
      argv: ['tailor', '--replace', 'Northwind=Globex'],
      code: 2,
      answer: [
        'turboslide: tailor needs --replace, --skip or --logo',
        'usage: turboslide tailor --replace <from>=<to> [--replace <from>=<to>] [--skip <slideId>] [--logo <assetId> [--logo-alt <word>]]',
      ],
      findings: [
        '--replace <from>=<to>   the customer name as the deck spells it, and the name that takes its place (up to 20)',
        '--skip <slideId>        a slide to skip (repeatable)',
        '--logo <assetId>        the asset every picture whose alt text names --logo-alt takes',
        "--logo-alt <word>       the word the pictures' alt text names (with --logo)",
      ],
      names: {
        from: 'Northwind',
        to: 'Globex',
      },
    },
  ],
  tailorCounts: {
    start: {
      places: 6,
      slides: 3,
    },
    rest: {
      places: 8,
      slides: 4,
    },
  },
  screens: {
    banner: {
      wide: [
        '$ turboslide --version',
        ' ███████████  Turboslide 2026.1001.3',
        ' ▀▀▀▀▀███▀▀▀  https://www.turboslide.com',
        '▄▄▄▄▄ ███     193 actions, effects backend: wasm',
        '▄▄▄▄ ▄▄▄',
        '     ███',
        '███ ███',
      ],
      narrow: [
        '$ turboslide --version',
        ' ███████████  Turboslide 2026.1001.3',
        ' ▀▀▀▀▀███▀▀▀  https://www.turboslide.com',
        '▄▄▄▄▄ ███     193 actions, effects backend:',
        '              wasm',
        '▄▄▄▄ ▄▄▄',
        '     ███',
        '███ ███',
      ],
    },
    transcript: {
      wide: [
        '$ turboslide slide new --layout rows --after ships --id',
        '    next-steps',
        'new rows slide next-steps after ships: revision 1',
        '$ turboslide block set next-steps#h /text "Next steps with',
        '    Northwind"',
        'set h /text on next-steps: revision 2, 8 finding(s)',
        "$ turboslide block set next-steps#rows /items '[",
        '{"key": "Monday", "value": "Northwind sellers get the deck"},',
        '{"key": "Wednesday", "value": "Agents draft slides over MCP"},',
        '{"key": "Friday", "value": "The first call uses this deck"}',
        "]'",
        'set rows /items on next-steps: revision 3, 2 finding(s)',
      ],
      narrow: [
        '$ turboslide slide new --layout rows --after',
        '    ships --id next-steps',
        'new rows slide next-steps after ships:',
        '    revision 1',
        '$ turboslide block set next-steps#h /text',
        '    "Next steps with Northwind"',
        'set h /text on next-steps: revision 2, 8',
        '    finding(s)',
        '$ turboslide block set next-steps#rows',
        "    /items '[",
        '{"key": "Monday", "value": "Northwind',
        '    sellers get the deck"},',
        '{"key": "Wednesday", "value": "Agents draft',
        '    slides over MCP"},',
        '{"key": "Friday", "value": "The first call',
        '    uses this deck"}',
        "]'",
        'set rows /items on next-steps: revision 3, 2',
        '    finding(s)',
      ],
    },
    mcp: {
      wide: [
        'tools/call deck_new_slide {"layout": "rows", "after": "ships",',
        '    "id": "next-steps", "baseRevision": 0}',
        'tools/call deck_update_block {"slideId": "next-steps",',
        '    "blockId": "h", "path": "/text", "value": "Next steps with',
        '    Northwind", "baseRevision": 1}',
        'tools/call deck_update_block {"slideId": "next-steps",',
        '    "blockId": "rows", "path": "/items", "value": [{"key":',
        '    "Monday", "value": "Northwind sellers get the deck"},',
        '    {"key": "Wednesday", "value": "Agents draft slides over',
        '    MCP"}, {"key": "Friday", "value": "The first call uses this',
        '    deck"}], "baseRevision": 2}',
        'Request only. The CLI tab shows the recorded answer.',
      ],
      narrow: [
        'tools/call deck_new_slide {"layout": "rows",',
        '    "after": "ships", "id": "next-steps",',
        '    "baseRevision": 0}',
        'tools/call deck_update_block {"slideId":',
        '    "next-steps", "blockId": "h", "path":',
        '    "/text", "value": "Next steps with',
        '    Northwind", "baseRevision": 1}',
        'tools/call deck_update_block {"slideId":',
        '    "next-steps", "blockId": "rows", "path":',
        '    "/items", "value": [{"key": "Monday",',
        '    "value": "Northwind sellers get the',
        '    deck"}, {"key": "Wednesday", "value":',
        '    "Agents draft slides over MCP"}, {"key":',
        '    "Friday", "value": "The first call uses',
        '    this deck"}], "baseRevision": 2}',
        'Request only. The CLI tab shows the recorded',
        '    answer.',
      ],
    },
    http: {
      wide: [
        'POST /api/actions/slide.new {"layout": "rows", "after": "ships",',
        '    "id": "next-steps", "baseRevision": 0}',
        'POST /api/actions/block.set {"slideId": "next-steps", "blockId":',
        '    "h", "path": "/text", "value": "Next steps with Northwind",',
        '    "baseRevision": 1}',
        'POST /api/actions/block.set {"slideId": "next-steps", "blockId":',
        '    "rows", "path": "/items", "value": [{"key": "Monday",',
        '    "value": "Northwind sellers get the deck"}, {"key":',
        '    "Wednesday", "value": "Agents draft slides over MCP"},',
        '    {"key": "Friday", "value": "The first call uses this',
        '    deck"}], "baseRevision": 2}',
        'Request only. The CLI tab shows the recorded answer.',
      ],
      narrow: [
        'POST /api/actions/slide.new {"layout":',
        '    "rows", "after": "ships", "id":',
        '    "next-steps", "baseRevision": 0}',
        'POST /api/actions/block.set {"slideId":',
        '    "next-steps", "blockId": "h", "path":',
        '    "/text", "value": "Next steps with',
        '    Northwind", "baseRevision": 1}',
        'POST /api/actions/block.set {"slideId":',
        '    "next-steps", "blockId": "rows", "path":',
        '    "/items", "value": [{"key": "Monday",',
        '    "value": "Northwind sellers get the',
        '    deck"}, {"key": "Wednesday", "value":',
        '    "Agents draft slides over MCP"}, {"key":',
        '    "Friday", "value": "The first call uses',
        '    this deck"}], "baseRevision": 2}',
        'Request only. The CLI tab shows the recorded',
        '    answer.',
      ],
    },
    help: {
      wide: [
        '$ help',
        'This page runs these five commands.',
        'turboslide slide new --layout rows --after ships --id next-steps',
        'turboslide block set next-steps#h /text "<title>"',
        "turboslide block set next-steps#rows /items '<rows>'",
        'turboslide tailor --replace=<from>=<to>',
        'turboslide version list',
      ],
      narrow: [
        '$ help',
        'This page runs these five commands.',
        'turboslide slide new --layout rows --after',
        '    ships --id next-steps',
        'turboslide block set next-steps#h /text',
        '    "<title>"',
        'turboslide block set next-steps#rows /items',
        "    '<rows>'",
        'turboslide tailor --replace=<from>=<to>',
        'turboslide version list',
      ],
    },
  },
  cliCommands: 180,
  refusal: "This page runs 5 of the CLI's 180 commands.",
  gestures: [
    {
      argv: ['slide', 'to-canvas', 'rosetta'],
      answer: ['rosetta: arranged by hand (mood), 5 object(s)'],
    },
    {
      argv: ['block', 'set', 'rosetta#h', '/pos', '{"x":612,"y":388,"w":520,"h":96}'],
      answer: ['set h /pos on rosetta: revision 5, 2 finding(s)'],
    },
    {
      argv: ['block', 'rotate', 'rosetta#h', '--to', '15'],
      answer: ['rotated h to 15 degrees on rosetta: revision 6, 2 finding(s)'],
    },
  ],
};
