// Generated by scripts/build-home-assets.ts --run (docs/LANDING.md 2.4, 6.1); never edited by
// hand. Day 0 stub: the integrator wrote the types and placeholder values on day 0
// (docs/gslides-parity/landing/build/integrator.md "Landing, day 0", section 4.2); L1's push 1
// writes the values from the CLI's recorded answers.
//
// The route reads this module only behind `import.meta.env.SSR` (the agents band's resting
// screen and the MCP and HTTP tab panels are server markup); the live module imports it, so it
// travels in the live chunk. Every row reads the commands from here, never from literal text.
import type { HomeObjectId, HomeSlideId } from './deck.generated';

/** A screen formatted by panel-format.ts at both widths: 64 columns and 44 columns. */
export type PanelText = { wide: readonly string[]; narrow: readonly string[] };

export type RunLanding =
  { kind: 'rails' } | { kind: 'words'; chars: number } | { kind: 'rows'; count: number };

/** The step's scheduled lengths in ms (docs/LANDING.md 2.4, A1 to A6), with the fixture's name. */
export type RunSchedule = {
  /** typed characters times 24 ms (A1) */
  type: number;
  /** 200 ms, then 120 ms and 55 ms a further line (A2) */
  answer: number;
  /** the 500 ms beat */
  beat: number;
  /** 300 ms plus the distance over two, at most 700 ms (A3) */
  ring: number;
  /** the landing (A4, A5) */
  land: number;
  /** the flag's 800 ms hold and 160 ms exit */
  flag: number;
  total: number;
};

export type RunStep = {
  n: 1 | 2 | 3;
  action: 'slide.new' | 'block.set';
  /** the arguments after `turboslide`, as the CLI received them */
  argv: readonly string[];
  /** the command as the panel prints it, `turboslide ...`, the newlines inside its quotes kept */
  command: string;
  /** the characters typed at 24 ms: the command up to its value (A1); a JSON value pastes whole */
  typedChars: number;
  /** the CLI's human answer, one or two lines (`apps/cli/src/write.ts` 207 to 213) */
  answer: readonly string[];
  /** the revision the CLI read before the step, the bodies' `baseRevision` */
  revisionBefore: string;
  /** the `tools/call` params: the tool of mcp-tools.json and its arguments */
  mcp: { name: string; arguments: Readonly<Record<string, unknown>> };
  /** the request of openapi.json */
  http: { method: 'POST'; path: string; body: Readonly<Record<string, unknown>> };
  /** where the agent's ring travels */
  target: HomeObjectId | HomeSlideId;
  landing: RunLanding;
  schedule: RunSchedule;
  /** the Version history row's words */
  history: string;
};

/** The deck states the typed line can meet (slide 5 absent, placeholders, titled, filled). */
export type RunDeckState = 'absent' | 'placeholders' | 'titled' | 'filled';

/** One recorded answer to a typed form (docs/LANDING.md 2.4, "The typed line"). */
export type TypedRecording = {
  form: 'tailor' | 'version-list' | 'step';
  state: RunDeckState;
  /** for `tailor`: whether the deck held the name; null otherwise */
  nameFound: boolean | null;
  /** for `step`: the step run out of order; null otherwise */
  step: 1 | 2 | 3 | null;
  argv: readonly string[];
  answer: readonly string[];
  /** the names the recording was made with, which the page substitutes; null when none */
  names: { from: string; to: string } | null;
};

export type HomeRun = {
  /** `turboslide --version`'s version, equal to the banner's */
  cliVersion: string;
  /** the banner, unformatted, the CLI's own lines */
  banner: readonly string[];
  steps: readonly [RunStep, RunStep, RunStep];
  /** the sum of the three schedules with the fixture's name */
  totalMs: number;
  /** totalMs in whole seconds, the caption's figure */
  captionSeconds: number;
  /** the help lines: the five commands this page runs */
  help: readonly string[];
  typed: readonly TypedRecording[];
  /** `tailor --replace Northwind=Globex` on the fixture (7 slides) and on the page deck (8) */
  tailorCounts: {
    start: { places: number; slides: number };
    rest: { places: number; slides: number };
  };
  /** the banner screen and the resting transcript, formatted and checked against the slots */
  screens: { banner: PanelText; transcript: PanelText };
};

const STUB_SCHEDULE: RunSchedule = {
  type: 0,
  answer: 0,
  beat: 500,
  ring: 0,
  land: 0,
  flag: 960,
  total: 0,
};

const STUB_STEP = (n: 1 | 2 | 3, target: HomeObjectId | HomeSlideId): RunStep => ({
  n,
  action: n === 1 ? 'slide.new' : 'block.set',
  argv: [],
  command: '',
  typedChars: 0,
  answer: [],
  revisionBefore: '',
  mcp: { name: '', arguments: {} },
  http: { method: 'POST', path: '', body: {} },
  target,
  landing:
    n === 1
      ? { kind: 'rails' }
      : n === 2
        ? { kind: 'words', chars: 0 }
        : { kind: 'rows', count: 3 },
  schedule: STUB_SCHEDULE,
  history: '',
});

export const HOME_RUN: HomeRun = {
  cliVersion: '',
  banner: [],
  steps: [
    STUB_STEP(1, 'next-steps'),
    STUB_STEP(2, 'next-steps#h'),
    STUB_STEP(3, 'next-steps#rows'),
  ],
  totalMs: 0,
  captionSeconds: 0,
  help: [],
  typed: [],
  tailorCounts: { start: { places: 0, slides: 0 }, rest: { places: 0, slides: 0 } },
  screens: { banner: { wide: [], narrow: [] }, transcript: { wide: [], narrow: [] } },
};
