// Generated by scripts/build-home-assets.ts from shots.json; do not edit by hand. The
// pictures of the /home page with their candidates (docs/POLISH.md 3.3): the same records as
// shots.json, as a module the studio project can import (its tsconfig reaches no JSON file).
export type ShotVariant = {
  path: string;
  scale: 1 | 2;
  width: number;
  height: number;
  bytes: number;
  sha256: string;
};
export type ChromeRecord = { mark: boolean; menubar: string[]; extensions: boolean };
export type ShotRecord = {
  name: string;
  kind: 'hero' | 'canvas' | 'menus';
  theme: 'dark' | 'light';
  format: 'jpeg' | 'png';
  width: number;
  height: number;
  variants: ShotVariant[];
  chrome: ChromeRecord;
};
export type ShotsManifest = {
  generatedBy: string;
  capturedAt: string;
  commit: string;
  deck: string;
  slide: string;
  viewport: { width: number; height: number };
  scale: number;
  quality: number;
  shots: ShotRecord[];
};

export const SHOTS_MANIFEST: ShotsManifest = {
  generatedBy: 'scripts/build-home-assets.ts',
  capturedAt: '2026-09-29T02:23:22.705Z',
  commit: '14612488',
  deck: 'gt-brand',
  slide: 'mood-earth',
  viewport: {
    width: 1440,
    height: 900,
  },
  scale: 2,
  quality: 82,
  shots: [
    {
      name: 'hero-dark',
      kind: 'hero',
      theme: 'dark',
      format: 'jpeg',
      width: 1440,
      height: 900,
      variants: [
        {
          path: '/home/hero-dark-2x-dfd9c8d761.jpg',
          scale: 2,
          width: 2880,
          height: 1800,
          bytes: 395602,
          sha256: 'dfd9c8d761239ae7eea3f9d87d9400a8516e04a1ddd42a63639e9f46a6751152',
        },
        {
          path: '/home/hero-dark-ba3e172d10.jpg',
          scale: 1,
          width: 1440,
          height: 900,
          bytes: 154628,
          sha256: 'ba3e172d10584c03feedd2c17db372b607303e451998008705f2cc0e186423cc',
        },
      ],
      chrome: {
        mark: true,
        menubar: ['File', 'Edit', 'View', 'Insert', 'Format', 'Slide', 'Arrange', 'Tools', 'Help'],
        extensions: false,
      },
    },
    {
      name: 'canvas-dark',
      kind: 'canvas',
      theme: 'dark',
      format: 'png',
      width: 612,
      height: 400,
      variants: [
        {
          path: '/home/canvas-dark-2x-525ba0e769.png',
          scale: 2,
          width: 1224,
          height: 800,
          bytes: 104117,
          sha256: '525ba0e7699454c6eb64e2166d9ba167f83df5c2e1ad84a20872f130e3d3621f',
        },
        {
          path: '/home/canvas-dark-adab5434a8.png',
          scale: 1,
          width: 612,
          height: 400,
          bytes: 39142,
          sha256: 'adab5434a8999a2890bf9a30d8d73e84ee611aa154ec40cdf2a336841724bf24',
        },
      ],
      chrome: {
        mark: true,
        menubar: ['File', 'Edit', 'View', 'Insert', 'Format', 'Slide', 'Arrange', 'Tools', 'Help'],
        extensions: false,
      },
    },
    {
      name: 'menus-dark',
      kind: 'menus',
      theme: 'dark',
      format: 'png',
      width: 612,
      height: 505,
      variants: [
        {
          path: '/home/menus-dark-2x-2d19e0a345.png',
          scale: 2,
          width: 1224,
          height: 1010,
          bytes: 171841,
          sha256: '2d19e0a345454326e38aa7d7baf6e50e57c90943795ea6fa7fbcc631cda11f98',
        },
        {
          path: '/home/menus-dark-7e1af41db7.png',
          scale: 1,
          width: 612,
          height: 505,
          bytes: 67213,
          sha256: '7e1af41db71aaf3a50c734518d9f8cd275eb267138e72f06f788d5f28f24b5af',
        },
      ],
      chrome: {
        mark: true,
        menubar: ['File', 'Edit', 'View', 'Insert', 'Format', 'Slide', 'Arrange', 'Tools', 'Help'],
        extensions: false,
      },
    },
    {
      name: 'hero-light',
      kind: 'hero',
      theme: 'light',
      format: 'jpeg',
      width: 1440,
      height: 900,
      variants: [
        {
          path: '/home/hero-light-2x-d6106a0704.jpg',
          scale: 2,
          width: 2880,
          height: 1800,
          bytes: 392483,
          sha256: 'd6106a07049a72cf748d1aa8d412141e341139d6a041c71a9b9185bc4ddb8469',
        },
        {
          path: '/home/hero-light-fdb7c9b176.jpg',
          scale: 1,
          width: 1440,
          height: 900,
          bytes: 153286,
          sha256: 'fdb7c9b176bf53c8efe766aed683d1277d71ac69d61942cc49b38d36f9d4dc5b',
        },
      ],
      chrome: {
        mark: true,
        menubar: ['File', 'Edit', 'View', 'Insert', 'Format', 'Slide', 'Arrange', 'Tools', 'Help'],
        extensions: false,
      },
    },
    {
      name: 'canvas-light',
      kind: 'canvas',
      theme: 'light',
      format: 'png',
      width: 612,
      height: 400,
      variants: [
        {
          path: '/home/canvas-light-2x-09aa8d9a15.png',
          scale: 2,
          width: 1224,
          height: 800,
          bytes: 106228,
          sha256: '09aa8d9a1587581061f3005682160ea7f4218e8fa4e5609fefc94ce6bd41360f',
        },
        {
          path: '/home/canvas-light-21a170e381.png',
          scale: 1,
          width: 612,
          height: 400,
          bytes: 39016,
          sha256: '21a170e38116eae2908781fe494296919a5f13b713bc259fa9b7d2fdc3de9c46',
        },
      ],
      chrome: {
        mark: true,
        menubar: ['File', 'Edit', 'View', 'Insert', 'Format', 'Slide', 'Arrange', 'Tools', 'Help'],
        extensions: false,
      },
    },
    {
      name: 'menus-light',
      kind: 'menus',
      theme: 'light',
      format: 'png',
      width: 612,
      height: 505,
      variants: [
        {
          path: '/home/menus-light-2x-fbf9d72b74.png',
          scale: 2,
          width: 1224,
          height: 1010,
          bytes: 187210,
          sha256: 'fbf9d72b7490a5ea27da41b3235e1b9ec7361a858911f768e99d30b1dfd664d8',
        },
        {
          path: '/home/menus-light-aa2b00e489.png',
          scale: 1,
          width: 612,
          height: 505,
          bytes: 68954,
          sha256: 'aa2b00e48993a66d726e3fab42b7d2b957b2599046a1144c602f54d2b2d24d2a',
        },
      ],
      chrome: {
        mark: true,
        menubar: ['File', 'Edit', 'View', 'Insert', 'Format', 'Slide', 'Arrange', 'Tools', 'Help'],
        extensions: false,
      },
    },
  ],
};
