// Generated by scripts/build-home-assets.ts --slides and --stills (docs/LANDING.md 2.0, 2.2, 2.3,
// 6.1); never edited by hand. Day 0 stub: the integrator wrote the types and placeholder values on
// day 0 (docs/gslides-parity/landing/build/integrator.md "Landing, day 0", section 4.2); L1's
// push 1 writes the values.
//
// Server only. `HomeSheet` and `HomeField` read this module behind `import.meta.env.SSR`, which
// the client build folds to false so Rollup drops the module from the route chunk; on the client
// they render the same element with an empty `dangerouslySetInnerHTML` and
// `suppressHydrationWarning`, which React leaves untouched after hydration. The route chunk must
// never contain `HOME_SLIDES_SENTINEL` (row home.budget.bytes-first).
import type { HomeSlideId } from './deck.generated';

/** The attribute on the root of every server rendered slide instance (docs/LANDING.md 6.3). */
export const HOME_SLIDES_SENTINEL = 'data-home-slides';

/** The ten slide instances in the markup (docs/LANDING.md 2.0), by the band that holds each. */
export type HomeInstanceId =
  | 'hero'
  | 'agents'
  | 'tailor-stage'
  | 'tailor-thumb-plan'
  | 'tailor-thumb-gets'
  | 'tailor-thumb-ships'
  | 'tailor-thumb-next-steps'
  | 'canvas'
  | 'present'
  | 'close';

export type HomeSlideInstance = {
  instance: HomeInstanceId;
  slide: HomeSlideId;
  /**
   * `renderSlide` output in its appearance neutral form: the sheet's `data-theme` and the picture
   * sources removed, every picture replaced by the page's print or hashed still, every heading
   * element outside the hero rewritten to a `div` (the page's outline is its own), the root
   * carrying `data-home-slides`, `data-slide` and `data-counter`, every selectable block wrapped
   * in its `data-object`.
   */
  html: string;
};

/**
 * One 1 bit still of a field (docs/LANDING.md 2.2, 2.3): a PNG of the cell grid at 2 px cells,
 * inlined once as a data URI and drawn as a CSS mask over a box filled with the kit's ink, so one
 * still serves every kit. The live module decodes it from the element's `--ts-still` custom
 * property and never carries its own copy.
 */
export type FieldStill = {
  cols: number;
  rows: number;
  /** data:image/png;base64,... with ink where the light print inks */
  ink: string;
  /**
   * The hero only (answer 1): the disc's cells. A dark ground prints the disc XOR the ink, which
   * equals the dark print through the complementary screen (63 - m), so the Earth never draws as
   * its negative. Null on the strip.
   */
  disc: string | null;
};

export type FieldStillPair = { wide: FieldStill; narrow: FieldStill };

export const HOME_SLIDE_HTML: Readonly<Record<HomeInstanceId, HomeSlideInstance>> = {
  hero: { instance: 'hero', slide: 'title', html: '' },
  agents: { instance: 'agents', slide: 'next-steps', html: '' },
  'tailor-stage': { instance: 'tailor-stage', slide: 'plan', html: '' },
  'tailor-thumb-plan': { instance: 'tailor-thumb-plan', slide: 'plan', html: '' },
  'tailor-thumb-gets': { instance: 'tailor-thumb-gets', slide: 'gets', html: '' },
  'tailor-thumb-ships': { instance: 'tailor-thumb-ships', slide: 'ships', html: '' },
  'tailor-thumb-next-steps': {
    instance: 'tailor-thumb-next-steps',
    slide: 'next-steps',
    html: '',
  },
  canvas: { instance: 'canvas', slide: 'rosetta', html: '' },
  present: { instance: 'present', slide: 'gets', html: '' },
  close: { instance: 'close', slide: 'close', html: '' },
};

const STUB_STILL = (cols: number, rows: number, disc: boolean): FieldStill => ({
  cols,
  rows,
  ink: '',
  disc: disc ? '' : null,
});

/** The two inlined stills: the hero's Blue Marble and the field strip, each at both widths. */
export const HOME_FIELD_STILLS: Readonly<{ hero: FieldStillPair; strip: FieldStillPair }> = {
  hero: { wide: STUB_STILL(512, 288, true), narrow: STUB_STILL(179, 100, true) },
  strip: { wide: STUB_STILL(512, 80, false), narrow: STUB_STILL(179, 48, false) },
};
