// Generated by scripts/build-home-assets.ts --slides (docs/DESIGN.md 8.7); never edited by hand.
// node scripts/build-home-assets.ts --check compares this file with its sources.
//
// The theme library's nine tiles (packages/theme/src/themes.ts THEME_RECORDS): each theme's id,
// name, sentence and the paper and ink of each appearance.
export type HomeThemeTile = {
  id: string;
  name: string;
  sentence: string;
  light: { paper: string; ink: string };
  dark: { paper: string; ink: string };
};

export const HOME_THEME_TILES: readonly HomeThemeTile[] = [
  {
    id: 'simple',
    name: 'Simple',
    sentence: 'Ink on paper in Inter with nothing else on the slide.',
    light: {
      paper: '#ffffff',
      ink: '#070707',
    },
    dark: {
      paper: '#070707',
      ink: '#f2f2f0',
    },
  },
  {
    id: 'general-translation',
    name: 'General Translation',
    sentence:
      'The brand deck: rails, rules and crosses, the GT mark on the title slide, the wordmark, the slide counter and the four dithered pictures.',
    light: {
      paper: '#ffffff',
      ink: '#070707',
    },
    dark: {
      paper: '#070707',
      ink: '#f2f2f0',
    },
  },
  {
    id: 'swiss',
    name: 'Swiss',
    sentence:
      'A red bar over each heading, the title at the top left, one rule across the top and the slide number.',
    light: {
      paper: '#ffffff',
      ink: '#111111',
    },
    dark: {
      paper: '#111111',
      ink: '#f4f4f2',
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    sentence: 'A mint ground with deep green ink and the title in the centre.',
    light: {
      paper: '#e8f3ee',
      ink: '#0d271d',
    },
    dark: {
      paper: '#0b1f18',
      ink: '#e4f2eb',
    },
  },
  {
    id: 'coral',
    name: 'Coral',
    sentence: 'A warm ground with coral as the accent and the title at the bottom left.',
    light: {
      paper: '#fff2ec',
      ink: '#2a130e',
    },
    dark: {
      paper: '#1f0f0b',
      ink: '#fbe9e3',
    },
  },
  {
    id: 'night',
    name: 'Night',
    sentence:
      'A navy ground for dark rooms, with rules at the top and bottom and the slide number.',
    light: {
      paper: '#f2f5fa',
      ink: '#0c1424',
    },
    dark: {
      paper: '#0c1424',
      ink: '#edf1f7',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    sentence:
      'A cool grey ground with a steel blue accent, rules at the top and bottom and the slide number.',
    light: {
      paper: '#edf0f3',
      ink: '#1a1f26',
    },
    dark: {
      paper: '#1a1f26',
      ink: '#eef1f4',
    },
  },
  {
    id: 'sand',
    name: 'Sand',
    sentence: 'A warm paper ground with ochre as the accent and the title in the centre.',
    light: {
      paper: '#f5efe4',
      ink: '#28231d',
    },
    dark: {
      paper: '#211c16',
      ink: '#f3ece0',
    },
  },
  {
    id: 'signal',
    name: 'Signal',
    sentence:
      'Black and white at the highest contrast with a yellow bar over each heading, for bright rooms and projectors.',
    light: {
      paper: '#ffffff',
      ink: '#000000',
    },
    dark: {
      paper: '#000000',
      ink: '#ffffff',
    },
  },
];

/** The page deck's theme at rest (DESIGN.md 7.9 rule 1). */
export const HOME_THEME_AT_REST = 'general-translation';
