// Generated by scripts/build-home-assets.ts (--help-titles) from the first heading of
// docs/training.md and docs/updates.md; do not edit by hand. The two help routes read their page
// titles here so their `head` holds no copy of the documents in the entry chunk (gslides-parity
// SPEC-5 7.6; VERIFICATION-5 finding 10); `--check` fails when a heading moved since this copy.
export const HELP_TITLES = {
  training: 'Training',
  updates: 'Updates',
} as const;
