import { DEFAULT_MENU_CONTEXT } from '@turboslide/chrome/menus/model';
import type { ShortcutGroup } from '@turboslide/chrome/menus/keys';

/**
 * The Keyboard shortcuts page, content/docs/shortcuts.mdx (docs/POLISH-2.md 5.3), written from
 * the data of the editor's Keyboard shortcuts dialog: `shortcutRows` over the key table of the
 * menu model (packages/chrome/src/menus/keys.ts and model.ts) in the default view, the dialog's
 * group order, the Mac chord and the Windows chord of every row. generated-pages.test.ts compares
 * the committed page with this output and writes it with `vitest run -u`.
 */
export type ShortcutRowsOf = (
  platform: 'mac' | 'win',
  table?: undefined,
  context?: typeof DEFAULT_MENU_CONTEXT,
) => Map<ShortcutGroup, { id: string; label: string; keys: string[]; later: boolean }[]>;

/** A table cell's text with MDX's and markdown's special characters escaped. */
export function cell(text: string): string {
  return text.replace(/[\\|<>{}*_`[\]]/g, (char) => `\\${char}`);
}

/** A markdown table padded to its widest cells, the form prettier writes. */
function table(head: string[], rows: string[][]): string {
  const all = [head, ...rows];
  const widths = head.map((_, at) => Math.max(3, ...all.map((row) => (row[at] ?? '').length)));
  const line = (row: string[]): string =>
    `| ${row.map((text, at) => text.padEnd(widths[at] ?? 3)).join(' | ')} |`;
  return [
    line(head),
    `| ${widths.map((width) => '-'.repeat(width)).join(' | ')} |`,
    ...rows.map(line),
  ].join('\n');
}

const HEAD = `---
# Generated by apps/studio/src/docs/generated-pages.test.ts from the key table of
# packages/chrome/src/menus/keys.ts and model.ts; do not edit by hand.
title: Keyboard shortcuts
description: Every keyboard shortcut the editor answers in its default view, with the key on a Mac and on Windows.
---

These are the keys the Keyboard shortcuts dialog lists. Open it in the editor with Help > Keyboard shortcuts, or press Cmd+/ (Ctrl+/ on Windows), and type in its search box to find a key. Every row is also a command in a menu, so Help > Search the menus finds it by name.

Turning on Tools > Advanced tools adds the keys of the commands behind it. See [Advanced tools](/docs/editor/advanced-tools).
`;

export function shortcutsMdx(rowsOf: ShortcutRowsOf, groups: readonly ShortcutGroup[]): string {
  const mac = rowsOf('mac', undefined, DEFAULT_MENU_CONTEXT);
  const win = rowsOf('win', undefined, DEFAULT_MENU_CONTEXT);
  const parts = [HEAD];
  for (const group of groups) {
    const rows = (mac.get(group) ?? []).filter((row) => !row.later);
    if (rows.length === 0) continue;
    const windows = new Map((win.get(group) ?? []).map((row) => [row.id, row]));
    const cells = rows.map((row) => [
      cell(row.label),
      cell(row.keys.join(', ')),
      cell((windows.get(row.id)?.keys ?? []).join(', ')),
    ]);
    parts.push(`## ${group}\n\n${table(['Action', 'Mac', 'Windows'], cells)}\n`);
  }
  return parts.join('\n');
}
