// docs/grammar.md (SPEC 7.1, 7.5): the grammar as a document generated from the schema's catalog
// and rule table, so the prose an agent reads and the code an agent runs cannot disagree. The same
// text is the turboslide-create skill's reference file.
import { BLOCK_TYPES } from '@turboslide/schema/blocks';
import {
  BLOCK_GROUPS,
  CATALOG,
  LAYOUT_CATALOG,
  SLIDE_KIND_CATALOG,
} from '@turboslide/schema/catalog';
import { SLIDE_KINDS, SLOT_NAMES } from '@turboslide/schema/deck';
import { ICON_NAMES } from '@turboslide/schema/icons';
import { CONTENT_BOX, RAIL_PX, SHEET_HEIGHT, SHEET_WIDTH } from '@turboslide/schema/render';
import { rulesInOrder } from '@turboslide/schema/rules';
import { markdownTable, summarizeProperties, toJsonSchema } from './json-schema.ts';

const GENERATED =
  'Generated by `pnpm generate:contracts` from `packages/schema/src/{catalog,rules,blocks,deck}.ts`; do not edit by hand. The rules of the grammar are quoted from `Prototemplate/deck/DECK-GRAMMAR.md` and the specification.';

function propertyTable(
  schema: Parameters<typeof toJsonSchema>[0],
  skip: ReadonlySet<string>,
): string {
  const rows = summarizeProperties(toJsonSchema(schema))
    .filter((property) => !skip.has(property.name))
    .map((property) => [
      `\`${property.name}\``,
      property.type,
      property.required ? 'yes' : 'no',
      property.title ?? '',
      property.description ?? '',
    ]);
  return markdownTable(['Property', 'Type', 'Required', 'Label', 'Note'], rows);
}

export function generateGrammar(): string {
  const parts: string[] = [];
  parts.push('# Turboslide grammar', '', GENERATED, '');

  parts.push('## The sheet', '');
  parts.push(
    `The sheet is ${SHEET_WIDTH} by ${SHEET_HEIGHT} px by default; \`deck.page\` (File > Page setup, \`deck.setPageSize\`; gslides-parity SPEC-5 6.1) sets another size, and every measure below is the default page's, derived from \`deckPage(deck)\` on another. Two vertical rails at ${RAIL_PX} px from the left and right edges, two horizontal rules at ${RAIL_PX} px from the top and bottom, an 11 by 11 registration cross at each junction, all drawn by the stage and never by a slide. The slide box is inset 57 px with 72 by 80 padding, so the content box is ${CONTENT_BOX[2]} by ${CONTENT_BOX[3]} at (${CONTENT_BOX[0]}, ${CONTENT_BOX[1]}). Nothing may leave the sheet, and text must not touch the rails or rules (DECK-GRAMMAR.md:15). Every other constant of the theme (tokens, the type ladder, column widths, plate sizes) is data in \`packages/theme/src/tokens.ts\`, parity tested against \`sheet.css\`.`,
    '',
  );
  parts.push(
    'Type is Inter only. Display weight is capped at 500; text under 15 px on the sheet is a defect; SVG labels never go under 18 px (DECK-GRAMMAR.md:20-21). Color is the nine tokens; the four semantic hues appear only on icons (DECK-GRAMMAR.md:28-30). The primitive blocks take a `Color`: a palette token (`ink`, `paper`, `ink-2`, `titanium`, `hair`, `hair-soft`, `plate`, `edge`, `green`, `amber`, `red`, `blue`) that follows the theme, or a custom `#rrggbb` that the linter flags as `color/off-palette` at severity 2. A heading, paragraph, text or box may carry `typography` (size from the ladder, weight 300 to 700, align, tracking in em, leading); a weight over 500 is `type/weight-cap` and a size off the ladder is `type/ladder`, both with a fix (docs/freeform.md).',
    '',
  );

  parts.push('## Text markup', '');
  parts.push(
    'A `Text` is a string in a four-rule inline markup (SPEC 4.2). Nothing else is markup.',
    '',
  );
  parts.push(
    markdownTable(
      ['Rule', 'Meaning'],
      [
        ['`*text*`', 'The display run: weight 500, the deck’s `<b>`'],
        [
          '`[text](https://…)`',
          'A link; inside a rows block with `links` the external glyph follows it',
        ],
        [
          '`GT`',
          'A standalone GT word becomes the mark at render; the document keeps the letters. Not inside a panel or a link',
        ],
        ['`\\*`, `\\[`, `\\GT`', 'Escapes; the validator stores the canonical form'],
      ],
    ),
    '',
  );
  parts.push(
    'No line breaks inside a Text except in `panel.code`, where `\\n` is honored. A non-breaking space (U+00A0) is the nowrap device.',
    '',
  );

  parts.push('## Addressing', '');
  parts.push(
    'A slide is its slug id, never a number (`content-rule`); numbers derive from the manifest’s section order. A block is `slideId#blockId` (`content-rule#list`). A field is a JSON pointer inside the slide or the block (`/slots/right/0/items/3/text`); a run inside a text is a pointer plus a character range. In the grammar layouts slots and ids are the only coordinates: there are no x, y, z-order or rotation (SPEC 1, 4.3). The `freeform` layout is the one exception (Kevin, 2026-09-11): every top-level block of a freeform slide carries `pos`, its `{ x, y, w, h, z }` box on the sheet (the deck’s page, 1600 by 900 by default), snapped to the 8 px grid, the rails and rules, the content box, the column seams and the plate edges; `pos` is refused anywhere else, and a freeform slide is flagged `layout/freeform` at severity 1 so a pure-grammar deck knows (docs/freeform.md).',
    '',
  );

  parts.push('### Comment anchors', '');
  parts.push(
    'A comment names a place with an anchor (gslides-parity SPEC-3 5.9): the deck (`deck`), a slide (`slide:<slideId>`), its speaker notes (`notes:<slideId>`), a block (`<slideId>#<blockId>`), a table cell (`<slideId>#<blockId>/cell:<row>,<col>`, zero based) or a range of the plain text at a Text pointer of a block (`<slideId>#<blockId>/text:<start>-<end>`, one character per paragraph break). Text anchors move with the text on every write; an anchor whose target is gone is reported as orphaned with its reason and kept.',
    '',
  );

  parts.push('## Slide kinds', '');
  parts.push(
    markdownTable(
      ['Kind', 'Label', 'Plate', 'Description', 'Source'],
      SLIDE_KINDS.map((kind) => {
        const entry = SLIDE_KIND_CATALOG[kind];
        const plate =
          entry.plate === undefined
            ? ''
            : `${entry.plate.side}, max ${entry.plate.maxWidth} px${entry.plate.titleSize === undefined ? '' : `, title ${entry.plate.titleSize} px`}`;
        return [`\`${kind}\``, entry.label, plate, entry.doc, entry.source];
      }),
    ),
    '',
  );
  parts.push(
    'Archetype anatomy. An opener’s plate is lower left at 740 px: the section title as a `big` heading, one paragraph that lists the section’s slide families in the order they appear, a 15 px credit. A mood slide’s plate is lower right at 560 px: the picture’s title at 44 px (`heading` with level `title`), one or two sentences on why the picture is in the deck, the credit. The credit is 15 px titanium and is required for share-alike sources. A mood slide follows a dense content slide and at least one content slide separates it from the next opener (OPENERS.md:137). The closing plate is upper left at 720 px with the mark above the thesis.',
    '',
  );
  for (const kind of SLIDE_KINDS) {
    parts.push(`### \`${kind}\``, '');
    parts.push(
      propertyTable(SLIDE_KIND_CATALOG[kind].schema, new Set(['schemaVersion', 'kind', 'ext'])),
      '',
    );
  }

  parts.push('## Layouts', '');
  parts.push(
    markdownTable(
      ['Layout', 'Label', 'Slots', 'Description', 'Source'],
      Object.values(LAYOUT_CATALOG).map((entry) => [
        `\`${entry.type}\``,
        entry.label,
        entry.slots.map((slot) => `\`${slot}\``).join(', '),
        entry.doc,
        entry.source,
      ]),
    ),
    '',
  );
  parts.push(
    `Slot names: ${SLOT_NAMES.map((slot) => `\`${slot}\``).join(', ')}, plus \`plate\` for the blocks of a full-picture slide. A content slide lists only the slots its layout has; a slot outside the layout is a validation error.`,
    '',
  );

  parts.push('## Blocks', '');
  parts.push(
    markdownTable(
      ['Type', 'Label', 'Group', 'Allowed in', 'Export', 'Description', 'Source'],
      BLOCK_TYPES.map((type) => {
        const entry = CATALOG[type];
        return [
          `\`${type}\``,
          entry.label,
          entry.group,
          entry.allowedIn.join(', '),
          entry.export,
          entry.doc,
          entry.source,
        ];
      }),
    ),
    '',
  );
  parts.push(
    `Groups: ${BLOCK_GROUPS.map((group) => `${group.label} (\`${group.id}\`)`).join(', ')}. Export says how the block leaves in native PPTX mode: native text and shapes, a raster, or mixed (native caption around a raster picture).`,
    '',
  );
  for (const type of BLOCK_TYPES) {
    const entry = CATALOG[type];
    parts.push(`### \`${type}\``, '', entry.doc, '');
    const facts: string[] = [];
    if (entry.textPaths.length > 0)
      facts.push(`Text fields: ${entry.textPaths.map((path) => `\`${path}\``).join(', ')}.`);
    if (entry.assetPaths.length > 0)
      facts.push(`Asset references: ${entry.assetPaths.map((path) => `\`${path}\``).join(', ')}.`);
    if (entry.iconPaths.length > 0)
      facts.push(`Icons: ${entry.iconPaths.map((path) => `\`${path}\``).join(', ')}.`);
    if (facts.length > 0) parts.push(facts.join(' '), '');
    parts.push(propertyTable(entry.schema, new Set(['id', 'type', 'ext'])), '');
  }

  parts.push('## Icons', '');
  parts.push(
    `Heroicons 20 solid from the sprite, written by the renderer as \`<svg class="ic ok" aria-hidden="true"><use href="#i-check-circle"/></svg>\`. An icon sits only in a rows key, at the start of a plain row, in a board state or inside a declared diagram, at 20 px on rows and 24 px on plain lists, never inside a sentence (DECK-GRAMMAR.md:40). Colors: \`ok\` green for done or passing, \`warn\` amber for open or in review, \`no\` red for excluded or rejected, \`info\` GT blue for GT itself; none for a monochrome category glyph. The ${ICON_NAMES.length} names: ${ICON_NAMES.map((name) => `\`${name}\``).join(', ')}.`,
    '',
  );

  parts.push('## Copy rules', '');
  parts.push(
    'Headings have no trailing period; sentences in body copy do. Headings are plain nouns or plain statements in sentence case: a capital first letter, proper nouns capitalized (General Translation, Prototemplate, Glyphfield, Locadex, Inter, Heroicons), product tokens in their exact form (gt-next, gt, npx, CLI, API) and never as the first word, and a heading is a name, not a URL. Straight technical English: no metaphors, no “X, not Y” contrast pairs, no fragment rhythm, no comma-tail headings, no em dashes, no exclamation marks, no eyebrow labels above headings. Full sentences even in captions. Title Case only on buttons (DECK-GRAMMAR.md:22-23). The lists live in `packages/theme/src/copy.ts`.',
    '',
  );

  parts.push('## Lint rules', '');
  parts.push(
    'Severity 3 must fix (the gate), 2 should fix, 1 polish. `Fix` marks rules whose findings carry mechanical `fix` mutations for `turboslide fix` and the inspector’s Fix button (SPEC 7.7).',
    '',
  );
  parts.push(
    markdownTable(
      ['Rule id', 'Layer', 'Severity', 'Kind', 'Check', 'Fix', 'Source'],
      rulesInOrder().map((rule) => [
        `\`${rule.id}\``,
        rule.layer,
        String(rule.severity),
        rule.kind,
        rule.check,
        rule.fix ? 'yes' : 'no',
        rule.source,
      ]),
    ),
    '',
  );
  parts.push(
    'Metaphors, fragment rhythm and comma-tail headings stay with the copy judge; the linter flags candidates at severity 1 only.',
    '',
  );

  parts.push('## What a defect is', '');
  parts.push(
    'Overflow past the sheet or into the margins; text under 15 px; a label crossing a line; misaligned columns; a slider marker or chart mark that does not match its value; contradictory numbers between slides; a screenshot that is stretched or cropped through content; unequal gaps in a pair; low contrast in either theme; empty half-slides; sentence-case violations; heading periods; comma-tail headings; metaphors (DECK-GRAMMAR.md:61).',
    '',
  );
  return `${parts.join('\n').trimEnd()}\n`;
}
