// The four skills' reference tables (SPEC 7.5), generated from the action table and the rule
// table so each SKILL.md stays under 50 lines and points at one current reference file.
import { actionsInOrder, actionsOn } from '@turboslide/schema/actions';
import { findingSchema } from '@turboslide/schema/findings';
import { rulesInOrder } from '@turboslide/schema/rules';
import { generateDescribe } from './describe.ts';
import { generateGrammar } from './grammar.ts';
import { markdownTable, summarizeProperties, toJsonSchema } from './json-schema.ts';

const GENERATED =
  'Generated by `pnpm generate:contracts` from `packages/schema/src/actions.ts`; do not edit by hand.';

function inputSummary(spec: ReturnType<typeof actionsInOrder>[number]): string {
  const schema = toJsonSchema(spec.input);
  if (schema.type !== 'object') return typeLabelOf(schema);
  const properties = summarizeProperties(schema);
  if (properties.length === 0) return 'none';
  return properties
    .map((property) => `\`${property.name}${property.required ? '' : '?'}\``)
    .join(', ');
}

function typeLabelOf(schema: Record<string, unknown>): string {
  if (typeof schema.type === 'string') return schema.type;
  if (Array.isArray(schema.anyOf)) return 'string or object';
  return 'value';
}

export function generateActionsReference(): string {
  const rows = actionsInOrder().map((spec) => [
    `\`${spec.id}\``,
    spec.label,
    inputSummary(spec),
    spec.mutates ? 'yes' : 'no',
    spec.transports.join(', '),
    spec.cli === undefined ? '' : `\`${spec.cli.usage}\``,
    spec.mcp === undefined ? '' : `\`${spec.mcp}\``,
    spec.milestone,
  ]);
  return [
    '# Turboslide actions',
    '',
    GENERATED,
    '',
    'Every operation is one action in one table; the CLI subcommands, the MCP tools, the window API and the HTTP endpoints are generated from it. Every mutating action takes `baseRevision` and rejects a stale one with 409 and the current document; every write returns the normalized result so the re-read is free. An action whose milestone has not landed answers `NotImplementedError` (501).',
    '',
    markdownTable(
      ['Action', 'Label', 'Input', 'Mutates', 'Transports', 'CLI', 'MCP tool', 'Milestone'],
      rows,
    ),
    '',
    '## Transports',
    '',
    '- `cli`: `turboslide <command> --json`, machine output on stdout, human output on stderr; exit 0, 1 (findings at the gate or a verify failure), 2 (usage or validation error). `--author agent:<runId>` and `--base-revision <n>` on every write.',
    '- `mcp`: tools named `deck_<action>` over stdio (`turboslide mcp`) or streamable HTTP at `/mcp`; render tools return image content beside the JSON.',
    '- `http`: `POST /api/actions/<id>` with the input as JSON; `GET /api/agent` for the manifest, `/openapi.json` for the contract.',
    '- `window`: `window.turboslide.studio.invoke(<id>, input)` in the studio; see `turboslide-studio`.',
    '',
    '## Write protocol',
    '',
    '1. Read: `deck.info`, then `slide.get` for the slide you will touch.',
    '2. Make the smallest change: one `block.set`, `text.replace` or `slide.update` with a mutation list; `slide.replace` only when the whole slide changes.',
    '3. Write with the `baseRevision` you read and `--author agent:<runId>`; on 409 re-read the returned document and retry once.',
    '4. Take `slide.lease` before a series of writes to one slide; release by letting it expire.',
    '5. Re-read from the response, not from memory; then render both themes and lint (`turboslide-verify`).',
    '',
    '## Mutations',
    '',
    markdownTable(
      ['op', 'Fields', 'Note'],
      [
        ['`slide.insert`', '`sectionId`, `after?`, `slide`', '`after` absent inserts first'],
        ['`slide.remove`', '`slideId`', ''],
        ['`slide.move`', '`slideId`, `sectionId`, `after?`', ''],
        [
          '`slide.set`',
          '`slideId`, `path`, `value?`',
          'JSON pointer into the slide; no value deletes',
        ],
        ['`slide.replace`', '`slideId`, `slide`', 'What the source drawer emits'],
        [
          '`block.insert`',
          '`slideId`, `slot`, `after?`, `block`',
          '`slot` is a layout slot or `plate`',
        ],
        ['`block.remove`', '`slideId`, `blockId`', ''],
        ['`block.move`', '`slideId`, `blockId`, `slot`, `after?`', ''],
        ['`block.set`', '`slideId`, `blockId`, `path`, `value?`', 'JSON pointer into the block'],
        [
          '`text.replace`',
          '`slideId`, `blockId`, `path`, `range`, `text`',
          'Typing, coalesced; range in the markup string',
        ],
        ['`section.set`', '`sections`', 'The only place order lives'],
        ['`asset.set`', '`asset`', ''],
        ['`asset.remove`', '`assetId`', ''],
        ['`deck.set`', '`path`, `value?`', 'title, theme, defaults'],
        ['`version.restore`', '`n`', 'A mutation, so it is undoable'],
      ],
    ),
    '',
    '## Errors',
    '',
    markdownTable(
      ['Class', 'HTTP', 'When'],
      generateDescribe().errors.map((error) => [
        `\`${error.name}\``,
        String(error.status),
        error.when,
      ]),
    ),
    '',
  ].join('\n');
}

export function generateBrowserApiReference(): string {
  const describe = generateDescribe();
  return [
    '# Turboslide studio browser API',
    '',
    GENERATED,
    '',
    `The adapter is \`${describe.global}\`; it is ready after the \`${describe.event}\` event, whose detail is \`describe()\`. The ownership model is Glyphfield’s: the component that owns state registers an adapter with an \`owner\` element, and the getter resolves the last registration whose owner is connected and not under \`[inert]\`, \`[hidden]\`, \`[aria-hidden="true"]\` or \`[data-active="false"]\`. Controls are found by normalized accessible label (\`aria-label\`, \`title\`, \`name\`, \`aria-labelledby\` or the wrapping \`<label>\`) and by \`data-control\` id; inspector controls read \`<block id>: <property label>\` (\`list: Size\`) with \`data-control="block.list.size"\`. A missing label throws \`RangeError\`.`,
    '',
    '## Methods',
    '',
    markdownTable(
      ['Method', 'What it does'],
      describe.methods.map((method) => [`\`${method.name}\``, method.description]),
    ),
    '',
    '## Owners',
    '',
    markdownTable(
      ['Owner', 'Active when', 'Actions'],
      describe.owners.map((owner) => [
        `\`${owner.id}\``,
        owner.when,
        owner.actions.map((id) => `\`${id}\``).join(', '),
      ]),
    ),
    '',
    '## Standard actions',
    '',
    `The six Glyphfield standard actions are handled by the API itself: ${describe.standardActions.map((id) => `\`${id}\``).join(', ')}. Everything else is delegated to the active owner.`,
    '',
    '## Window actions',
    '',
    markdownTable(
      ['Action', 'Label', 'Mutates', 'Milestone', 'Description'],
      actionsOn('window').map((spec) => [
        `\`${spec.id}\``,
        spec.label,
        spec.mutates ? 'yes' : 'no',
        spec.milestone,
        spec.doc,
      ]),
    ),
    '',
    '## Errors',
    '',
    markdownTable(
      ['Class', 'When'],
      describe.errors.map((error) => [`\`${error.name}\``, error.when]),
    ),
    '',
    '## Completion',
    '',
    'A resolved `applySource` or `invoke` is a React commit boundary, not a render: wait for the stage to re-render (two animation frames, then `document.fonts.ready`, then image decode) before reading pixels. Re-read the source after every apply; the validator may have canonicalized text.',
    '',
  ].join('\n');
}

export function generateVerificationReference(): string {
  const finding = summarizeProperties(toJsonSchema(findingSchema));
  const verifyActions = actionsInOrder().filter((spec) =>
    [
      'render.slide',
      'render.sheet',
      'lint.run',
      'fix.run',
      'validate.run',
      'export.run',
      'build.run',
      'judge.bundle',
      'diff.run',
    ].includes(spec.id),
  );
  return [
    '# Turboslide verification',
    '',
    GENERATED,
    '',
    '## Evidence actions',
    '',
    markdownTable(
      ['Action', 'CLI', 'MCP tool', 'Milestone', 'What it produces'],
      verifyActions.map((spec) => [
        `\`${spec.id}\``,
        spec.cli === undefined ? '' : `\`${spec.cli.usage}\``,
        spec.mcp === undefined ? '' : `\`${spec.mcp}\``,
        spec.milestone,
        spec.doc,
      ]),
    ),
    '',
    '## Reading a sheet',
    '',
    'Read `sheet-<theme>.json` first: `cells` maps each cell box to a slide id and number, so a judgment names a slide by id. Then open the render of the slide named. Render records carry the block boxes, line counts, font sizes and weights; read the structured record before the pixels.',
    '',
    '## The Finding schema',
    '',
    markdownTable(
      ['Field', 'Type', 'Required', 'Note'],
      finding.map((property) => [
        `\`${property.name}\``,
        property.type,
        property.required ? 'yes' : 'no',
        property.description ?? '',
      ]),
    ),
    '',
    '`severity` 3 must fix (the gate), 2 should fix, 1 polish. `proposal` is prose a fixer acts on without judgment; `fix` is present when the fix is mechanical. `source` is `lint`, `judge:<lens>` or `skeptic`.',
    '',
    '## Rules',
    '',
    markdownTable(
      ['Rule id', 'Layer', 'Severity', 'Fix', 'Check'],
      rulesInOrder().map((rule) => [
        `\`${rule.id}\``,
        rule.layer,
        String(rule.severity),
        rule.fix ? 'yes' : 'no',
        rule.check,
      ]),
    ),
    '',
    '## Judge lenses',
    '',
    'One lens each, with stable names: layout, visual consistency and dark mode, copy and case, accuracy, completeness, art direction. Judges read the sheets by cell map first and then the renders, alongside the render records and the lint findings, and return findings at severity 2 and 3 only with evidence and a concrete proposal. A skeptic keeps or drops each finding; fixers work one slide each under a lease and report `verifiedBothThemes` and `residual`.',
    '',
    '## Completion rules',
    '',
    '- An overflow finding is a failure.',
    '- A severity 3 finding blocks the ship step; the known list (`known-findings.json`) is the honest state of the deck, not a place to hide new findings.',
    '- A resolved export call is not a verified export: read `export-report.json` and require `passed` and `geometryInBounds`.',
    '- A frame timestamp is not an image: read the file and its dimensions.',
    '- A resolved apply is only a React commit: wait for the render before reading pixels.',
    '- A claim about a deck names the revision it was verified at.',
    '',
  ].join('\n');
}

/** Reference files by repo-relative path. */
export function generateSkillReferences(): Record<string, string> {
  return {
    'skills/turboslide-create/references/grammar.md': generateGrammar(),
    'skills/turboslide-api/references/actions.md': generateActionsReference(),
    'skills/turboslide-studio/references/browser-api.md': generateBrowserApiReference(),
    'skills/turboslide-verify/references/verification.md': generateVerificationReference(),
  };
}
