// Regenerates src/sprite.ts from assets/sprite.svg (SPEC 5.1: "sprite.ts, one entry per symbol").
// Run with `pnpm --filter @turboslide/theme build:sprite` (Node type stripping, no build step).
// The sprite file is the source of truth for the symbol bodies; the icon name list is
// @turboslide/schema/icons ICON_NAMES, and sprite.test.ts asserts the two agree.
import { readFileSync, writeFileSync } from 'node:fs';

export type ParsedSymbol = { id: string; viewBox: string; body: string };

export function parseSprite(svg: string): ParsedSymbol[] {
  const out: ParsedSymbol[] = [];
  const pattern = /<symbol id="([^"]+)" viewBox="([^"]+)">([\s\S]*?)<\/symbol>/g;
  for (const match of svg.matchAll(pattern)) {
    const [, id, viewBox, body] = match;
    if (id === undefined || viewBox === undefined || body === undefined) continue;
    out.push({ id, viewBox, body: body.trim() });
  }
  return out;
}

export function iconNameOf(symbolId: string): string {
  return symbolId === 'gt-mark' ? symbolId : symbolId.replace(/^i-/, '');
}

/** A single-quoted TypeScript string literal, the form prettier writes for these values. */
export function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** A property key: bare when it is an identifier, quoted otherwise, as prettier normalizes keys. */
function key(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

export function renderSpriteModule(symbols: ReadonlyArray<ParsedSymbol>): string {
  const entries = symbols
    .map(
      (symbol) =>
        `  ${key(iconNameOf(symbol.id))}: {\n    id: ${quote(symbol.id)},\n    viewBox: ${quote(symbol.viewBox)},\n    body: ${quote(symbol.body)},\n  },`,
    )
    .join('\n');
  return `// Generated by scripts/build-sprite.ts from assets/sprite.svg; do not edit by hand. The sprite is
// the deck's (Prototemplate/deck/parts/head.html lines 398 to 462): 63 Heroicons 20 solid symbols
// (MIT, tailwindlabs/heroicons) plus gt-mark at viewBox "-8 214 1213 771" (SPEC 5.1). Icons are
// written as <svg class="ic ok" aria-hidden="true"><use href="#i-check-circle"/></svg>
// (DECK-GRAMMAR.md:40); the renderer inlines spriteMarkup() once per document.
import type { IconName } from '@turboslide/schema/icons';
import { iconSymbolId } from '@turboslide/schema/icons';

export type SpriteSymbol = { id: string; viewBox: string; body: string };

export const SPRITE: Readonly<Record<IconName, SpriteSymbol>> = {
${entries}
};

export const SPRITE_NAMES = Object.keys(SPRITE) as ReadonlyArray<IconName>;

/** One <symbol> element. */
export function symbolMarkup(name: IconName): string {
  const symbol = SPRITE[name];
  return \`<symbol id="\${symbol.id}" viewBox="\${symbol.viewBox}">\${symbol.body}</symbol>\`;
}

/** The hidden sprite the stage carries once; all symbols by default, or the named subset. */
export function spriteMarkup(names: Iterable<IconName> = SPRITE_NAMES): string {
  const symbols = [...names].map(symbolMarkup).join('');
  return \`<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute" aria-hidden="true">\${symbols}</svg>\`;
}

export type IconMarkupOptions = {
  /** 'ok' | 'warn' | 'no' | 'info' for the semantic hues, nothing for a monochrome glyph. */
  color?: 'ok' | 'warn' | 'no' | 'info';
  /** 'ext' for the 16 px external glyph after a link (head:121). */
  ext?: boolean;
};

/** The deck's icon markup: <svg class="ic ok" aria-hidden="true"><use href="#i-check-circle"/></svg>. */
export function iconMarkup(name: IconName, options: IconMarkupOptions = {}): string {
  const classes = ['ic'];
  if (options.color !== undefined) classes.push(options.color);
  if (options.ext) classes.push('ext');
  return \`<svg class="\${classes.join(' ')}" aria-hidden="true"><use href="#\${iconSymbolId(name)}"/></svg>\`;
}

/** The standalone mark at a stated size (slide 02: 132 by 84). */
export function markMarkup(width: number, height: number, className?: string): string {
  const cls = className === undefined ? '' : \` class="\${className}"\`;
  return \`<svg\${cls} width="\${width}" height="\${height}" fill="currentColor" aria-hidden="true"><use href="#gt-mark"/></svg>\`;
}

/** The GT word (head:70-74): the mark sized to the text with the letters kept for assistive technology. */
export const GT_WORD_MARKUP =
  '<span class="gt-word"><svg aria-hidden="true"><use href="#gt-mark"/></svg><span class="sr">GT</span></span>';
`;
}

export function buildSprite(spritePath: URL, modulePath: URL): number {
  const symbols = parseSprite(readFileSync(spritePath, 'utf8'));
  writeFileSync(modulePath, renderSpriteModule(symbols));
  return symbols.length;
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === new URL(`file://${process.argv[1]}`).href
) {
  const count = buildSprite(
    new URL('../assets/sprite.svg', import.meta.url),
    new URL('../src/sprite.ts', import.meta.url),
  );
  process.stderr.write(`build-sprite: wrote ${count} symbols to src/sprite.ts\n`);
}
